### ISSUE TITLE
Move Azure config from V1 CLI (asm) to V2 CLI (arm)

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#1035]
In the last year Azure deployed a new way to manage and configure resources called Azure Resource Manager (ARM).  It is much faster than the service manager (ASM)( and is the model all new project should use.

The benefit to PKB is faster provisioning of resources, fewer "leaked" resources due to timeouts, and a more consistent network config.

The current usage of ASM is outdated and does not reflect the speed or capabilities of Azure.

**Comment by k1xme** [comment]
+1. I was benchmarking Azure in the past 3 weeks. These 2 existing deployment methods confused me a lot.

**Comment by voellm** [comment]
There is a pull request for this now... https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1112

I'm going to close this request and let the pull request complete.
