### ISSUE TITLE
Kubernetes + Perfkit

### ISSUE THREAD

**Issue by nehayward** [GoogleCloudPlatform/PerfKitBenchmarker#1064]
I think there should be more documentation on how to set this up. I have a cluster setup but I haven't been able to get perfkit to run on it.

**Comment by voellm** [comment]
I agree.  There is some help here on Docker - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/FAQ

What is needed is a Wiki on Kubernetes though it is similar to Docker in how it works here.

Start with --cloud=kubernetes and that should get you going.
