### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#108]
Today PKB handles Centos, Redhat, Ubuntu, Debian, ... but does not handle Windows.

There are some unique challenges here with the biggest being how to bootstrap Windows to allow remote command execution.  On GCE we can do this with startup scripts.

For the actual command automation I think it makes the most sense to use powershell vs ssh like we do on LINUX.  However that might tie running Windows workloads to running from Windows machines.

Other options include putty, etc.

Suggestions on how to architect this are welcome.

**Comment by voellm** [comment]
Eric have a number of fixes that add support for Windows.  The first change is getting PKB to run on Windows machines (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/274).  The second change is to add support for benchmarking Windows vs the current Linux Support.

**Comment by ehankland** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/311
