### ISSUE TITLE
fio: KeyError: 'fio_run_for_minutes' after flag define was removed

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#1098]
PR #1066 removed the flag `fio_run_for_minutes` but all the references were not removed.

Specifically in this line:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/fio_benchmark.py#L133

Now `WarnOnBadFlags()` fails with a KeyError when `--fio_jobfile` is set due to `fio_run_for_minutes` not being defined.

**Comment by ehankland** [comment]
Thanks for catching this - I verified that the above PR fixes this behavior
