### ISSUE TITLE
Need lock when creating gce vm instances.

### ISSUE THREAD

**Issue by yuyantingzero** [GoogleCloudPlatform/PerfKitBenchmarker#118]
Need a lock to wrap around instance_counter (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/gcp/gce_virtual_machine.py#L70). BenchmarkSpec creates GceVM objects serially, but when running more than one benchmarks in parallel, pkb might try to create 2 vms with same name.

**Comment by cmccoy** [comment]
Closed by #265.
