### ISSUE TITLE
vm_util undefined breaks master

### ISSUE THREAD

**Issue by vhe182** [GoogleCloudPlatform/PerfKitBenchmarker#1195]
Since #1185, master breaks.  Error pertains to undefined 'vm_util' in:
perfkitbenchmarker/linux_packages/aerospike_server.py

 See log below for more details.

https://travis-ci.org/GoogleCloudPlatform/PerfKitBenchmarker/jobs/175834460

**Comment by vhe182** [comment]
A short-term fix is re-adding `from import perfkitbenchmarker import vm_util` to the previously mentioned file.

**Comment by meteorfox** [comment]
Confirmed.

I pulled latest from master and ran tox.

Several unit tests are failing with following error message:
```
NameError: name 'vm_util' is not defined
```

**Comment by meteorfox** [comment]
PR #1185 did the clean up of the `vm_util` module, but PR #1190 introduce a line using `vm_util.Retry` which is where it seems is failing at.

**Comment by vhe182** [comment]
Proposed fix has been tested and confirmed to work.  Closing Issue #1195
