### ISSUE TITLE
Calls to `aws` should specify JSON output.

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#121]
The default output format for `aws` is JSON, but [this can be changed in a config file](http://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html).  Calls to `aws` in PerfKitBenchmarker should explicitly set `--output=json`, in case the user has specified a different default output format.

**Comment by voellm** [comment]
Connor this is fixed is it not?

**Comment by cmccoy** [comment]
No, not fixed.

**Comment by cmccoy** [comment]
Opened pull request #167 to address.

**Comment by cmccoy** [comment]
Closed by #167.
