### ISSUE TITLE
GCP image aliases are deprecated 

### ISSUE THREAD

**Issue by gareth-ferneyhough** [GoogleCloudPlatform/PerfKitBenchmarker#1213]
See this output from gcloud instances create: 
`WARNING: Image aliases are deprecated and will be removed in a future version. Please use --image-family=ubuntu-1404-lts and --image-project=ubuntu-os-cloud instead.`

**Comment by dlott** [comment]
Fixed with https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/79b2cce0bed0155baf64b190d33e98109009081a
