### ISSUE TITLE
fio benchmark should support --log_hist_msec

### ISSUE THREAD

**Issue by noahl** [GoogleCloudPlatform/PerfKitBenchmarker#1245]
This is a feature request for the fio benchmark. Could you please support enabling fio's `log_hist_msec` option? It is similar to `log_avg_msec`, which you already support, but instead of averaging latencies over a time interval, it records percentiles over a time interval. I think it would yield much more interesting data than `log_avg_msec`.

**Comment by meteorfox** [comment]
This feature seems to have been introduced in fio 2.15, according to this PR.

https://github.com/axboe/fio/commit/1e613c9c23932006263dd8334007865f32891a0c

So we will need to bump the fio version in `linux_packages/fio.py` from 2.7 -> 2.15

**Comment by noahl** [comment]
@meteorfox good point.

**Comment by yuyantingzero** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1300
