### ISSUE TITLE
GPU benchmark - image does not exist: ami-a9d276c9

### ISSUE THREAD

**Issue by gareth-ferneyhough** [GoogleCloudPlatform/PerfKitBenchmarker#1270]
The AWS image `ami-a9d276c9` does not exist anymore, and it is hard-coded in the `gpu_pcie_bandwidth` benchmark. I believe that this was the latest Ubuntu16.04 image. The benchmark should be modified so that it does not depend on a specific AMI; `describe-images` could be used instead to get the latest 16.04 image.

**Comment by gareth-ferneyhough** [comment]
This AMI does in fact exist and can be found using `describe-images` on the CLI by passing in `--region us-west-2`. Perhaps the AWS provider needs to be modified so that a region can be specified along with an AMI.

**Comment by meteorfox** [comment]
I think PKB's `--zone` flag maps to the AWS' region.

See: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/aws/aws_virtual_machine.py#L170
