### ISSUE TITLE
PerfKitExplorer Dashboard for every benchmark

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#129]
The benchmarker can output the final results in "Text", "Json", etc.  One output it can do is to Google BigQuery.  This allows for big data mining.

To make this dashboarding on BQ easier we released a tool called PerfKitExplorer.  

The work for this issue is to create a PerfKitExplorer dashboard for every benchmark.

Side note -  the explorer is extensible so we could just as easily export to MySQL and create a MySQL widget for the Explorer to analyze results.  We just have not done that work yet.

**Comment by jmuharsky** [comment]
Widget extensibility isn't so much a "feature" right now as a "plan".  The next release (v23) in addition to a significant overhaul of the sidebar UX, will better factor the code to support different types of widgets.  If I we wanted a "quick and dirty" solution, it would be to add the REST URL to the widget/data config.

Realistically, we're looking at having support (and tutorials/documentation) for custom widgets in the Q2/Q3 timeframe.

**Comment by klausw** [comment]
I've retargeted this to v0.19.0 since the corresponding pull request #332 is still open and no longer targeting the current milestone. If it's ready now, let me know and we can see if we can still get it in v0.18.0.

**Comment by ehankland** [comment]
@yuyantingzero  Release v0.19.0 is starting - should this get pushed further back, or will it be ready?

**Comment by yuyantingzero** [comment]
I will push it further back. Actually, this will be checked into PerfKitExplorer as discussed offline.

**Comment by cmccoy** [comment]
This was moved to PerfKitExplorer.
