### ISSUE TITLE
unable to run ./pkb.py --help command i get series of ./pkb.py: line 58: import: command not found

### ISSUE THREAD

**Issue by goupadhy** [GoogleCloudPlatform/PerfKitBenchmarker#1292]
Hi,

New to perf benchmarking, python and ubuntu world :)
I'm unable run this command for doing some performance bench marking on Ubuntu OS. I tried running the command by navigating to the folder where i have cloned the perfkit tool.  root@---:~/PerfKitBenchmarker/perfkitbenchmarker# ./pkb.py --help. when i do this 

./pkb.py: line 58: import: command not found
./pkb.py: line 59: import: command not found
./pkb.py: line 60: import: command not found
./pkb.py: line 61: import: command not found
./pkb.py: line 62: import: command not found
./pkb.py: line 63: import: command not found
./pkb.py: line 64: import: command not found
./pkb.py: line 65: import: command not found
./pkb.py: line 66: import: command not found
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker
from: can't read /var/mail/perfkitbenchmarker.configs
from: can't read /var/mail/perfkitbenchmarker.linux_benchmarks
from: can't read /var/mail/perfkitbenchmarker.publisher
./pkb.py: line 96: LOG_FILE_NAME: command not found
./pkb.py: line 97: REQUIRED_INFO: command not found
./pkb.py: line 98: syntax error near unexpected token `('
./pkb.py: line 98: `REQUIRED_EXECUTABLES = frozenset(['ssh', 'ssh-keygen', 'scp', 'openssl'])'

I also tried with command but getting same import error:

 python ./pkb.py --help
Traceback (most recent call last):
  File "./pkb.py", line 68, in <module>
    from perfkitbenchmarker import archive
ImportError: No module named perfkitbenchmarker

Can some one help me with the issue?

Thanks, 
Goutham

**Comment by tedhtchang** [comment]
Please run ./pkb.py from PerfKitBenchmarker/

**Comment by goupadhy** [comment]
Thanks Ted, but when i run that in PerfKitBenchmarker/ getting below error:
root@iZwz9cd2l7ux0jfv4evtizZ:~/PerfKitBenchmarker# ./pkb.py --help
Traceback (most recent call last):
  File "./pkb.py", line 19, in <module>
    from perfkitbenchmarker.pkb import Main
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/__init__.py", line 15, in <module>
    import gflags as flags  # NOQA
ImportError: No module named gflags

**Comment by tedhtchang** [comment]
You need to follow the "Install PerfKit Benchmarker dependencies" in the README.

**Comment by gareth-ferneyhough** [comment]
Specifically, you need to install the prerequisites with pip:
```
$ cd /path/to/PerfKitBenchmarker
$ sudo pip install -r requirements.txt
```

**Comment by zoumra** [comment]
same issue, event with 

> Requirement already satisfied: python-gflags==3.1.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 14))
