### ISSUE TITLE
PKB now tries to connect to InfluxDB by default

### ISSUE THREAD

**Issue by tedsta** [GoogleCloudPlatform/PerfKitBenchmarker#1294]
Resulting in this error message: 

`2017-02-18 05:52:31,642 59982a9d MainThread ERROR    Error connecting to the database:  [Errno 111] Connection refused`

We should make the InnoDB publisher opt-in like the other publishers. `--influx_uri` should be None by default. https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1278/files#diff-498e2d3e3f4e5a7438518dfcb7075ccbR118

**Comment by meteorfox** [comment]
@besanradwan PTAL

**Comment by besanradwan** [comment]
@tedsta please check PR I tagged you in for fix.
