### ISSUE TITLE
The iperf text results dont label the internal and external IP results

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#130]
When the final results come out of iperf on the command line the results dont differentiate the internal and external IP results.  You can likely tell from the diff in performance but we should be explicit.

This may also hold for the network benchmarks.

The detailed JSON block does including the right information so it should be a matter of updating the output text to be more detailed.

**Comment by voellm** [comment]
Connor is working on this and there is a fix out ... https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/178

**Comment by cmccoy** [comment]
#178 is merged - it will make 0.13.0.
