### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by AdamIsrael** [GoogleCloudPlatform/PerfKitBenchmarker#1325]
This was discussed in issue #193 a couple years back. I'm wondering if now would be a good time to re-consider opening a Slack for the community? FWIW, Kubernetes (referenced as an example in that issue) now has a thriving Slack community.

I know personally a Slack (or irc channel) would help me stay connected with what's happening in the community.

**Comment by gareth-ferneyhough** [comment]
Thanks for bringing this up - it has been on our plate for a while. We will discuss as a team and see what solutions are feasible for us before we put our ideas here.

**Comment by gareth-ferneyhough** [comment]
Either Slack or IRC would be great, and the team here is on board with it, although we don't anticipate being readily reachable at all times (issues will still be useful for getting attention). I am interested in hearing a few more opinions on which tool people prefer (Slack, or IRC). @AdamIsrael: do you have a preference? 

@meteorfox do you have any thoughts on this?

**Comment by meteorfox** [comment]
I think is a great idea. In terms of tools, Slacks seems very popular. Besides IRC, there's also Gitter.

**Comment by gareth-ferneyhough** [comment]
Great, I personally vote for Slack. @AdamIsrael: do you want to set this up, since you brought it up? I am happy to do so as well if you prefer.

**Comment by joelio** [comment]
+1 (Either slack or IRC... or both!)

**Comment by gareth-ferneyhough** [comment]
I finally got around to creating an IRC channel on Freenode, #PerfKitBenchmarker! Thanks for everyone's input.
