### ISSUE TITLE
RobustRemoteCommand fails is run after the VM is restarted

### ISSUE THREAD

**Issue by gareth-ferneyhough** [GoogleCloudPlatform/PerfKitBenchmarker#1344]
`RobustRemoteCommand` fails if it is run on a VM that has been rebooted, because the `/tmp/pkb` directory has been deleted. `linux_virtual_machine.py` should recreate the tmp directory if necessary.

**Comment by tedsta** [comment]
Just out of curiosity, in which benchmark(s) do VMs get rebooted?

**Comment by gareth-ferneyhough** [comment]
Stencil2D, or any benchmarks that install the cuda_toolkit package.
