### ISSUE TITLE
GCP: Only 4 of 9 VMs spawn on Hadoop Terrasort benchmark

### ISSUE THREAD

**Issue by timothyeharris** [GoogleCloudPlatform/PerfKitBenchmarker#137]
I'm using an f1-micro instance on GCP as my orchestrator for running pkb.

When I execute the Hadoop Terrasort benchmark against an n1-standard-4 machine type, I see 9 disks successfully created, but then only 4 vm's successfully start.  The other 5 continue retrying until timeout, and pkb tears down the resources and never executes the benchmark.  It's a different 4 each time... on one run, -1,-3,-4,-7, and -8 were missing... but in another run -1,-2,-5,-6, and -7 were missing.  That said, it always seems to be the same number of instances that end up missing.

I've only tried this against GCP in us-central1-a.  

I see "Got exception running _CreateResource: Creation of DebianBasedGceVirtualMachine failed" for the instances that don't start.

Any ideas why this is happening?

**Comment by ehankland** [comment]
The first thing that comes to mind is that it might be a quota problem (probably #cores) since you are always able to create the same number of machines. A quick way to verify this would be to look inside the log file and check for the stdout/stderr from the create command.

**Comment by timothyeharris** [comment]
I'll take a look at the log files, however the dashboard is showing I've never used more than 13 of my 24 available CPUs.

**Comment by voellm** [comment]
There are other resources like networks, etc.  When looking at "quotas"
does everything look ok?

On Fri, Feb 27, 2015 at 1:03 PM, Tim Harris <notifications@github.com>
wrote:

> I'll take a look at the log files, however the dashboard is showing I've
> never used more than 13 of my 24 available CPUs.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/137#issuecomment-76471217>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by timothyeharris** [comment]
Everything looks fine now.  Just didn't even think to look at quotas (or to multiply instances x4 for a n1-standard-4).  I put a request in to increase quota allowances, and now it's working fine.
