### ISSUE TITLE
AWS hadoop runs never complete

### ISSUE THREAD

**Issue by BEJadon** [GoogleCloudPlatform/PerfKitBenchmarker#142]
Hi,
I'm very new to this and am having trouble with hadoop and aws.

Running 0.10.1.  
Cmd:  /pkb.py --cloud=AWS --benchmarks=hadoop_terasort --machine_type=t1.micro --terasort_num_rows=1000

Is there a minimum machine_type? I would think 1000 rows would go very quickly but it never completed, even after 3 hours of running.  Ideas/Suggestions?
Thanks,

**Comment by cmccoy** [comment]
There should be a run-specific verbose log file in `/tmp/perfkitbenchmarker/run_<run_uri>/pkb.log` - could you paste the last few commands run?

I wouldn't be surprised if a t1.micro didn't have enough memory to run Hadoop, but I haven't tried.

**Comment by BEJadon** [comment]
yeah that was it.  Might consider adding a note to the pkb help output.  Something along the lines of "resource intensive workload, may not work well with micro tiers".

**Comment by cmccoy** [comment]
Glad to hear it.  I opened #144 to track updating the help.
