### ISSUE TITLE
Iperf links under test

### ISSUE THREAD

**Issue by crbertoldo** [GoogleCloudPlatform/PerfKitBenchmarker#143]
Hi,

Could anyone help me to understand the links under test when running an Iperf test, pls? I could see some different IPs in Terminal (besides the two assigned to my VMs), so I guessed they are from different zones. If so, are the zones chosen randomly? 

Thanks in advance.

**Comment by cmccoy** [comment]
Unless you specified multiple comma-separated zones via the `--zones` flag, the VMs will be created in the same zone.

By default, iperf test runs against both the internal and external IP of the pair of VMs.  You can control this behavior with the `--ip_addresses` flag.

**Comment by crbertoldo** [comment]
cmccoy, thanks a lot!

So if not inputting the --ip_addresses flag, the tests are performed between both VMs. This way, are we testing the internal network (virtual and/or physical) when testing "internal IP VM1 <--> internal IP VM2 *and* internal IP VM2 <--> internal IP VM1" and testing the internet link when testing "internal IP VM1 <--> external IP VM2 *and* internal IP VM2 <--> external IP VM1"?

I didn't understand what to conclude with the four results shown yet.

**Comment by cmccoy** [comment]
That's exactly right. The bidirectional testing may be useful when:

* Multiple zones/regions are used the test, in case the the network performance is asymmetric.
* One or more static VMs are used (that is, VMs not created by PerfKitBenchmarker), useful for measuring egress / ingress bandwidth from a cloud provider.

When you have two VMs in the same zone (the default behavior), I would expect the two internal and two external measurements to be consistent.

**Comment by crbertoldo** [comment]
Thanks a lot.

In fact, about the measurements consistency, same scenario, should not the "internal<-->external" measurements be smaller than the "internal<-->internal" measurements naturally? Sorry if that was you meant...

**Comment by cmccoy** [comment]
Yes, the result over the external IP should be lower than the tests over the internal IP.
I meant to say: with the default settings the two internal tests (VM1 -> VM2 internal, VM2 -> VM1 internal) should be fairly consistent with one another, and the same for the two external (VM1 -> VM2 external, VM2 -> VM1 external) tests.
There is no expectation that the internal tests will match the external.

Thanks for your interest!

**Comment by crbertoldo** [comment]
Thanks a lot cmccoy, it's now very clear. I'm trying to explore it to evaluate NFV-Infrastructures.
