### ISSUE TITLE
SSD vs. Standard Scratch & Persistent disk info doesn't make it to results

### ISSUE THREAD

**Issue by timothyeharris** [GoogleCloudPlatform/PerfKitBenchmarker#146]
I ran the block_storage_workload benchmark three times against an n1-standard-1 instance in us-central-1a.  On one, I left all options at standard.  On another, I specified SSD scratch disks.  On the last, I specified SSD one GCE Persistent Disk.

I see that there are significant performance differences between the three runs (as you'd expect), but there is nothing in the results data that tells me how the instances were configured :-(

For the results table, there should be a column representing every possible command-line option you can pass in to pkb.py.  For example, there should be a column called "gce_num_local_ssds", and if that parameter isn't passed in to the script, it should populate the result file with zero.

Without the ability to go back and look at initial conditions that ended in a specific result, it's much harder to do comparative analysis.

**Comment by voellm** [comment]
All flags should have meta data in the labels field of the json output.
The printed output needs improvement and there is an issue open for it.

**Comment by timothyeharris** [comment]
Is there an updated schema for BQ that I've missed?  I'm not seeing any information in my BQ results table that would enable disambiguation.  Nothing in the labels field indicates how the vms were configured.

**Comment by cmccoy** [comment]
@timothyeharris is correct - those fields aren't making it into the metadata, but need to.

That said, I'm hesitant to include *all* flag values as metadata: most of them are irrelevant for any given benchmark / cloud provider combination, and logging them will make it hard to identify the important metadata for a sample.

**Comment by voellm** [comment]
Agreed but we should have a label for the storage used just like we do for
the type of IP.

Timothy - as a temporary workaround you can specify extra labels using the
metadata flag.  These get added to the json result output.

**Comment by cmccoy** [comment]
Closed by #277.
