### ISSUE TITLE
Clarification on Timestamps and End-to-end runtimes

### ISSUE THREAD

**Issue by timothyeharris** [GoogleCloudPlatform/PerfKitBenchmarker#147]
I'm trying to figure out when the "timestamp" gets written for any given test.  Is it when the test starts, or when the test finishes?  (Is it possible to get both?)

I'm also trying to figure out end-to-end runtime...  is it inclusive of setting up the environment (creating networks, spawning vm's, etc)?  In cases where packages are being installed to run the benchmark, does the end-to-end runtime include this time?

I'm trying to figure out how to isolate (and benchmark) the FABRIC CONTROLLER of the cloud providers to see what kind of overhead each has....  apart from cluster_boot, there really isn't anything that measures the overhead of orchestration in the benchmarks...

If you can control variables like OS, Image, Packages, etc... then the end-to-end runtime is useful for understanding the differences in fabric controller overhead.

**Comment by cmccoy** [comment]
The timestamp is generated at the end of the benchmark run, before resource cleanup happens.  Including the start of the benchmark wouldn't be difficult, but isn't implemented presently.

> I'm also trying to figure out end-to-end runtime... is it inclusive of setting up the environment (creating networks, spawning vm's, etc)? In cases where packages are being installed to run the benchmark, does the end-to-end runtime include this time?

Yes, the End to End Runtime reported includes resource provisioning (VMs, disks, etc), benchmark runtime, and resource teardown time.

**Comment by timothyeharris** [comment]
Thanks for this.  So in order for me to control all the variables, I'll need to create a VM that I can keep consistent between the various cloud providers (fun) :-)

**Comment by timothyeharris** [comment]
Should I close this issue and open a separate one specifically for the request to implement "start time stamp" for the benchmarks?

**Comment by cmccoy** [comment]
Yes, please do. Thanks!
