### ISSUE TITLE
Block_storage benchmark fails on Azure

### ISSUE THREAD

**Issue by timothyeharris** [GoogleCloudPlatform/PerfKitBenchmarker#149]
I'm having a problem with the block_storage benchmark saying : 

"Package libaio1 is not available, but is referred to by another package.
 This may mean that the package is missing, has been obsoleted, or
 is only available from another source

STDERR: Warning: Permanently added '23.99.192.174' (ECDSA) to the list of known hosts.
 E: Unable to locate package libaio-dev
 E: Package 'libaio1' has no installation candidate"

It appears that it continues on to build FIO from GIT, but then the block_storage benchmark fails (mismatch perhaps?)

**Comment by voellm** [comment]
What image?

**Comment by timothyeharris** [comment]
b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server
 -20150123-en-us-30GB

**Comment by cmccoy** [comment]
I believe 22214a1cbfebfa183bd1d3379ad35228c9d45f95 resolved this.
