### ISSUE TITLE
epel-release not available for RHEL images

### ISSUE THREAD

**Issue by akrzos** [GoogleCloudPlatform/PerfKitBenchmarker#153]
The epel-release package for RHEL images on GCP is not currently available and prevents bonnie++ benchmark and sysbench oltp benchmark from running on RHEL images.  The Centos images have the extras repository enabled and can yum install epel-release without issue.  Either the image on GCP should be fixed or the framework must be robust enough to determine that the epel may need to be installed via url as it was prior to PR #99.  If a static url is used, the package is different between RHEL 6 & 7.

**Comment by voellm** [comment]
What do you think is the best course here?

If we go the links route what links do you recommend?

One more q... What is the best way to deyetmine the image RedHat?

**Comment by ehankland** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/154 fixes this - I tried running bonnie++ (which requires EPEL) on RHEL 6/7 and it successfully installed.

**Comment by akrzos** [comment]
@voellm I'll ask if there is a static url for the latest epel-release package per el6 and el7.

@ehankland Looks great, Thanks for the fast PR, hopefullyt it gets merged quick. :+1: 

On another note, the iperf only attempts to install the el7 version so it fails on RHEL 6.  The package that is built for el6 is at: http://pkgs.repoforge.org/iperf/iperf-2.0.4-1.el6.rf.x86_64.rpm

Do I need to open a second issue for iperf to be fixed?

**Comment by ehankland** [comment]
EPEL6 contains an iperf package - now that EPEL6 gets installed correctly on RHEL 6, iperf will also work. EPEL7 only contains iperf3, which is why we have to directly get the rpm. I verified this by running iperf (with the fix) on RHEL 6.

**Comment by ehankland** [comment]
Merged the fix into dev
