### ISSUE TITLE
netperf failed, due to missing commands (killall, patch, gcc)

### ISSUE THREAD

**Issue by kjellgren** [GoogleCloudPlatform/PerfKitBenchmarker#1538]
Running the netperf test on static VM with Centos 7 cloud image fail.

I fixed it by ``yum install`` following on the VM 

- psmisc
- patch
- gcc

**Comment by yuyantingzero** [comment]
if using non debian/ubuntu based images, make sure to use --os_type flag.
Closing, feel free to reopen if you have more questions.
