### ISSUE TITLE
ValueError: NUMA Node(s) could not be found in lscpu value:

### ISSUE THREAD

**Issue by zilingliyu** [GoogleCloudPlatform/PerfKitBenchmarker#1539]
Hello everyone：
  I use unixbench to test a Ubuntu host, an error 'ValueError: NUMA Node (s) could not be found in lscpu value:'
![qq 20171114153941](https://user-images.githubusercontent.com/26271856/32768259-10cdaae0-c952-11e7-9feb-1d15bac0fe76.png)
When I execute 'lscpu' on the host being tested, it shows:
![qq 201711141542578888](https://user-images.githubusercontent.com/26271856/32768378-877278e2-c952-11e7-901e-d8feb65169e2.png)
What is the reason?

**Comment by gareth-ferneyhough** [comment]
The regex in `linux_virtual_machine.py` at the line in question is searching for the literal 'NUMA Node(s)'. This is typically below the 'Socket(s)' line and above 'Vendor ID:'. Looks like your output is in Chinese which is messing up the regex.
