### ISSUE TITLE
any way to choose the GCP network tier for iperf tests

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/PerfKitBenchmarker#1547]
For example is it possible to run this command:
`$ ./pkb.py --cloud=GCP --zones=us-central1-a --benchmarks=iperf,ping --networkTier=premium`

`$ ./pkb.py --cloud=GCP --zones=us-central1-a --benchmarks=iperf,ping --networkTier=standard`

https://cloud.google.com/network-tiers/

**Comment by gareth-ferneyhough** [comment]
There is no support for network tiers in PKB at the moment.

**Comment by Manouchehri** [comment]
This was add in 3e57a60b2f425e1c1770969a34e58188f8792994.

(I found this ticket during a Google search.)

**Comment by cobookman** [comment]
@Manouchehri Thanks for making my day! Always great to see an email with a multi-year old issue be closed out. Thank you!
