### ISSUE TITLE
Please record timestamp when benchmark begins

### ISSUE THREAD

**Issue by timothyeharris** [GoogleCloudPlatform/PerfKitBenchmarker#155]
Right now, we get the timestamp of when a benchmark finishes along with end-to-end runtime.  The end-to-end runtime is inclusive of setting up the environment and booting the machine, etc.

It would be nice if we got a timestamp when the whole process starts, a timestamp when the benchmark itself starts, a timestamp when the benchmark ends, and a timestamp when the whole process ends.  IMO, the "end-to-end runtime" field could be deprecated.  I'd rather do the math myself :-)

This will enable more apples-to-apples comparisons between instance types.

**Comment by akrzos** [comment]
:+1: 
When running against a static vm, I still receive an end-to-end runtime metric too.  It would definitely be useful to include timestamps / runtimes throughout all stages of PerfKitBenchmarker (Prepare, run, cleanup, total)

**Comment by voellm** [comment]
Skyler want to take this on?

**Comment by skschneider** [comment]
Sure, sounds pretty straightforward and useful.

**Comment by skschneider** [comment]
More detailed timing information has been added in #171. Timing information for each benchmark is reported as a sample, similar to End to End Runtime. You can enable the most information with --timing_measurements=runtimes,timestamps
