### ISSUE TITLE
time_file_path should be different on OS X

### ISSUE THREAD

**Issue by kindermoumoute** [GoogleCloudPlatform/PerfKitBenchmarker#1563]
# Issue
I encountered an issue when using PKB on OS X because `time` is not GNU time.

# Possible solution
Use `gtime`:
```
brew install gnu-time
```

And [`time_file_path`](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/1d1bca07e92a935cdf8951dd2416d911729985ba/perfkitbenchmarker/vm_util.py#L295) should be `'/usr/local/bin/gtime'`.

**Comment by asaksena** [comment]
The timing feature will be ignored on Darwin / macOS similar to windows. A utility method is being added to detect if pkb is running on OS X variants.

**Comment by asaksena** [comment]
The fix has been pushed https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/c03488a1e4839bd622451cf2788b6c5ca0ed30e1
Please close after verification.

**Comment by kindermoumoute** [comment]
It works for me. Thanks!
