### ISSUE TITLE
Azure Stack PerfKitBenchmarker

### ISSUE THREAD

**Issue by gsee2000** [GoogleCloudPlatform/PerfKitBenchmarker#1567]
Hi All,

Possibly not the right place, but as a question to the community, I wondered if anyone had made a branch or version of this for Azure Stack?

Cheers

G

**Comment by s-deitz** [comment]
We are not aware of any branch for Azure Stack. If anybody is interested in doing so, we'd be happy to fold this into PKB.

**Comment by gsee2000** [comment]
I have now created and put in a merge request for the Azure Stack provider. Currently awaiting this to be verified, and hopefully approved!
