### ISSUE TITLE
Example run on AWS

### ISSUE THREAD

**Issue by zledwon** [GoogleCloudPlatform/PerfKitBenchmarker#1574]
I think default AWS run example on http://googlecloudplatform.github.io/PerfKitBenchmarker/getting-started in "EXAMPLE RUN ON AWS" section should be changed to:
`./pkb.py --cloud=AWS --benchmarks=iperf --machine_type=t2.micro
`
t1.micro => t2.micro

as t1.micro was replaced by t2.micro and t1.micro does not support Placement Groups.
It returns "Placement groups may not be used with instances of type 't1.micro'" error.

**Comment by ehankland** [comment]
Thanks for pointing that out - fixed in the above PR
