### ISSUE TITLE
Instance mapping to know the link properties

### ISSUE THREAD

**Issue by crbertoldo** [GoogleCloudPlatform/PerfKitBenchmarker#158]
Hi,

Please, is it possible to know where instances are running (same node, same rack) when performing the Iperf benchmarking? I ask it because I think it's important to know when evaluating the internal<>internal IP link, if this link is virtual-only (i.e. both instances in the same node) or not.

Thank you in advance.

**Comment by voellm** [comment]
This data is published in the json results.  Are you looking for it
someplace else?

**Comment by crbertoldo** [comment]
In fact I didn't see it. Please, where can I find out this result? I just run for GCP.

Thanks in advance.

**Comment by cmccoy** [comment]
We don't expose physical node / rack information to my knowledge. The most
granular placement information is zone.

**Comment by crbertoldo** [comment]
Understood, thanks a lot. Perhaps it would be useful to know what is under the hood (i.e. node/rack) when performing tests like Iperf, but I don't know if such kind of granularity is possible.

**Comment by voellm** [comment]
You are right Connor we only expose zone, I missed the ask about rack info.
Zone is as fine as the reporting gets.  There are features in GCE like
instance groups that declare VMs work together, but that also does not
expose rack placement.
