### ISSUE TITLE
Error with df command in fio benchmark

### ISSUE THREAD

**Issue by akrzos** [GoogleCloudPlatform/PerfKitBenchmarker#159]
Running against a static vm that is using device mapper, df can indent the output it provides which leads to an error attempting to run the fio benchmark:

```
# df -k
Filesystem           1K-blocks    Used Available Use% Mounted on
/dev/mapper/vg_dhcp23108-lv_root
                      51475068 2121292  46732336   5% /
tmpfs                  1960452       0   1960452   0% /dev/shm
/dev/vda1               487652   33396    428656   8% /boot
/dev/mapper/vg_dhcp23108-lv_scratch0
                      46967160   53116  44521572   1% /scratch0
```

This output breaks [vm.GetDeviceSizeFromPath(vm.GetScratchDir())] (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/5de105ba9a9edd536603f831ac1d9d175f386c02/perfkitbenchmarker/benchmarks/fio_benchmark.py#L65) in the fio benchmark.

This might only affect the version of df on this vm which is 8.4.

**Comment by cmccoy** [comment]
Closed by #160.
