### ISSUE TITLE
Example run on Azure

### ISSUE THREAD

**Issue by zledwon** [GoogleCloudPlatform/PerfKitBenchmarker#1605]
`$ ./pkb.py --cloud=Azure --machine_type=ExtraSmall --benchmarks=iperf`

running default example ends up with error:
"The requested VM size ExtraSmall is not available in the current region."

changing "ExtraSmall" to "Standard_A0" fixes the problem

**Comment by yuyantingzero** [comment]
Hi @zledwon , PerkitBenchmarker uses cli to interact with cloud providers. In this case, [az](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest).
You can run following command to find out name for the sizes:
az vm list-sizes -l <region>, e.g. az vm list-sizes -l east-us

Let me know if you need help

**Comment by dlott** [comment]
Thanks for point this out @zledwon here's a fix: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1609
