### ISSUE TITLE
Benchmarks fail due to AttributeError: run_with_pdb

### ISSUE THREAD

**Issue by lgajowy** [GoogleCloudPlatform/PerfKitBenchmarker#1621]
This started happening recently, most probably due this commit: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/90064bbb3a693cf625193c974428fa16c5f9a0a0 

Example stacktrace can be found here: https://builds.apache.org/view/A-D/view/Beam/job/beam_PerformanceTests_TextIOIT/342/console

**Comment by dlott** [comment]
Thanks for the report.  Fixed in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1622/commits/acea9babe2d2f0b3886e44264548a914337e55a3

**Comment by dlott** [comment]
Merged in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1622
