### ISSUE TITLE
RemoteCommandError: Got non-zero return code (255) executing hostname

### ISSUE THREAD

**Issue by ayamResearch** [GoogleCloudPlatform/PerfKitBenchmarker#1650]
Hello,

I am trying to run iperf, ping or coremark on google cloud platform using perfkit benchmarker using the command:

./pkb.py --project=testgcp --benchmarks=ping --machine_type=f1-micro --cloud=GCP

That generates an error:

RemoteCommandError: Got non-zero return code (255) executing hostname
Full command: ssh -A -p 22 perfkit@35.184.156.76 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/a73239e4/perfkitbenchmarker_keyfile hostname
STDOUT: STDERR: ssh: connect to host 35.184.156.76 port 22: Connection timed out

Appreciate your help.

**Comment by yuyantingzero** [comment]
Hi, this particular error "connection timed out caused by executing hostname" is a transient error during VM booting caused by PerfkitBenchmarker trying to ssh into VMs, which should go away eventually (when VMs are sshable).
If the error persists, please also post full logs:/tmp/perfkitbenchmarker/runs/a73239e4/pkb.log

**Comment by ayamResearch** [comment]
Thank you for your response. I ran the experiment again and I have attached the most recent pkb.log file for your reference.

[pkb.log](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/1933054/pkb.log)

**Comment by ayamResearch** [comment]
I have resolved the issue. Thanks anyways
