### ISSUE TITLE
PerfKitBenchmarker uses Ubuntu 14.04 HVM AMI on AWS, which doesn't support ENA

### ISSUE THREAD

**Issue by lyoungblood** [GoogleCloudPlatform/PerfKitBenchmarker#1673]
### Problem Statement

PerfKitBenchmarker defaults to using Ubuntu 14.04 HVM machine images, which don't support the Elastic Networking Adapter on AWS.

### Implication

This dramatically limits networking performance, and prevents the usage of newer EC2 instance types such as m5 and c5, which only support the ENA.  In addition, only ENA support 25gbps networking available in the newer instance types.

### Output

```
2018-05-04 01:26:29,247 6047fbe9 Thread-20 object_storage_service(1/1) INFO     Ran aws --output json ec2 run-instances --region=us-east-1 --subnet-id=subnet-0d88f43301770faa9 --associate-public-ip-address --client-token=5a92cc73-50eb-45bc-94ac-13b970b8f650 --image-id=ami-ac0d9eba --instance-type=c5.18xlarge --key-name=perfkit-key-6047fbe9 --placement=GroupName=perfkit-6047fbe9-fe3fff8239ce. Got return code (255).
STDOUT: 
STDERR: 
An error occurred (InvalidParameterCombination) when calling the RunInstances operation: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'c5.18xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA.
```

**Comment by dlott** [comment]
Please reopen if you have further issues.

**Comment by lyoungblood** [comment]
Thanks - this helps!

**Comment by lyoungblood** [comment]
Just tried this now and it didn't work:

```
$ ./pkb.py --benchmarks object_storage_service --cloud AWS --os_type ubuntu1604 --machine_type=c5.18xlarge --region=us-west-2
ERROR    flag --os_type=ubuntu1604: value should be one of <debian|juju|rhel|ubuntu_container|windows>
INFO     For usage instructions, use --helpmatch={module_name}
INFO     For example, ./pkb.py --helpmatch=benchmarks.fio
```

**Comment by s-deitz** [comment]
The --os_type flag has been greatly expanded since the last release. Try running from head instead.

To use the last release, you'd have to manually find an image on AWS (and the image name would differ from zone to zone). Since the last release, PKB will find an image given an expanded definition of OS type which now includes ubuntu1604.

Note that we're close to changing the OS default, but we haven't updated the code yet.

**Comment by HarpPDX** [comment]
According to this query, the Ubuntu 14.04 image listed in the AWS console supports ENA. Is this not the image being picked up by PKB?
$ aws ec2 describe-images --region=us-west-2 --image-id=ami-c59ce2bd --query 'Images[].EnaSupport'
[
    true
]
