### ISSUE TITLE
ycsb_reload_database ycsb flag not working correctly

### ISSUE THREAD

**Issue by flint-dominic** [GoogleCloudPlatform/PerfKitBenchmarker#1686]
setting the '--ycsb_reload_database' to False will still have a load phase.  changing the 'self.loaded' variable to 'True' fixes this.

**Comment by tohaowu** [comment]
Yes, in ycsb.py:951 "if FLAGS.ycsb_reload_database or not self.loaded;"
Should we change the behavior?

**Comment by flint-dominic** [comment]
ah, I see this is primarily for using the same uri or multiple runs in the same uri when this variable is passed on, not for seperate runs with different uri's.

**Comment by flint-dominic** [comment]
I'll close this, as it was not what I thought the flag was used for, I'll just use the work around.
