### ISSUE TITLE
Proposal: Use Corrected YCSB for Coordinated-Omission Problem

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#169]
As you might be aware, the coordinated-omission problem (unintentionally) can cause biased samples, which can skew your results to be better than what's actually are.

Here's a short description taken from [Nitsan Wakart's blog](http://psy-lob-saw.blogspot.com/2015/03/fixing-ycsb-coordinated-omission.html):

<blockquote>
This issue manifests in many load generating frameworks where the call into the system under test is done synchronously and the measurement thread holds up the next sample while the call is ongoing. This enables the system under test to delay requests that would have been made during the synchronous call thus skewing the sample set
</blockquote>

This has been "cautioned" before by the research community, this is essentially the problem of Open vs Closed  system models as described by this [CMU's paper](http://repository.cmu.edu/cgi/viewcontent.cgi?article=1872&context=compsci)

The same author of the blog shared above has posted a solution for this problem, and a [great detailed post](http://psy-lob-saw.blogspot.com/2015/03/fixing-ycsb-coordinated-omission.html) explaining how it was solved.

The corrected YCSB version is here:
https://github.com/LatencyUtils/YCSB2

How should we approach the update to this benchmark? This is essentially a different workload, even the author renamed it to YCSB2, should this be treated as its own benchmark, or similar to the UnixBench, should we use flags to use the different versions?

More info on Coordinated-Omission:
[How NOT to measure latency](http://www.infoq.com/presentations/latency-pitfalls)
[Mechanical Sympathy's Discussion](https://groups.google.com/forum/#!msg/mechanical-sympathy/icNZJejUHfE/BfDekfBEs_sJ)

**Comment by voellm** [comment]
We should get Connor to comment on this one...

**Comment by meteorfox** [comment]
@voellm During the community meeting, you mentioned there's a Googler maintaining YCSB, I was wondering if we should be looking at the efforts started by others in this [repo](https://github.com/YCSB/YCSB), and if it should be evaluated to be included as the default YCSB in PKB. That repo includes the fixes I mentioned on the comments above plus others improvements by other contributors.

**Comment by voellm** [comment]
+Connor to followup.

On Wed, May 20, 2015 at 9:49 AM, Carlos Torres <notifications@github.com>
wrote:

> @voellm <https://github.com/voellm> During the community meeting, you
> mentioned there's a Googler maintaining YCSB, I was wondering if we should
> be looking at the efforts started by others in this repo
> <https://github.com/YCSB/YCSB>, and if it should be evaluated to be
> included as the default YCSB in PKB. That repo includes the fixes I
> mentioned on the comments above plus others improvements by other
> contributors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/169#issuecomment-103956374>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by cmccoy** [comment]
@meteorfox: Getting an updated YCSB sounds great to me. I'm interested in adding YCSB workloads for the NoSQL databases currently in YCSB, and some (e.g. Aerospike) weren't merged into the canonical repo.

The original YCSB repo has gotten some new contributions recently as well from Cloudera though - I'm not sure how we should decide which one to use (or alternatively make the repo configurable via a flag). Do you know if there are any plans to merge?

**Comment by meteorfox** [comment]
@cmccoy According to this pull request the intention is to merge this new changes to the canonical YCSB repo, https://github.com/brianfrankcooper/YCSB/pull/214

Probably, we should wait to see what happens with that pull-request.

**Comment by cmccoy** [comment]
Sounds good to me.

**Comment by cmccoy** [comment]
This will be in the next YCSB release, which we can then pull in.
The present YCSB benchmarks don't set a target rate (simulating a closed system), so they don't have a coordinated omission problem.  `-target` can be set as an option, however.

**Comment by voellm** [comment]
@cmccoy - Is this fixed?  If not please reopen.

**Comment by cmccoy** [comment]
Though not configured by default, the YCSB tests can run with a set target QPS and latencies including queueing time.

I haven't modified the benchmark to use this by default because there would be some work required to combine results across client VMs, which I don't think I'll have time to do anytime soon.
