### ISSUE TITLE
--helpmatch=~module~ does not print all flags for ~module~

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1707]
I noticed that flags of type integerlist are not printed by the --helpmatch option.

E.g.,
r$ ./pkb.py --helpmatch=cuda_toolkit

perfkitbenchmarker.linux_packages.cuda_toolkit:
  --cuda_toolkit_installation_dir: installation directory to use for CUDA
    toolkit. If the toolkit is not installed, it will be installed here. If it
    is already installed, the installation at this path will be used.
    (default: '/usr/local/cuda')
  --cuda_toolkit_version: <8.0|9.0>: Version of CUDA Toolkit to install
    (default: '9.0')
  --[no]gpu_autoboost_enabled: whether gpu autoboost is enabled

Note missing (as seen in cuda_toolkit.py) "gpu_clock_speeds", which is an integer list.

**Comment by yuyantingzero** [comment]
IntegerList is not a vanilla flag provided by absl module. It is defined in perfkitbenchmarker.
