### ISSUE TITLE
mongodb configuration for static machine

### ISSUE THREAD

**Issue by ayamResearch** [GoogleCloudPlatform/PerfKitBenchmarker#1716]
I can change the configuration for mongodb_ycsb workload using
mongodb_ycsb:
  description: Run YCSB against a single MongoDB node.
  vm_groups:
    workers:
      vm_spec: *default_single_core
      disk_spec: *default_500_gb
      vm_count: 1
    clients:
      vm_spec: *default_single_core
"""
However, I would like to run the mongodb on static machine. Can you please explain how to configure mongodb_ycsb.config file to run it on a static machine?

my mongodb_ycsb.yaml is
static_vms:
 - &vm0
    ip_address: *.*.*.*
    user_name: xyz
    ssh_private_key: id_rsa
    internal_ip: *.*.*.*

 - &vm1
    ip_address: *.*.*.*
    user_name: xyz
    ssh_private_key: id_rsa
    internal_ip: *.*.*.*

mongodb_ycsb:
  vm_groups:
    vm_1:
      static_vms:
        - *vm0
    vm_2:
      static_vms:
        - *vm1

How can I specify disk_specs as static machine disk specs?

**Comment by ehankland** [comment]
You should be able to add the disks to each of the static vm configs:
```
vm1: &vm1
  ip_address: ... 
  user_name: xyz
  ssh_private_key: id_rsa
  internal_ip: ...
  disk_specs:
    - mount_point: /scratch
```
Another note - it looks like the VM groups for the mongodb ycsb benchmark are "workers" and "clients" not vm_1 and vm_2 so you'll need to update that too.
