### ISSUE TITLE
fio test 

### ISSUE THREAD

**Issue by liyjperfkit** [GoogleCloudPlatform/PerfKitBenchmarker#172]
i want to know how to define the parameters because thc client‘s io  value is not obvious when perform ./pkb.py --benchmarks=fio  --static_vm_file=test.json  --ip_addresses=EXTERNAL

**Comment by voellm** [comment]
Can you be more specific on what you are not finding?

fio takes a config file with a set of defined benchmarks today.  We are
going to improve the coverage soon.  More queue depth, threads, and sizes
covered.

To change what is run by fio you have to edit the config file.

**Comment by liyjperfkit** [comment]
the  config file?  is it the fio.job?  following 
[global]
filesize=100*100*1000*$mb_memory
filename=fio_test_file
directory=/scratch0
ioengine=libaio

[sequential_write]
overwrite=0
rw=write
blocksize=10M
size=1000*1000*1000*$mb_memory
iodepth=64
direct=1
end_fsync=1

[sequential_read]
stonewall
invalidate=1
overwrite=0
rw=read
blocksize=512k
size=10*10*1000*$mb_memory
iodepth=64
direct=1

[random_write_test]
stonewall
overwrite=1
rw=randwrite
blocksize=4k
iodepth=1
size=10*1000*$mb_memory
direct=1

[random_read_test]
invalidate=1
stonewall
rw=randread
blocksize=4k
iodepth=1
size=10*1000*$mb_memory
direct=1

[random_read_test_parallel]
invalidate=1
stonewall
rw=randread
blocksize=4k
iodepth=64
size=10*1000*$mb_memory
direct=1

**Comment by cmccoy** [comment]
Exactly.

**Comment by yuyantingzero** [comment]
I am currently working on block_storage_benchmark, which also uses fio binary. 
Current fio_benchmark uses job file and block_storage_benchmark uses pure command line. I am thinking about unifying these 2 benchmarks, either both use job file, which seems to be standard way from documentation, or both use command line, which gives better control on the parameters and more straight forward.

**Comment by liyjperfkit** [comment]
i want to resize the "filesize=1001001000*$mb_memory",please tell me what means the variable"$mb_memory",if i can resisz to "filesize= 1000  1000 10000". my destination is see the results of fio test is obvious

**Comment by noahl** [comment]
`$mb_memory' in a fio job file means the amount of memory on the machine running fio. You cannot do `filesize = 1000 1000 10000', but you can do `filesize = 1000 * 1000 * 10000'. For more information on fio job files, please see https://github.com/axboe/fio/blob/master/HOWTO

Beyond that, it's not clear to me what the bug is here. What enhancements are being asked for? Have we implemented them in the last 5 months?

**Comment by voellm** [comment]
There have been a number of improvements around fio which I believe address this.  If not please reopen.
