### ISSUE TITLE
How to use different version of mongoDB 

### ISSUE THREAD

**Issue by ayamResearch** [GoogleCloudPlatform/PerfKitBenchmarker#1726]
Hi
I believe my default PKB install mongoDB version 2.6. I would like to install a different version on ubuntu operating system.

To do so I edit the mongodb_server.py as follows:
  vm.RemoteCommand('sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5')
 vm.RemoteCommand('echo "deb [ arch=amd64,arm64,ppc64el,s390x ] http://repo.mongodb.com/apt/ubuntu xenial/mongodb-enterprise/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list')
 vm.RemoteCommand('sudo apt-get update')
vm.RemoteCommand('sudo apt-get install --reinstall mongodb-enterprise')

However, I get error: "error: unit mongodb.service is masked when staring mongodb".
To solve this issue: I add following lines in the file
 vm.RemoteCommand('sudo systemctl unmask mongodb')
 vm.RemoteCommand('sudo systemctl enable mongodb')

It solved the error regarding mask but then it get stuck while running command:
/tmp/pkb/wait_for_command.py --status /tmp/pkb/cmdec36b858-e101-438c-bdde-c33995e35589.status in VM0 finish stage.

Appreciate any ideas to solve this issue.

**Comment by jellyfishcake** [comment]
I'd suggest trying out the commands from the official mongo site as well: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/. Otherwise, you can try using tarballs.

**Comment by ayamResearch** [comment]
Thanks for your response.
I figure the halt is because of error mentioned below:

YCSB Client 0.9.0
Command line: -db com.yahoo.ycsb.db.MongoDbClient -P workloads/workloadc -p recordcount=10000 -p operationcount=200 -p mongodb.url=mongodb://ip:port/ -t
Loading workload...
Starting test.
mongo client connection created with mongodb://ip:port/
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=ip:port, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
