### ISSUE TITLE
Request - Add support for Rackspace Cloud

### ISSUE THREAD

**Issue by smolinari** [GoogleCloudPlatform/PerfKitBenchmarker#173]
Hi,

Simple request. I'd like to see these tools also be usable on Rackspace's cloud computing infrastructure. Thanks!

Scott

**Comment by voellm** [comment]
Goods news... Carlos (cced) from Rackspace is a big contributor.  He can
likely get you started today with the static machine config we support.

That said I'd like to see Rackspace as one of the default clouds so all you
have to do is --cloud=Rackspace

Not sure of the timeline on that.

**Comment by smolinari** [comment]
Yes, the "--cloud=Rackspace" is the kind of support I'd like to see too. And I am almost certain RS would want to have it too.;)

Scott

**Comment by voellm** [comment]
Assigning to Carlos to eval.

**Comment by meteorfox** [comment]
Communicated this to the right channels internally at Rackspace. Developer Relations team at Rackspace will take a look into this for their next sprint.

**Comment by jrperritt** [comment]
So as to not keep everyone in the dark, this is currently being developed (by me).

**Comment by meteorfox** [comment]
@jrperritt Awesome thanks for taking on this task.

**Comment by voellm** [comment]
Nice!  Thank you.  Any planned ETA?

On Wed, Apr 15, 2015 at 10:19 AM, jrperritt <notifications@github.com>
wrote:

> So as to not keep everyone in the dark, this is currently being developed
> (by me).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/173#issuecomment-93491315>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by smolinari** [comment]
>So as to not keep everyone in the dark, this is currently being developed (by me).

:+1:

**Comment by jrperritt** [comment]
@voellm Not really, but it would go a lot faster if there was a guide for adding cloud providers. Does such a thing exist?

**Comment by voellm** [comment]
We dont have a guide by you are welcome to ping ehankland@google.com  for
help.

On Wed, Apr 15, 2015 at 12:56 PM, jrperritt <notifications@github.com>
wrote:

> @voellm <https://github.com/voellm> Not really, but it would go a lot
> faster if there was a guide for adding cloud providers. Does such a thing
> exist?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/173#issuecomment-93548966>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by klausw** [comment]
Closing, #336 is merged and appears on track to be included in the upcoming 0.18.0 release.

FYI re @voellm's earlier comment, we've started on documentation for adding cloud providers in the Wiki - let me know if you have feedback:

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/Adding-a-new-cloud-provider

**Comment by meteorfox** [comment]
Awesome, thanks for merging this! 

@klausw I'll go over the wiki, and leave my feedback. Thanks
