### ISSUE TITLE
Where can we ask questions or discuss the results of some of these benchmarks ?

### ISSUE THREAD

**Issue by desaiak** [GoogleCloudPlatform/PerfKitBenchmarker#174]
@voellm I have run a lot of these and would like to discuss some of the results, where is the right platform to do that?

Thanks!

**Comment by voellm** [comment]
I like covering the questions in the issues because it keeps things
together and essay for everyone to find.

You can also use perfkitconnect@googlegroups.com or email me directly.

Thanks... fire away.

**Comment by voellm** [comment]
I should mention if you sign up for GitHub email notifications issues go to
your inbox so they work via email.  That's what I do.
