### ISSUE TITLE
How to use "Named configs"

### ISSUE THREAD

**Issue by ayamResearch** [GoogleCloudPlatform/PerfKitBenchmarker#1745]
Named configs allow multiple configs for the same benchmark to be present within the same config file.
The example mentioned in the document is 
cluster_boot.yaml ...
cluster_boot_5:
  name: cluster_boot
  vm_groups:
    default:
      vm_count: 5
cluster_boot_10:
  name: cluster_boot
  vm_groups:
    default:
      vm_count: 10

How should I specify on the command line to run cluster_boot_10 config settings?
./pkb.py --benchmark_config_file=cluster_boot.yaml  ????

**Comment by jellyfishcake** [comment]
blaze-bin/cloud/performance/artemis/artemis --benchmarks=cluster_boot_5 --cloud=...  --benchmark_config_file=cluster_boot.yml
Not sure where you got your example from. Format looks wrong to me.

**Comment by ayamResearch** [comment]
Thanks, It works
