### ISSUE TITLE
Anyone else notice inconsistent iperf results for GCP

### ISSUE THREAD

**Issue by desaiak** [GoogleCloudPlatform/PerfKitBenchmarker#175]
Consistently when I run iperf on GCP I get 2 low and 2 high throughput numbers, whereas they seem to be consistent for both Azure and AWS. Trying to understand why.

Command: ./pkb.py --cloud=GCP --benchmarks=iperf --machine_type=n1-standard-4

Azure - D3
Throughput 1594.0 Mbits/sec
Throughput 1531.0 Mbits/sec
Throughput 1697.0 Mbits/sec
Throughput 1668.0 Mbits/sec

AWS - m3-xlarge
Throughput 950.0 Mbits/sec
Throughput 1004.0 Mbits/sec
Throughput 950.0 Mbits/sec
Throughput 1004.0 Mbits/sec

Google -n1-standard-4
Throughput 634.0 Mbits/sec
Throughput 5916.0 Mbits/sec
Throughput 533.0 Mbits/sec
Throughput 6147.0 Mbits/sec

**Comment by voellm** [comment]
Ahh.... we have a bug open to clarify the results though the details are in
the json. You are seeing results for internal and external IPs and both
directions.

External are the middle and bottom... the lower numbers.  Internal are the
~6Gbps numbers.

We recommend using internal IPs for all VMs that work together.

**Comment by voellm** [comment]
We should have this fixed in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/178

It will get picked up in master in with the next release from dev.

ok to close this?

**Comment by desaiak** [comment]
Yes

**Comment by hungvelo** [comment]
So, using the example above, we should disregard the first and third throughputs and use only the second and last numbers (5916.0 and 6147.0 Mbits/sec) for GCP? Please let me know. Thank you.

**Comment by cmccoy** [comment]
@hungvelo: If you're only interested in internal (within cloud) networking, then yes. Better would be look at the JSON output (which specifies whether the IP was internal or external) for your results.  Once #178 is merged, that information will be printed by default.
