### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by nehajkps** [GoogleCloudPlatform/PerfKitBenchmarker#1797]
I'm following the setup for AWS as it mentions here: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker#install-aws-cli-and-setup-authentication  and when I try to run a single benchmark, i.e these commands: 
$ cd PerfKitBenchmarker
$ ./pkb.py --cloud=AWS --benchmarks=iperf --machine_type=t2.micro
I get the following error: **-bash: ./pkb.py: Permission denied**
I looked online pretty much everywhere, but couldn't find any solution to this. What I noticed was that when I try to **./**"any python file in the folder", it always throws a permission denied error. 

Any help would be much appreciated.

**Comment by yuyantingzero** [comment]
Have you tried running  "sudo chmod 777 pkb.py"

**Comment by s-deitz** [comment]
Since pkb.py should be executable, I'm going to close this. Reopen if you continue to have issues.
