### ISSUE TITLE
Collect and publish data on machine load during benchmark runs

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#180]
e.g., with `dstat`.

cc: @meteorfox

**Comment by meteorfox** [comment]
Other possible tools to collect system utilization data with time range addressing capabilities:

[sysstat package (sar)](http://sebastien.godard.pagesperso-orange.fr/)
[Performance Co-Pilot (pcp)](http://www.pcp.io/)

With time range addressing you can zoom in to particular time intervals, or time spans instead of relying on when the tool was started and stopped.

**Comment by hungvelo** [comment]
It's good and useful to collect system utilization data during benchmark runs but be careful as this may effect performance results for some benchmarks that are latency sensitive. What's about the host itself? Maybe not but is it possible to find out the host system configuration (OS version, CPU, memory, I/O storage, Network, etc.)? :-)?

**Comment by cmccoy** [comment]
Host configuration is being tracked in #183.

**Comment by cmccoy** [comment]
I added dstat (because it's simple to run and parse) in #282. Does that seem reasonable as a first step? PCP and sar sound great too, but I'm not as familiar. #282 includes the unix epoch for each sample, so filtering to time windows of interest is possible.

**Comment by cmccoy** [comment]
Comment by @meteorfox on #282, which sounds like a great idea to me:

>A nother suggestion. It'd be great if we could collect error metrics too (I'm not entirely sure if dstat already does). I'm looking for metrics like dropped packets, TCP re-transmissions and timeouts, storage IO errors, etc. 
This follows the USE method methodology, which monitors utilization, saturation, and error metrics for each main component in a system, and serves as checklist to quickly identify bottlenecks.

> Here's more info: http://www.brendangregg.com/USEmethod/use-linux.html

This won't be addressed by #282, as `dstat` doesn't seem to collect error metrics in the list above.

**Comment by cmccoy** [comment]
The collectd support added in #398 includes TCP errors, but not everything from the USE method @meteorfox mentioned above.

I'm going to close this - if there are specific additional metrics we should be collecting, let's open separate issues for them.
