### ISSUE TITLE
ycsb version >= 0.11.0 does not work w/ YUM package manager

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1823]
Installation of HDR Histogram when ycsb version >= 0.11.0 forces use of APT package manager: 

  if _GetVersionIndex(FLAGS.ycsb_version) >= 11:
    vm.RemoteCommand(install_cmd.format(HDRHISTOGRAM_DIR, HDRHISTOGRAM_TAR_URL))
    vm.RemoteCommand('sudo **apt-get** --assume-yes install maven > /dev/null 2>&1')

Unfortunately, fix is not as straight forward as vm.InstallPackages('maven'). It seems there isn't a package in the RHEL repo.

**Comment by yuyantingzero** [comment]
What is the OS you are using.
Some quick search gives:

sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
sudo yum install -y apache-maven
mvn --version

If above command works on your system, we can add maven package into PerfkitBenchmarker.

**Comment by HarpPDX** [comment]
I agree adding a maven package, with proper installation steps for RHEL, will solve the problem.

**Comment by prabha101** [comment]
i ran into this issue as well on CentOS where it hits these code lines in ycsb.py under def _Install(vm):

if _GetVersionIndex(FLAGS.ycsb_version) >= 11:
    vm.RemoteCommand(install_cmd.format(HDRHISTOGRAM_DIR, HDRHISTOGRAM_TAR_URL))
    vm.RemoteCommand('sudo apt-get --assume-yes install maven > /dev/null 2>&1')

I manually did a yum install of maven and commented out "vm.RemoteCommand('sudo apt-get --assume-yes install maven > /dev/null 2>&1')" and it seemed to work for me. Is the above fix in yet for OS agnostic maven pre-installation. Then this line can be removed from the codebase.

[root@mlb03 ~]# mvn -version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.7.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.201-2.6.16.1.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.el7.x86_64", arch: "amd64", family: "unix"

**Comment by prabha101** [comment]
> What is the OS you are using.
> Some quick search gives:
> 
> sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
> sudo sed -i s/$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
> sudo yum install -y apache-maven
> mvn --version
> 
> If above command works on your system, we can add maven package into PerfkitBenchmarker.

i tried this on a system and it goes through just fine.

[root@mlb03 ~]# sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven                                       /epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
--2019-01-30 09:33:34--  http://repos.fedorapeople.org/repos/dchen/apache-maven/                                       epel-apache-maven.repo
Resolving repos.fedorapeople.org (repos.fedorapeople.org)... 152.19.134.199, 261                                       0:28:3090:3001:5054:ff:fea7:9474
Connecting to repos.fedorapeople.org (repos.fedorapeople.org)|152.19.134.199|:80                                       ... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-ma                                       ven.repo [following]
--2019-01-30 09:33:34--  https://repos.fedorapeople.org/repos/dchen/apache-maven                                       /epel-apache-maven.repo
Connecting to repos.fedorapeople.org (repos.fedorapeople.org)|152.19.134.199|:44                                       3... connected.
HTTP request sent, awaiting response... 200 OK
Length: 445
Saving to: ‘/etc/yum.repos.d/epel-apache-maven.repo’

100%[======================================>] 445         --.-K/s   in 0s

2019-01-30 09:33:35 (17.0 MB/s) - ‘/etc/yum.repos.d/epel-apache-maven.repo’ save                                       d [445/445]

[root@mlb03 ~]# sudo sed -i s/$releasever/6/g /etc/yum.repos.d/epel-apache-maven                                       .repo
sed: -e expression #1, char 0: no previous regular expression
[root@mlb03 ~]# sudo yum install -y apache-maven
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.rcs.alaska.edu
 * epel: mirror.csclub.uwaterloo.ca
 * extras: mirror.cogentco.com
 * updates: mirror.cs.vt.edu
epel-apache-maven                                        | 3.3 kB     00:00
epel-apache-maven/7/x86_64/primary_db                      | 7.7 kB   00:00
Resolving Dependencies
--> Running transaction check
---> Package apache-maven.noarch 0:3.5.2-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch        Version             Repository              Size
================================================================================
Installing:
 apache-maven      noarch      3.5.2-1.el7         epel-apache-maven      8.0 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 8.0 M
Installed size: 9.6 M
Downloading packages:
apache-maven-3.5.2-1.el7.noarch.rpm                        | 8.0 MB   00:04
Running transaction check
Running transaction test


Transaction check error:
  file /usr/share/java/plexus/plexus-cipher.jar from install of apache-maven-0:3                                       .5.2-1.el7.noarch conflicts with file from package plexus-cipher-1.7-5.el7.noarc                                       h
  file /usr/share/java/plexus/plexus-sec-dispatcher.jar from install of apache-m                                       aven-0:3.5.2-1.el7.noarch conflicts with file from package plexus-sec-dispatcher                                       -1.4-13.el7.noarch
  file /usr/share/java/maven-wagon/file.jar from install of apache-maven-0:3.5.2                                       -1.el7.noarch conflicts with file from package maven-wagon-0:2.4-3.el7.noarch
  file /usr/share/java/maven-wagon/provider-api.jar from install of apache-maven                                       -0:3.5.2-1.el7.noarch conflicts with file from package maven-wagon-0:2.4-3.el7.n                                       oarch
  file /etc/m2.conf from install of apache-maven-0:3.5.2-1.el7.noarch conflicts                                        with file from package maven-3.0.5-17.el7.noarch
  file /etc/maven/settings.xml from install of apache-maven-0:3.5.2-1.el7.noarch                                        conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/bin/mvn from install of apache-maven-0:3.5.2-1.el7.noarch conflicts                                        with file from package maven-3.0.5-17.el7.noarch
  file /usr/bin/mvnDebug from install of apache-maven-0:3.5.2-1.el7.noarch confl                                       icts with file from package maven-3.0.5-17.el7.noarch
  file /usr/bin/mvnyjp from install of apache-maven-0:3.5.2-1.el7.noarch conflic                                       ts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-artifact.jar from install of apache-maven-0:3                                       .5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-compat.jar from install of apache-maven-0:3.5                                       .2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-core.jar from install of apache-maven-0:3.5.2                                       -1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-embedder.jar from install of apache-maven-0:3                                       .5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-model-builder.jar from install of apache-mave                                       n-0:3.5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarc                                       h
  file /usr/share/java/maven/maven-model.jar from install of apache-maven-0:3.5.                                       2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-plugin-api.jar from install of apache-maven-0                                       :3.5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch
  file /usr/share/java/maven/maven-repository-metadata.jar from install of apach                                       e-maven-0:3.5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7                                       .noarch
  file /usr/share/java/maven/maven-settings-builder.jar from install of apache-m                                       aven-0:3.5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.no                                       arch
  file /usr/share/java/maven/maven-settings.jar from install of apache-maven-0:3                                       .5.2-1.el7.noarch conflicts with file from package maven-3.0.5-17.el7.noarch

Error Summary
-------------

[root@mlb03 ~]# mvn --version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.7.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.201-2.6.16.1.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.el7.x86_64", arch: "amd64", family: "unix"
