### ISSUE TITLE
YCSB 'load' phase not respecting ycsb_field_count/length flags

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1857]
Attempted to override the default field count and field size using --ycsb_field_count=8 --ycsb_field_length=8.  These values are not present in the the ycsb load command, but are present in the ycsb run command.

LOAD CMD:
'cd /opt/pkb/ycsb; /opt/pkb/ycsb/bin/ycsb load mongodb -cp /opt/pkb/ycsb -threads 16 -P /opt/pkb/workloadc -p measurementtype=histogram -p recordcount=10000000 -p mongodb.url=mongodb://10.0.0.159:27020 -p insertcount=2500000 -p measurement.interval=op -p insertstart=7500000'

RUN CMD:
'cd /opt/pkb/ycsb; /opt/pkb/ycsb/bin/ycsb run mongodb -cp /opt/pkb/ycsb -threads 32 -P /opt/pkb/workloadc -p measurementtype=histogram -p duplicate_count=4 -p recordcount=2500000 -p **fieldcount**=8 -p mongodb.url=mongodb://10.0.0.159:27017 -p operationcount=10000000 -p duplicate_index=0 -p maxexecutiontime=1800 -p insertstart=0 -p measurement.interval=op -p **fieldlength**=8'

**Comment by jellyfishcake** [comment]
Fixed in pull request 1861.

**Comment by HarpPDX** [comment]
Looks good...thanks.
