### ISSUE TITLE
percent_expand: unknown key %C

### ISSUE THREAD

**Issue by mjz-smu** [GoogleCloudPlatform/PerfKitBenchmarker#1858]
ssh appends the literal '%C' on Ubuntu 14 (possibly other OS) eg from pkb.log: ...ssh flags
```-2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes
 -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/1160bba4/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/1160bba4/ssh/%C" -o ControlMaster=auto -o ControlPersist=10m hostname}  ReturnCode:255
STDOUT: 
STDERR: percent_expand: unknown key %C
```
relevant commit (198: control_path = os.path.join(temp_dir.GetSshConnectionsDir(), '%C')): https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/b15bf30494c8621929c1677914a125da905e36c5#diff-6c0dd34a0f7b6f2f2e0668bfbe15a263

tested on:
 ```
uname -a:
Linux i-2019021411-a5f6c2c1 4.4.0-142-generic #168~14.04.1-Ubuntu SMP Sat Jan 19 11:26:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ehankland** [comment]
This means you've got an older version of openssh (https://unix.stackexchange.com/questions/218272/how-can-i-maintain-open-ssh-connection-and-use-it-from-shell-scripts indicates %C was introduced in v6.7). If you don't want to upgrade you can turn off the PKB feature by passing in the flag --reuse_ssh_connections=False
