### ISSUE TITLE
Azure cloud error: Allocation failed - condition is too restrictive

### ISSUE THREAD

**Issue by ayamResearch** [GoogleCloudPlatform/PerfKitBenchmarker#1863]
I am trying to run MongoDB with YCSB on Ubuntu 18.04 with the instance "Standard_L32s" and "Standards_F72s_v2" in zone eastus2. PKB shows error: **"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - VM Size"**

Error message from log file:
-------------------------------------
az vm create --location eastus2 --image Canonical:UbuntuServer:18.04-LTS:latest --size Standard_L32s --admin-username perfkit --availability-set pkbdc85a005-mongodb_ycsb0-eastus2 --storage-sku Standard_LRS --name pkb-dc85a005-1 --resource-group pkbdc85a005-mongodb_ycsb0 --nics pkb-dc85a005-1-nic --ssh-key-value /tmp/perfkitbenchmarker/runs/dc85a005/perfkitbenchmarker_keyfile.pub}  ReturnCode:1
STDOUT:
STDERR: ERROR: Deployment failed. Correlation ID: 60d9830e-559d-4067-82c2-0fff4568fba5. {^M
  "status": "Failed",^M
  "error": {^M
    "code": "ResourceDeploymentFailure",^M
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",^M
    "details": [^M
      {^M
        "code": "OverconstrainedAllocationRequest",^M
        "message": "Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - VM Size\n"^M
      }^M
    ]^M
  }^M
}

 The configuration file to run workload on Azure
-----------------------------------------------------------------------

server: &server
  Azure:
    machine_type: Standard_L32s
    zone: eastus2
disk: &disk
  Azure:
    disk_type: local
    mount_point: /scratch
client: &client
  Azure:
    machine_type: Standard_F72s_v2
    zone: eastus2
mongodb_ycsb:
  vm_groups:
    workers:
      os_type: ubuntu1804
      vm_spec: *server
      disk_spec: *disk
      vm_count: 1
    clients:
      os_type: ubuntu1804
      vm_spec: *client

**Comment by yuyantingzero** [comment]
This error came from Azure:
https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/error-messages

**Comment by HarpPDX** [comment]
@yuyantingzero The error comes from Azure, but the problem is that the Azure provider in PKB attempts to put all the VMs for a benchmark in the same Azure Availability Set. This doesn't make sense for client-server workloads where the client and server may be different classes of VMs. Removing (commenting-out) the availability set constraint allows the above configuration to succeed on Azure.

**Comment by s-deitz** [comment]
It seems like, by default, we shouldn't add VMs from different groups to the same availability set. I wonder if we have a similar problem with placement groups on AWS.

**Comment by s-deitz** [comment]
@gareth-ferneyhough Any thoughts on whether we would have a simillar problem on AWS if there were different machine types in two different VM groups?

**Comment by gareth-ferneyhough** [comment]
@s-deitz: I don't think PKB should allow different types of VMs in the same VM group at all. In fact, I don't think it will work. I believe the implementation assumes all VMs are identical.

**Comment by HarpPDX** [comment]
We use different types of VMS on AWS for client-server benchmarks, e.g. we may use a bunch of Compute Optimized VMs as clients and a General Purpose VM as the server.

We, obviously, haven't used/tested all combinations. :-)

**Comment by s-deitz** [comment]
@gareth-ferneyhough Not in the same group. What if we had different machine types in different VM groups? Do we currently create separate placement groups for different VM groups on AWS?

**Comment by gareth-ferneyhough** [comment]
No, I just ran a test with three vm_groups (all different machine types) on AWS, and they were all placed in the same placement_group. I agree that they should be separate.
