### ISSUE TITLE
RELEASE: v0.12.0

### ISSUE THREAD

**Issue by stfeng** [GoogleCloudPlatform/PerfKitBenchmarker#187]
Release tracking bug for v0.12.0.

Cut-off time for commits is EOD Monday 3/23.

**Comment by voellm** [comment]
This is the release bug to keep notes on what is happening. 

If you have a feature or bug you want to tag to a future release to indicate when it will land please use the milestone.  For each release we will make sure things tagged for the milestone release and are not checked in get pinged.

**Comment by stfeng** [comment]
Here is the CHANGES.md file for this release:

# v0.12.0

* Add per-phase timestamp samples (GH171)
* Regex improvement (GH182)
* Fix a bug in mesh network benchmarks (GH163)
* Fix for running on AWS when user has a non-JSON output format
  configured(GH167)
* Clarify how to provide scratch disk for static VMs (GH166)
* Add benchmark name, run URI to log messages (GH157)
* Fix fio_benchmark to support static VMs (GH162)
* Optional patch to the unix bench for 16+ core VMs (GH 135)

**Comment by stfeng** [comment]
Release qualification and side-by-side run is in progress, ETA is tomorrow.

**Comment by stfeng** [comment]
This release has been completed.

**Comment by voellm** [comment]
Thanks!  On to the next release.

Perfies - Please start tagging features and bugs you are actively working
on with the targeted milestone label.

On Wed, Mar 25, 2015 at 4:22 PM, stfeng <notifications@github.com> wrote:

> This release has been completed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/187#issuecomment-86250736>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
