### ISSUE TITLE
gce not deleting firewall consistently

### ISSUE THREAD

**Issue by flint-dominic** [GoogleCloudPlatform/PerfKitBenchmarker#1875]
2019-03-26 10:52:15,611 9d4c8142 MainThread cloud_firestore_ycsb(1/1) vm_util.py:315 INFO     Running: gcloud compute firewall-rules describe default-internal-9d4c8142 --format json --quiet --project firestore-benchmark-tests
2019-03-26 10:52:16,197 9d4c8142 MainThread cloud_firestore_ycsb(1/1) vm_util.py:366 DEBUG    Ran: {gcloud compute firewall-rules describe default-internal-9d4c8142 --format json --quiet --project firestore-benchmark-tests}  ReturnCode:1
STDOUT: 
STDERR: ERROR: (gcloud.compute.firewall-rules.describe) Could not fetch resource:
 - The resource 'projects/firestore-benchmark-tests/global/firewalls/default-internal-9d4c8142' was not found

**Comment by jellyfishcake** [comment]
Deleting a resource should have retries such that the resource will keep deleting till it succeeds or timeout after 20min. Did the delete succeed in the end? Or is your concern the error message?

**Comment by flint-dominic** [comment]
it was attempting to delete non-existent firewall rules, and fails, then is prevented from deleting network.  i usually manually delete the firewall rules and it finished successfully.

**Comment by jellyfishcake** [comment]
The benchmark cloud_firestore_ycsb seems to have not been checked in. Can you attach a log file when you run into this issue again?

**Comment by flint-dominic** [comment]
[fd.pkb.log.tar.gz](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/3015771/fd.pkb.log.tar.gz)

**Comment by jellyfishcake** [comment]
It looks like from your logs that the firewall-rules perfkit-firewall-c1a637eb-22-22, default-internal-c1a637eb were created by the benchmark, and then deleted properly, after deletion, you see the 'error' that 
"The resource 'projects/firestore-benchmark-tests/global/firewalls/blabla' was not found". This is all within expectations.

Now the firewall that is causing your network to fail to delete is named 'projects/firestore-benchmark-tests/global/firewalls/pkb-network-c1a637eb-pjf5geul3rfwfyd5mynbasya'. I do not see it getting created anywhere in the logs, the naming convention is also foreign to me. It is unclear to me how it is created. If this is not a pkb creation, then pkb will not be able to delete it.

**Comment by flint-dominic** [comment]
yep, i only have the default VPC network, any starting with pkb are created by pkb, it seems to be something is creating them, but if no one else is reporting on this, somehow related to internal network, i did notice it possibly happening with other peoples internal pkb automated runs on other projects.

**Comment by jellyfishcake** [comment]
I see that you are creating networks in the benchmark, and setting the subnet-mode as auto. I am wondering if you are automatically creating subnets because of that. I would skip the network creation and use a default network to verify if that it the source of the problem.

**Comment by flint-dominic** [comment]
ill give that a shot, thanks!

**Comment by dlott** [comment]
The new  `--gce_firewall_rules_clean_all` should also help this scenario.  
See  https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/3a0159f3eba72523f3aa751fe697fc4ba6d7d62f for details.

Please reopen if you're still having issues.
