### ISSUE TITLE
container_netperf benchmark fails due to change in netperf benchmark

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1881]
The container_netperf benchmark uses the ParseNetperfOutput function from the netperf benchmark.  This commit https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/e0a5c9fdaf11e02259fada129efc5f698a676000 to the netperf benchmark, that adds more metrics, breaks container_netperf because the list of metrics in container_netperf must match those in netperf due to sharing the output parsing function.

**Comment by ehankland** [comment]
Thanks for the report - this should be fixed shortly - I'll close once the fix is merged

**Comment by HarpPDX** [comment]
This was fixed with commit: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/431b8e8ebe2435ab15abc6f2769e964f6d8b223b
Thanks @ehankland .
