### ISSUE TITLE
Cassandra Heap size config

### ISSUE THREAD

**Issue by krishbala** [GoogleCloudPlatform/PerfKitBenchmarker#1896]
Hi,

After setting the heap memory in Cassandra-env.sh/jam.option, I have started the Cassandra as a service but my Cassandra node did not start why?

Also please suggest us where to set the heap size for Cassandra.

Currently, it is taking as 1GB by default.i have to increase it to 1.5GB.

**Comment by yuyantingzero** [comment]
Can you give some background?
what machine size, what did you change in cassandra-env.sh (a diff may be helpful)

If cassandra didn't even start, can you check cassandra logs?

**Comment by dlott** [comment]
Closing as we can't help without further information.  Feel free to reopen if you have more information for  @yuyantingzero questions.
