### ISSUE TITLE
How to add additional tests?

### ISSUE THREAD

**Issue by omps** [GoogleCloudPlatform/PerfKitBenchmarker#1924]
Hi,

Was looking to add some additional tests from my local environment, more of some functional tests, which i couldn't find and these tests would mainly be app specific. I am looking to add some tests for this. Please guide me to the correct document. If there isn't any, i will surely try to help write one.

Something like this

`https://avocado-framework.readthedocs.io/en/52.0/WritingTests.html`

Regards,
Om Ps

**Comment by s-deitz** [comment]
Are you asking about writing unit tests to ensure PKB keeps working with your local environment? There isn't much documentation, but there is some mention at https://github.com/GoogleCloudPlatform/PerfKitBenchmarker#integration-testing.

If you are asking about adding a new benchmark (which is sometimes referred to as a test), there isn't much documentation yet. It would be great to add. I'd recommend following the patterns in an existing benchmark and reading the documentation in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/pkb.py.

**Comment by cwilkes** [comment]
@omps I'm going through old bugs, is there anything more you need from us on this?

Looking at Avocado it looks like you do just do this: https://avocado-framework.readthedocs.io/en/52.0/WrapProcess.html and specify pkb.py as your executable (along with any flags).  Is that enough for you to go on?

**Comment by omps** [comment]
@cwilkes what i meant was to write docs such as the avacoado guys had written for additional tests which could be added in future with perfkit. I do not see any appropriate documentation to add additional tests. I was proposing to add similar page where procedure can be written for adding new tests.  I will go with what @s-deitz has suggested and work on the same lines. I will submit a demo doc in some time.

**Comment by omps** [comment]
> Are you asking about writing unit tests to ensure PKB keeps working with your local environment? There isn't much documentation, but there is some mention at https://github.com/GoogleCloudPlatform/PerfKitBenchmarker#integration-testing.
> 
> If you are asking about adding a new benchmark (which is sometimes referred to as a test), there isn't much documentation yet. It would be great to add. I'd recommend following the patterns in an existing benchmark and reading the documentation in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/pkb.py.

Thanks. I will go through this.
