### ISSUE TITLE
vm.InstallPreprovisionedBenchmarkData fails on GCP with Ubuntu 18.04

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1925]
Gsutil isn't in the path when issuing remote commands via SSH on Ubuntu 18.04 resulting in an error.  Gsutil is installed and in the path when logged in. It appears the GCP SDK is installed via Ubuntu's snap application package on 18.04.  Not sure how snap packages should be added to path for remote ssh (no shell).

Note: works fine with Ubuntu 16.04.

**Comment by s-deitz** [comment]
Thanks for the report. This should now be fixed at head with 
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/1c47a380af51d4d091bce611ee3307f542bd2568.
