### ISSUE TITLE
Cannot specify different machine types for VMs used in a benchmark

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#193]
As a user, I want to be able to specify different machine types for each of the VMs used in a benchmark that requires more than 1 VM. If only a single machine_type is specified, then this machine type will be used for all VMs (current behavior). 

Example:
A benchmark could make use of 2 VMs where one of them acts as a client load generator, and the other as the SUT (e.g. system under test). For example, LinkBench, SysBench OLTP, iperf, or a web server benchmark could be examples of such benchmarks.

Possible CLI ideas:

```shell
pkb.py --cloud=GCP --mapfile=sysbench_oltp_types.json --benchmarks=sysbench_oltp
```

```json
// sysbench_oltp_types.json
{
    "sysbench": { 
        "machine_type": "n1-standard-4",
        "num_vms": 2
    },
    "mysql": {
        "machine_type": "n1-standard-16",
        "num_vms": 1,
        "scratch_disk_type": "ssd"
    }
}
```
The keys like 'sysbench', and 'mysql', could be define by the benchmark. They indicate the 'roles' of the VMs used, which a benchmark could use to retrieve properties that apply to certain  VMs.

While this issue is specifically about multiple machine_types, this kind of configuration opens the possibilities of specifying more granular configurations, as shown above when it is used to specify num_vms and scratch_disk_types.

**Comment by voellm** [comment]
This is part of our much larger flags refactor.  We want to merge
benchmark_spec, configs and flags into something more rationalized.

This work is planned for Q2 and we'll start some brainstorming on Monday.

Lets keep this bug to track it on GitHub.

On Fri, Mar 27, 2015 at 1:57 PM, Carlos Torres <notifications@github.com>
wrote:

> As a user, I want to be able to specify different machine types for each
> of the VMs used in a benchmark that requires more than 1 VM. If only a
> single machine_type is specified, then this machine type will be used for
> all VMs (current behavior).
>
> Example:
> A benchmark could make use of 2 VMs where one of them acts as a client
> load generator, and the other as the SUT (e.g. system under test). For
> example, LinkBench, SysBench OLTP, iperf, or a web server benchmark could
> be examples of such benchmarks.
>
> Possible CLI ideas:
>
> pkb.py --cloud=GCP --mapfile=sysbench_oltp_types.json --benchmarks=sysbench_oltp
>
> // sysbench_oltp_types.json
> {
>     "sysbench": {
>         "machine_type": "n1-standard-4",
>         "num_vms": 2
>     },
>     "mysql": {
>         "machine_type": "n1-standard-16",
>         "num_vms": 1,
>         "scratch_disk_type": "ssd"
>     }
> }
>
> The keys like 'sysbench', and 'mysql', could be define by the benchmark.
> They indicate the 'roles' of the VMs used, which a benchmark could use to
> retrieve properties that apply to certain VMs.
>
> While this issue is specifically about multiple machine_types, this kind
> of configuration opens the possibilities of specifying more granular
> configurations, as shown above when it is used to specify num_vms and
> scratch_disk_types.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/193>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by meteorfox** [comment]
@voellm where is this brainstorming going to take place? 

For those interested to participate in these discussions, I think it'd be a great idea to have a 'real-time' collaboration channel, like an IRC channel, or a Slack channel where the discussions are public. Also, I believe it would be a great place to answer quick questions for other wishing to contribute, having problems to run PerfKit, or other relevant discussions.

**Comment by voellm** [comment]
We moved this discussion out a week or so.

Kubernetes has an IRC and we considered it as well. So far we've fielded
questions pretty fast via GitHub. If the volume goes up IRC may be the
solution. How about opening an issue for getting IRC setup.

**Comment by voellm** [comment]
Carlos lead a discussion at the recent community meeting around config and it dovetails nicely with our plans for a larger refactor.  The community discussion slide is here https://docs.google.com/presentation/d/1XLx3pnwAzI0XHohWxcNQbxnN91jcJXYSAPd6xFfD6Hw/edit#slide=id.g64899ba87_1_58

What we would like to do is refactor all the current config and flags into a more consistent pattern.  Some properties we want are;
- Single way to describe a benchmark config
- Be able to override flags in the config
- Be able to have heterogeneous machine types and clouds

Eric is going to have a design doc and one he has a first pass we'll share it here for further editing.  Should be in a couple of weeks or less.

**Comment by voellm** [comment]
A related issue was opened today - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/429 suggestion we use Ansible for config.

What I'd like to do in the short term is make sure our config file is compatible with Ansible should we decide to make that change in the future.  So another requirement is to be as Ansible compatible as possible.

**Comment by voellm** [comment]
Another ask to consider :)
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/430

**Comment by ehankland** [comment]
The config refactor has been merged so this is now possible - see https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/PerfKitBenchmarker-Configurations for more information.

**Comment by meteorfox** [comment]
@ehankland thanks for closing. I forgot to close it.
