### ISSUE TITLE
stress_ng benchmark fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1940]
The stress_ng benchmark installs stress-ng using the package manager.  The version of stress-ng installed with Ubuntu 18.04 has changed behavior in a few ways compared to how the benchmark code is written...
Issues causing complete failure:
- the '--metrics-brief' output goes to STDERR instead of STDOUT
- two of the stressors (cpu-online, oom-pipe) have been disabled unless the '--pathological' flag is also passed to stress-ng

Issues causing partial failure:
- some of the stressors (e.g. numa) are printing additional lines of output causing the output parser to fail, this results in 1) not getting the result for this stressor and 2) not calculating/reporting the geomean of all results at the end of the run

**Comment by s-deitz** [comment]
This should be fiexed with https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/658dd18b9dfed1a8a98506867e3c75a133819b32
