### ISSUE TITLE
fio hanging at dselect-upgrade on local VM

### ISSUE THREAD

**Issue by pramodbiligiri** [GoogleCloudPlatform/PerfKitBenchmarker#197]
I am running the fio benchmark on a Ubuntu 14.04 VM hosted in VirtualBox on a Ubuntu host OS. The benchmark hangs at the dselect-upgrade phase during the cleanup.

I'm using the git commit 6b2877c51d3e7c5a80f5397f12f842da1eda9b5a

**Comment by meteorfox** [comment]
Which Ubuntu edition, server or desktop ? Better yet, if you could somehow share the same virtualbox image you use, so I can replicate and debug locally.

I've been using Ubuntu 14.04 VMs on Rackspace and Google clouds with no problems, and the 'dselect-upgrade' command that PerfKit runs is common to all benchmarks that run on a Debian based machine.

**Comment by pramodbiligiri** [comment]
I'm using Ubuntu 14.04.2 LTS Desktop edition. I will try to upload the virtualbox image later today. Even I was surprised to see the issue as I thought the cleanup is part of all benchmarks.

**Comment by voellm** [comment]
Please include the log output around the error.  That will give us more context on the error you are seeing.  Thanks.

**Comment by voellm** [comment]
These benchmarks have been completely reworked since this time and best I can tell this issue no longer exists.
