### ISSUE TITLE
Python3 Readiness

### ISSUE THREAD

**Issue by imswynne** [GoogleCloudPlatform/PerfKitBenchmarker#1989]
Hi, I'm a Cloud Software Engineer at Intel and am curious about the current state of Python3 readiness in PerfkitBenchmarker. I've noticed a lot of Python3 compatibility commits in the last few months, but as of a couple of weeks ago, I couldn't run PKB with Python3. Is it on track for the end of Python2 support? If this is something you could use help with, a summary of the current status and areas that need work would be useful to help us determine if this is something we can help with in a coordinated way. We already have the CLA taken care of. 

Thanks,
Michael Wynne

**Comment by dlott** [comment]
Closing due to age.  Feel free to reopen or open a new issue if you have specific repro and pkb.log you'd like me to take a look at.
