### ISSUE TITLE
Cannot specify different SSH port for Static VM

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#199]
Even when using the flag `--ssh_options -p 2222`, the SSH command used by PerfKit then has two -p flags as follows:

```
/usr/bin/ssh -A -p 22 vagrant@127.0.0.1 .... -p 2222 hostname'
```

But, first flag still takes precedence.

**Comment by meteorfox** [comment]
Please assign to me.

Should we add a parameter on the static_vm JSON definition to specify an SSH port?

**Comment by cmccoy** [comment]
Assigned - thanks for reporting this.  The port flag is specified a lot of places, unfortunately.

I think allowing the user to specify additional options to `ssh` would be preferable to adding a port - then it's more general.

**Comment by meteorfox** [comment]
Just to be clear.

Is the intended behavior that whenever something like ssh_options='-p 2222' is specified that it should overwrite any flags of the default flags (in this case -p 22 -> -p 2222)?

**Comment by cmccoy** [comment]
Generally I don't think that `-p 22` should be specified unless the user explicitly provides it as an SSH option. The current behavior (always specifying `-p`) prevents overriding the default port in `~/.ssh/config` as well.

**Comment by meteorfox** [comment]
Actually, so I added the host to the SSH config, and specify the port there. Using it that way, the SSH commands work.

Now, but then it hits another bug.

When it does the SCP, or the ```RemoteCopy()``` method, it reuses the same ```ssh_options```, but now SCP doesn't take a -p flag but a -P for the port, and throws this [stack trace](https://gist.github.com/meteorfox/52e9596c8fac5b6961db)

**Comment by voellm** [comment]
Carlos did you have a pull request for this?  Is this issue closed?

**Comment by meteorfox** [comment]
Pull request is #201
