### ISSUE TITLE
Python3 and GCP issues

### ISSUE THREAD

**Issue by andycockers** [GoogleCloudPlatform/PerfKitBenchmarker#2011]
Hi,

I've been trying to run on GCP with an Ubuntu 18.04 VM with Python3. I get cascading module issues, which I have resolved by installing the correct modules and/or changing the code to point at correct modules.

I have noticed that even though I am running on GCP, it is trying to load aws_network from aws_dpb_emr.py. I don't want or need to install AWS deps.

Finally, after working around numeous module issues, I'm stuck on perfkitbenchmarker/flag_util.py throwing an error.

`PerfKitBenchmarker-1.13.0/perfkitbenchmarker/flag_util.py", line 276, in __init__
    if isinstance(convertible_to, (basestring, units.Unit)):
NameError: name 'basestring' is not defined`

My question is, how can I run this using python3, and how can I run on GCP so that I don't have to install other providers deps.

**Comment by andycockers** [comment]
Note, I just installed python 2.7 and pip using apt and a benchmark is now running.

**Comment by dlott** [comment]
Hi Andy,

Unfortunately the 1.13 release is quite dated.  As you note, running from master/head is should work completely for Python 2.7.  It should also work in most cases with Python 3.6.  See some discussion in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/1989.

If you run into specific issues running in Python 3.6 from master/head, please feel free to open a new issue with repro steps and your pkb.log and assign it to me to take a further look.  I'm also happy to review pull requests.

Thanks,
David

**Comment by s-deitz** [comment]
As an aside, we are working towards making periodic stable releases again. I don't have a date for when we will start this, but hopefully by the end of the year.
