### ISSUE TITLE
how to config redis benchmark test

### ISSUE THREAD

**Issue by XIAHUALOU** [GoogleCloudPlatform/PerfKitBenchmarker#2047]
It's the first time i use this tool to run redis benchmark test.but something wrong happend,it reminds me of below error,how to set up ,could u tell me?

Traceback (most recent call last):
  File "pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/root/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1244, in Main
    return RunBenchmarks(mitmSvc)
  File "/root/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1127, in RunBenchmarks
    benchmark_specs = _CreateBenchmarkSpecs()
  File "/root/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 561, in _CreateBenchmarkSpecs
    benchmark_tuple_list = benchmark_sets.GetBenchmarksFromFlags()
  File "/root/perfkitbenchmarker/perfkitbenchmarker/benchmark_sets.py", line 391, in GetBenchmarksFromFlags
    user_config = configs.GetUserConfig()
  File "/root/perfkitbenchmarker/perfkitbenchmarker/configs/__init__.py", line 228, in GetUserConfig
    'references are defined. Error received:\n%s' % e)
perfkitbenchmarker.errors.ParseError: Encountered a problem loading config. Please ensure that all references are defined. Error received:
found undefined alias 'default_single_core'

static_vms:
  - &worker
    ip_address: 106.12.72.181
    user_name: pkb
    ssh_private_key: ~/.ssh/id_rsa
    internal_ip: 106.12.72.181
redis:
  description: >
      Run memtier_benchmark against Redis.
      Specify the number of client VMs with --redis_clients.
  vm_groups:
    default:
      vm_spec: *default_single_core

**Comment by yuyantingzero** [comment]
Can you paste command you use?

**Comment by XIAHUALOU** [comment]
> Can you paste command you use?

 python pkb.py --benchmarks=redis --benchmark_config_file=sysbench_cpu_baremetal.yaml --ignore_package_requirements

**Comment by XIAHUALOU** [comment]
> > Can you paste command you use?
> 
> python pkb.py --benchmarks=redis --benchmark_config_file=sysbench_cpu_baremetal.yaml --ignore_package_requirements

is there something wrong,it didn't work

**Comment by jerlawson** [comment]
What is the configuration you're using? Can you post what your sysbench_cpu_baremetal.yaml looks like?
This is odd since default_single_core is a valid constant but maybe there's something different with your config.

**Comment by XIAHUALOU** [comment]
Uh,actually even official redis test on ubuntu,I also met errors,could u send me a yaml file which can make redis_benchmark.py work properly at ubuntu。

 

发件人: Jeremy Lawson <notifications@github.com> 
发送时间: 2019年11月28日 7:55
收件人: GoogleCloudPlatform/PerfKitBenchmarker <PerfKitBenchmarker@noreply.github.com>
抄送: XIAHUALOU <390306467@qq.com>; Author <author@noreply.github.com>
主题: Re: [GoogleCloudPlatform/PerfKitBenchmarker] how to config redis benchmark test (#2047)

 

What is the configuration you're using? Can you post what your sysbench_cpu_baremetal.yaml looks like?
This is odd since default_single_core is a valid constant but maybe there's something different with your config.

**Comment by XIAHUALOU** [comment]
python pkb.py --benchmarks=redis --benchmark_config_file=/redis.yaml --ignore_package_requirements

and redis.yaml

       

static_vms:

  - &worker

    ip_address: 106.12.72.181

    user_name: pkb

    ssh_private_key: ~/.ssh/id_rsa

    internal_ip: 106.12.72.181

redis:

  vm_groups:

    default:

      vm_spec: *default_single_core

 

发件人: yuyanting <notifications@github.com> 
发送时间: 2019年11月23日 7:13
收件人: GoogleCloudPlatform/PerfKitBenchmarker <PerfKitBenchmarker@noreply.github.com>
抄送: XIAHUALOU <390306467@qq.com>; Author <author@noreply.github.com>
主题: Re: [GoogleCloudPlatform/PerfKitBenchmarker] how to config redis benchmark test (#2047)

 

Can you paste command you use?
