### ISSUE TITLE
No support for Clearlinux OS type in openstack provider

### ISSUE THREAD

**Issue by keerockl** [GoogleCloudPlatform/PerfKitBenchmarker#2049]
Can you please add support for Clearlinux in openstack providers?

**Comment by dlott** [comment]
What  is needed beyond https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/2117

**Comment by keerockl** [comment]
Can you please also pick up #2112?

**Comment by dlott** [comment]
I think this is complete.  Please reopen if there are further issues.
