### ISSUE TITLE
Perfkit can't ssh to VMs once it is created in OpenStack environment 

### ISSUE THREAD

**Issue by ashutoshbhatt1** [GoogleCloudPlatform/PerfKitBenchmarker#2057]
Running below command in OpensStack environment

>  ./pkb.py  --cloud OpenStack --machine_type=m1.small --openstack_network=external-network-shared --os_type=centos7 --benchmarks=ping

Perfkit is creating VMs successfully but can not ssh into it for ping or iperf benchmark test. Getting Permission denied when it is trying to ssh to VMs. 

> 
> 2019-12-12 17:46:36,301 2dee6931 Thread-1 ping(1/1) vm_util.py:364 INFO     Running: ssh -A -p 22 ubuntu@X.X.X.X -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/sc/l_g86zr57qg0pr7jbxj3c3340000gn/T/perfkitbenchmarker/runs/2dee6931/perfkitbenchmarker_keyfile -o ControlPath="/var/folders/sc/l_g86zr57qg0pr7jbxj3c3340000gn/T/perfkitbenchmarker/runs/2dee6931/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m hostname
> 2019-12-12 17:46:36,608 2dee6931 Thread-2 ping(1/1) vm_util.py:364 INFO     Running: ssh -A -p 22 ubuntu@X.X.X.X -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/sc/l_g86zr57qg0pr7jbxj3c3340000gn/T/perfkitbenchmarker/runs/2dee6931/perfkitbenchmarker_keyfile -o ControlPath="/var/folders/sc/l_g86zr57qg0pr7jbxj3c3340000gn/T/perfkitbenchmarker/runs/2dee6931/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m hostname
> 2019-12-12 17:46:36,856 2dee6931 Thread-1 ping(1/1) vm_util.py:421 DEBUG    Ran: {ssh -A -p 22 ubuntu@X.X.X.X -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/sc/l_g86zr57qg0pr7jbxj3c3340000gn/T/perfkitbenchmarker/runs/2dee6931/perfkitbenchmarker_keyfile -o ControlPath="/var/folders/sc/l_g86zr57qg0pr7jbxj3c3340000gn/T/perfkitbenchmarker/runs/2dee6931/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m hostname}

ReturnCode:255
STDOUT:
STDERR: Warning: Permanently added 'X.X.X.X' (ECDSA) to the list of known hosts.
ubuntu@X.X.X.X: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
>

**Comment by jacob-jarick** [comment]
I solved a very similar issue for myself.

first use queens version of packstack if you are using packstack, I ran into issues with stien.

**Second and most important for SSH issues:**
try lowering the MTU on your physical interface for the packstack/openstack server and the client you perform tests from.

I was able to debug and confirm this issue by running:

<pre> ssh -vvv ubuntu@10.1.1.234 \
-2 -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
-o PreferredAuthentications=publickey -o PasswordAuthentication=no \
-o ConnectTimeout=5 -o GSSAPIAuthentication=no \
-o ServerAliveInterval=30 -o ServerAliveCountMax=10  \
-i /tmp/perfkitbenchmarker/runs/bccaf369/perfkitbenchmarker_keyfile
</pre>

from the same server I was running the gperfkit tests.

the command I used on the packstack server to lower the MTU:

<pre>ifconfig enp2s0 mtu 1400
ifconfig br-ex mtu 1400
</pre>

The bridge adaptor setting may not be required but I did it to be safe.
I also performed the same on the gperfkit host.

After reading through the source a bit, I believe this is the correct command to run against openstack:

<pre>./pkb.py \
--cloud=OpenStack \
--machine_type=m1.small \
--image='ubuntu-16.04' \
--benchmarks=ping --openstack_network=private \
--openstack_floating_ip_pool=external_network  \
--os_type=debian</pre>

note: I found a potential issue in the code where --openstack_network and --openstack_private_network (depreciated) actually check for a network named private and not the network supplied in the command line arguments.
I renamed private_network in horizon to private. I need to do further digging to confirm but I have it working finally.

note (2): I dont believe modifying the source to use ubuntu-16.04 is necessary and it does appear to slow down benchmarks by repeatedly trying to install the package "python" which does not exist in ubuntu 16.04+. This does not cause the benchmark to fail just slows it down.

**Comment by srelf-ukcloud** [comment]
So i would say your setting --os_type=centos7 but your not passing --openstack_image_username=centos

in your output its showing its attempting to log in with the user ubuntu, which if your using the centos images available for openstack, wont work as the user required is centos.
