### ISSUE TITLE
Tables on README seem to be broken

### ISSUE THREAD

**Issue by dPhanekham** [GoogleCloudPlatform/PerfKitBenchmarker#2107]
Tables like https://github.com/GoogleCloudPlatform/PerfKitBenchmarker#useful-global-flags
do not seem to be displaying correctly since this commit:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/72e2806f41ecbb6137cb10ae6a6236819aeb67c0

**Comment by dPhanekham** [comment]
![image](https://user-images.githubusercontent.com/2540864/73967763-2641af80-48de-11ea-9ccd-a1986441fcae.png)

**Comment by bvliu** [comment]
Thanks for reporting this, it should now be fixed. Closing.

**Comment by dlott** [comment]
Fixed with https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/2124
