### ISSUE TITLE
Creation of DebianBasedAzureVirtualMachine failed due to overconstrained Allocation Request

### ISSUE THREAD

**Issue by hungvelo** [GoogleCloudPlatform/PerfKitBenchmarker#213]
2015-04-15 23:42:22,450 4209b208 Thread-4 redis(1/1) INFO     Running: azure vm show --json perfkit-4209b208-3
2015-04-15 23:42:26,248 4209b208 Thread-4 redis(1/1) ERROR    Got exception running _CreateResource: Creation of DebianBasedAzureVirtualMachine failed.

azure.err:
Error: Compute.OverconstrainedAllocationRequest : The VM size (or combination of VM sizes) required by this deployment cannot be provisioned due to deployment request constraints. If possible, try relaxing constraints such as virtual network bindings, deploying to a hosted service with no other deployment in it and to a different affinity group or with no affinity group, or try deploying to a different region.
    at /usr/lib/node_modules/azure-cli/node_modules/azure/node_modules/azure-mgmt-compute/lib/computeManagementClient.js:24686:30
    at /usr/lib/node_modules/azure-cli/node_modules/azure/node_modules/azure-mgmt-compute/lib/computeManagementClient.js:285:14
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:158:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:244:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/redirectfilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:49:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)

**Comment by hungvelo** [comment]
Also when the test fails, the resources (virtual machines and cloud services) are left behind and do not get cleaned up. Will have to manually delete resources.

**Comment by voellm** [comment]
We should most definitely not leave resouces behind. Please open a P1 issue
for that.

**Comment by ehankland** [comment]
The error seems related to the availability of VM sizes in the region you were attempting to run in. Does running in a different region work?

Also, what were the circumstances under which it failed to clean up? Did you Ctrl-C or did you let it complete running? Being able to see a more complete log would be helpful.

**Comment by hungvelo** [comment]
Ehankland, I'll be happy to provide the full log file. I let the test run to complete until it died by itself. All 5 virtual machines and 6 cloud services are still up and running. Can I send the log file directly to you? For the original issue, I found out why the test failed to create additional virtual machines. It's because the subscription policy limit for resource type 'cores count' was exceeded. The limit for resource type 'cores count' is 20 per subscription. I am not sure why this quota is so low on Azure, and there is no option to increase it yourself - a request has been submitted to the support team. Once the limit is increased, I'll try it again. Thanks.

**Comment by ehankland** [comment]
Thanks for the info - yep you can send it to me.

**Comment by hungvelo** [comment]
Increasing the policy limit for cores count and cloud services has fixed the issue - redis workload completed successfully and all resources (VM instances, disks, networks, cloud services) were cleaned-up properly this time. The clean-up bug will be fixed by new issue #214 .
