### ISSUE TITLE
Improve the FIO benchmarks

### ISSUE THREAD

**Issue by stfeng** [GoogleCloudPlatform/PerfKitBenchmarker#221]
Currently there is a fio benchmark in PKB, it mostly works but needs some improvement. The core testing logic is driven by an FIO job file which is specified by the user who runs this benchmark, that's quite flexible and good. What's missing are:

1. The ability to test directly against a device in addition to testing against a file (that is, test against /dev/sdb). Basically we need to be able to handle the case where the flag fio_benchmark_file points to a device rather than a file, specifically, the prepare and cleanup logic needs some change to handle this.

2. The ability to provision (write) the entire test file, or the entire test device in the prepare step as instructed by the user. This is for some read or random read test cases, to run those properly, the device or file has to be filled first.

**Comment by stfeng** [comment]
@voellm FYI, this is the fio improvements we talked about, which is necessary to enable full automation for any fio/raw device benchmarking.

**Comment by stfeng** [comment]
@yuyantingzero Would you be able to work on this soon? I've talked to Tony about this.

**Comment by yuyantingzero** [comment]
I can start on this next week.

**Comment by yuyantingzero** [comment]
pull request #236
