### ISSUE TITLE
Persistence of VM_TMP_DIR

### ISSUE THREAD

**Issue by mnarusze-intel** [GoogleCloudPlatform/PerfKitBenchmarker#2226]
By default, PKB creates a temporary directory on target systems under `/tmp/pkb` as set in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/vm_util.py#L50. The issue with this path is that on some systems `/tmp` is not persistent across reboots. We've seen failures when we run things stage by stage and reboot the server in between stages (specifically between provision and prepare). PKB expects some files/directories to be present in prepare but they're nowhere to be found.

We would be happy to submit a PR but we need an understanding on what's the best solution:

1. Adding a new global variable like `VM_PERSISTENT_DIR` (ideally as a flag) and moving all data that requires persistence between stages there.
2. Moving `VM_TMP_DIR` permanently to something persistent like `/var/tmp`. This will impact many workloads as there's multiple references to `/tmp/pkb` in the code (which is wrong on its own but that's not the point here). There are probably other implications which I can't think of right now.
3. Allowing to set `VM_TMP_DIR` by changing it into a dynamic flag. Same problems will apply as in the first point but only to those who change the value.
4. Make sure that `/tmp` is persistent during runtime, remounting it if it's not.

**Comment by pmkc** [comment]
I like #3 making it a flag. It does seem that /var/tmp/pkb is more likely to be reboot resistant and should be portable, so I like that as a default (and cleaning up uses of /tmp/pkb would also be required.

I should get a second opinion before asking you for a PR.

**Comment by pmkc** [comment]
The internal consensus is that, while we could support some of these changes VM_TMP_DIR should only hold ephemeral content that should be wipable on reboot, whereas other directories like INSTALL_DIR, should be reboot resilient.

You specifically mentioned rebooting before prepare, so very little should be on the VM. Was the issue that VM_TMP_DIR  was not recreated? or that it lost critical content?

**Comment by mnarusze-intel** [comment]
It lost critical content that was prepared in between stages, `provision` created something that `prepare` needed but it was gone due to the reboot. The reboot is an optional step in some cases for us

**Comment by pmkc** [comment]
My point is nothing especially not Provision should rely on VM_TMP_DIR persisence. I believe you found one or more cases that do rely on that, but could we fix those cases and keep VM_TMP_DIR for short lived files?

**Comment by mnarusze-intel** [comment]
Yeah sure, that makes sense - I just think that there are many benchmarks that currently use VM_TMP_DIR and assume its persistence across stages, so the effort to address it across all of PKB will probably take some time... but I'll double check if that's indeed the case

**Comment by mnarusze-intel** [comment]
I took another look and it looks like benchmarks are not using `VM_TMP_DIR` to share data between stages. That said, `VM_TMP_DIR` is currently created in `provision` stage:
 https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/51f49214bed75c050e4e94c67dd8d902e8230500/perfkitbenchmarker/benchmark_spec.py#L456

which means that if a reboot happens after `provision`, `VM_TMP_DIR` might not exist. In other words, any benchmark that uses `VM_TMP_DIR` outside of `provision` stage will fail on systems with volatile `/tmp`.

I think it makes sense to establish another variable (or reuse INSTALL_DIR) for content that should persist across stages, but `VM_TMP_DIR` should also be accessible in all stages.

Thoughts?

**Comment by pmkc** [comment]
Sorry for dropping this for a week.

How are you rebooting?

We usually reboot with the [Reboot](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/3334c55e31afd7dc869b550b1402e346d3c81490/perfkitbenchmarker/virtual_machine.py#L343) method, which recreates the directory in [_AfterReboot](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/2ea19796ac1388810ef31b825129e913cf6b0404/perfkitbenchmarker/linux_virtual_machine.py#L926).

I understand this wouldn't work if you run PKB one stage at a time and manually reboot between them.

**Comment by mnarusze-intel** [comment]
You are right, we reboot outside of PKB as there's some steps we have defined outside of the framework. We'd rather keep it that way due to our pipeline architecture

**Comment by pmkc** [comment]
Ok I accept that this is a real issue for your workflow, but I don't want to change the defaults for the reasons you initially wrote. I still like a flag and a refactor to use that flag more broadly (the places that hard-code /tmp/pkb. 

If you could put that in a PR, I could get it merged. Does that sound reasonable?
