### ISSUE TITLE
tempdir generation breaks SSH on macos

### ISSUE THREAD

**Issue by bleything** [GoogleCloudPlatform/PerfKitBenchmarker#2233]
The default `temp_dir` path on macos is too long and causes SSH to fail. This manifests as PKB looping forever on the connection check step. Copying/pasting the command shows the error:

```
$ ssh -A -p 22 perfkit@[redacted] -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/tp/vv4yshsd70qfn9qlfrsnl7_000lbtv/T/perfkitbenchmarker/runs/609d5015/perfkitbenchmarker_keyfile -o   ControlPath="/var/folders/tp/vv4yshsd70qfn9qlfrsnl7_000lbtv/T/perfkitbenchmarker/runs/609d5015/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m hostname
unix_listener: path "/var/folders/tp/vv4yshsd70qfn9qlfrsnl7_000lbtv/T/perfkitbenchmarker/runs/609d5015/ssh/[redacted].YVBXsmnvZVRPpdlR" too long for Unix domain socket
```

This is mostly macos's fault and not PKB's but it does break PKB on the mac. One possible solution is shortening the suffix from 'perfkitbenchmarker' to 'pkb'... this works for me but I'm not sure it's the best solution. I'll put in a PR for it just in case.

**Comment by yuyantingzero** [comment]
Can you try --temp_dir?

**Comment by dlott** [comment]
Recommend adding check on the length of control path and throw an error on MacOS if it's too long and suggest using `--temp_dir`.
