### ISSUE TITLE
Use "," or ":" as separator in sed instead of "/" to reduce use of "\"

### ISSUE THREAD

**Issue by ChaosEternal** [GoogleCloudPlatform/PerfKitBenchmarker#2280]
For example, in this line
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/03865f2522f8c00d1438e30237bb82d74d7388c9/perfkitbenchmarker/linux_packages/hpcc.py#L307

instead of writing:

s/\\$(HOME)\\/netlib\\/ARCHIVES\\/Linux_PII/%s/
we can simply write:

s,\\$(HOME)/netlib/ARCHIVES/Linux_PII,%s,

less backslashes less complexity.

**Comment by yuyantingzero** [comment]
Sounds reasonable. If you have a patch we are happy to review and merge

**Comment by dlott** [comment]
I think @bvliu fixed this in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/2c87ffa0847411c5a993cf152526458b65a906f2#diff-9e21eb72c0e7f225b253b5de4e538964  Feel free to reopen if that's incorrect.
