### ISSUE TITLE
perfkitbenchmarker_results.json format

### ISSUE THREAD

**Issue by akshay4241** [GoogleCloudPlatform/PerfKitBenchmarker#2319]
While the mentioned file has a .json extension, it is not a json compliant file.

**Comment by dlott** [comment]
True.  It is in fact a newline delimited JSON file (historically for compatibility with https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json).  Generally we've found that our tooling handles the `.json` extension better than `.jsonl`.  If that's not the case for your tooling, you're welcome to submit a pull request making the default file name configurable.

**Comment by shubhamc521** [comment]
JSON file can be analysed but as it is not proper json.How can I convert this JSON file into excel or CSV for analysis?

**Comment by dlott** [comment]
Please see http://jsonlines.org/, referenced in the above https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json.
