### ISSUE TITLE
standard_set on local machine

### ISSUE THREAD

**Issue by hurtz** [GoogleCloudPlatform/PerfKitBenchmarker#235]
Whenever I attempt to run the standard set of benchmarks on a local workstation, the cluster_boot fails to complete. Is this a valid test for a local (non-cloud) system?

Thanks,
Jason

**Comment by voellm** [comment]
Actually no... that is a benchmark that is strictly targeted at Cloud
Provisioning.  Maybe we should add a feature to remove benchmarks like
--benchmarks=standard_set,-cluster_boot

Note the "-" before cluster_boot.

Would that help you?



On Thu, Apr 30, 2015 at 7:46 AM, hurtz <notifications@github.com> wrote:

> Whenever I attempt to run the standard set of benchmarks on a local
> workstation, the cluster_boot fails to complete. Is this a valid test for a
> local (non-cloud) system?
>
> Thanks,
> Jason
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/235>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by hurtz** [comment]
Yes, that's actually what I was going to suggest. Being able to use a group but exclude 1 or more tests. Or if the flag --static_vm_file is used, automatically exclude it (cluster_boot).

**Comment by voellm** [comment]
Good suggestions.  I'll try to have this in by the next release.

**Comment by yuyantingzero** [comment]
ping. Progress on this issue?

**Comment by voellm** [comment]
Started but not done.  I've move to a future milestone.

**Comment by klausw** [comment]
@voellm or others, any progress on this issue? I'm preparing v0.18.0 now, we should retarget this to v0.19.0 if it's not ready yet.

**Comment by ehankland** [comment]
@voellm Starting v0.19.0 soon - are we still targeting this release?

**Comment by ehankland** [comment]
@voellm I'm planning on branching soon for the release, and I don't think this has been worked on. Should this get pushed back again?

**Comment by voellm** [comment]
This is actually being fixed by @hildrum and tracked in issue - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/671

We can pass on this for V1.0.0.  Good addition however for the next release
