### ISSUE TITLE
log cpu, memory and disk info to the pkb.log file

### ISSUE THREAD

**Issue by hungvelo** [GoogleCloudPlatform/PerfKitBenchmarker#245]
Can we add cpuinfo, memory and disk info to the pkb.log file?
For example, 
   cat /proc/cpuinfo
   lshw -class cpu -class memory -class disk -class storage

**Comment by klausw** [comment]
I'm preparing v0.18.0 now, has anyone started on this? If not, it'll need to be retargeted to v0.19.0.

BTW, I think we should revisit our procedures. Having this issue marked as P0 seems inconsistent with the issue's progress (or lack thereof) :-/

For the issue itself, how should this look in practice? `cat /proc/cpuinfo` is very verbose (~12kB on my workstation) and the `lshw` command is rather slow (~11s on my workstation), so we may not want to do this unconditionally. 

Hiding it behind an opt-in flag would somewhat defeat the purpose, so it may be preferable to get a more compact and lightweight summary by default. That would also make it more feasible to include structured data in processed results as metadata.

**Comment by ehankland** [comment]
@voellm Starting v0.19.0 - should this get pushed back, or has there been progress?

**Comment by voellm** [comment]
Connor has a done a couple of checkins to add dstat.  Collectd has and open pull request... https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/398

Likely these will both go into v0.20.0

**Comment by cmccoy** [comment]
The collectd and dstat changes don't fully address this issue - running `lshw` gives much more information about system configuration than either do (clock speed, model, etc).  collectd and/or dstat do indirectly provide some information (disk size, cpu count, and total memory), but it would be clearer to explicitly list these features.  @klausw's point is well taken that /proc/cpuinfo is verbose, and lshw is a bit slow (also not available as a package by default on CentOS 6).  I think this should stay open to add more system specification logging.

**Comment by voellm** [comment]
I going to close this as "fixed"  

Hung please open if you want something additional.  Thanks for the suggestions!
