### ISSUE TITLE
Port 8080 connection refused

### ISSUE THREAD

**Issue by ssb0432** [GoogleCloudPlatform/PerfKitBenchmarker#2480]
Hello,
I'm trying to run PKB on MS Azure. When running the tomcat_wrk benchmark, I see that sometimes the benchmark runs without any problem, and at other times, I get an error message saying "Port 8080: Connection refused".
My subscription is in the US East region.
It appears that the IP address allocated during the benchmark sometimes falls outside the resource group. I have a rule setup in my network security group to allow inbound/outbound traffic on port 8080.
The PKB tomcat_wrk runs fine on v1 instances (Standard_D4), but there are problems on v2, v3, v4 instances.
Is there a way to specify the network range for the test to fall within the resource group?

**Comment by bvliu** [comment]
Hi - is this resource group PKB managed? It would be helpful if you could include a full error log/trace here. Thanks.

**Comment by ssb0432** [comment]
I experienced this problem when trying RHEL/Ubuntu OS's. It went away when I tried with CentOS 7. Looks like for other OS versions, the packages don't get installed properly. As a result, the tomcat service does not start. So, the connection refused error is not due to a network issue, but due to there being no service endpoint listening.
I have not saved error logs for other OS versions, but have successfully run the benchmark with CentOS 7 on many different types of instances.

**Comment by dlott** [comment]
Hi,

Diffing the logs between a successful and failed install is the next best step.  Specifically you'll probably get an actionable error message for one of these commands:

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/398494c0a977e1003d2d0ba5491caf40266e8f4d/perfkitbenchmarker/linux_packages/tomcat.py#L49

**Comment by dlott** [comment]
Closing due to age.  Feel free to reopen if you find more logs we can help debug.
