### ISSUE TITLE
Pull Unixbench from GitHub vs code.google.com

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#257]
Talked to the Unixbench owners on Code.google.com and they have moved their project to   https://github.com/kdlucas/byte-unixbench

**Comment by voellm** [comment]
Looks like CH also have a GitHub repository so we have options on which to use.

**Comment by yuyantingzero** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/467

**Comment by ehankland** [comment]
Looks like the above PR fixed this. Closing
