### ISSUE TITLE
object_storage_service

### ISSUE THREAD

**Issue by pdeyhim** [GoogleCloudPlatform/PerfKitBenchmarker#2605]
object_storage_service benchmarks executes MultiStreamDelete which expects /tmp/pkb/pkb-objects-written to exist. For the CLI scenario (and potentially others) that file is not written which causes the test to fail. The only way around this failure is to set object_storage_objects_written_file_prefix or keep_bucket flag

Got non-zero return code (1) executing python /tmp/pkb/wait_for_command.py --status /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.status --exclusive /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.exclusive --stdout /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.stdout --stderr /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.stderr --delete
Full command: ssh -A -p 22 perfkit@35.223.173.131 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/f608ca00/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/f608ca00/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m python /tmp/pkb/wait_for_command.py --status /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.status --exclusive /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.exclusive --stdout /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.stdout --stderr /tmp/pkb/cmd4dd39cbc-839f-47af-abe5-3c48e11e653f.stderr --delete
STDOUT: STDERR: INFO:root:Storage provider is GCS, bucket is pkbf608ca00, scenario is MultiStreamDelete
Traceback (most recent call last):
  File "/tmp/run/object_storage_api_tests.py", line 1304, in <module>
    sys.exit(Main())
  File "/tmp/run/object_storage_api_tests.py", line 1301, in Main
    return MultiStreamDelete(service)
  File "/tmp/run/object_storage_api_tests.py", line 831, in MultiStreamDelete
    with open(FLAGS.objects_written_file, 'r') as object_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pkb/pkb-objects-written'

**Comment by shyamsabhaya** [comment]
Hi @pdeyhim,

Do you have log file for this run? It would also be nice to know which commands you ran for the this object_storage_benchmark run.
