### ISSUE TITLE
openstack benckmarker does not working; No BaseVirtualMachine subclass defined with the attributes:

### ISSUE THREAD

**Issue by yasmindemiral** [GoogleCloudPlatform/PerfKitBenchmarker#2615]
I try to running perfkitbenchmarker at OpenStack on ussuri versions, I follow these below steps:

   cd $HOME && git clone https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git
   cd PerfKitBenchmarker/
   pip install --upgrade pip
   pip install -r requirements.txt
   pip install -r perfkitbenchmarker/providers/openstack/requirements.txt 
   ./pkb.py --cloud=OpenStack --machine_type=m1.medium --openstack_network=provider --benchmarks=ping --image='ubuntu1604'

but it gave an error; log is : http://paste.openstack.org/show/800534/

Do you have any idea?

**Comment by jellyfishcake** [comment]
It looks like the only operating systems defined for OpenStach are rhel7 and centos7 
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/openstack/os_virtual_machine.py#L409
You can either use those OS, or submit a pull request to add ubuntu1604.

**Comment by yasmindemiral** [comment]
Okey thank you for your comment @jellyfishcake. I change from ubuntu1604 to centos7. It is working. But now, when i was iperf benckmarker, creteated centos7 virtual machines, ssh command has username ubuntu, http://paste.openstack.org/show/800621/ . I didint understand it, why?

**Comment by jellyfishcake** [comment]
Looks like the username on openstack is set with a flag. You can change that to be whatever you need.
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/openstack/os_virtual_machine.py#L72

**Comment by yasmindemiral** [comment]
Yes, it was wrong flag, but it is fixed. It works, thank you.
