### ISSUE TITLE
--es_uri=local:9200 elasticsearch.exceptions.RequestError

### ISSUE THREAD

**Issue by yasmindemiral** [GoogleCloudPlatform/PerfKitBenchmarker#2646]
hi 
I want to use elasticsearch end of the test. i run ./pkb.py --cloud=OpenStack --machine_type=m1.small --openstack_network=provider --benchmarks=coremark  --os_type=centos7 --openstack_image_username=centos --es_uri=local:9200 but it gave an error: http://paste.openstack.org/show/801016/
Do you have any idea?

**Comment by wlifferth-g** [comment]
Linking in @dlott as he's familiar with the coremark benchmark!

**Comment by dlott** [comment]
Unfortunately this appears to be a problem in the ElasticSearch Publisher, with which I'm not familiar.  Perhaps @tedhtchang can help?

**Comment by yasmindemiral** [comment]
What is your elasticsearch version ? I use 7.x version, may be it related with ?  @wlifferth @dlott @tedhtchang

**Comment by yasmindemiral** [comment]
i installed 6.x version to elasticsearch, it is working. thank you
