### ISSUE TITLE
elasticsearch.exceptions.RequestError

### ISSUE THREAD

**Issue by yasmindemiral** [GoogleCloudPlatform/PerfKitBenchmarker#2659]
when i run the test fio or hpcc, ./pkb.py --cloud=OpenStack --machine_type=m1.small --openstack_network=provider --benchmarks=fio  --os_type=centos7 --openstack_image_username=centos --openstack_volume_size=20 --es_uri=local:9200 , elastic search give an error
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [metadata.size] of type [long] in document with id....   elasticseach log is http://paste.openstack.org/show/801140/

do you have any idea?

**Comment by cwilkes** [comment]
I haven't worked with elasticsearch but looking at the "size" metadata label I can see it can have that value along with ones like "100%" and "16G".  According to the FIO docs that \$mb_memory gets turned into the machine type's memory size.  I haven't seen it as a number.

Did you define a schema in ES?  Maybe it is hardcoded to expect "size" to always be a number?  Perhaps it is a special field.  I would look to see if you can change that or maybe map what we call "size" to a different name ("filesize" is already taken so perhaps "fio_size"?)

**Comment by JoshHilliker** [comment]
Getting the same error.

**Comment by spencerghkim** [comment]
Can you run other benchmarks? Or are fio and hpcc specifically the ones with problems?

**Comment by yasmindemiral** [comment]
If i use large or xlarge machine, perfit benckmarker give an error, but when i use small machine it works. But in fio, the machine size does not effect to the perfkit benckmarker, it gives errors always

**Comment by yuyantingzero** [comment]
The fio issue is related to schema, as Chris mentioned. 
I am not familiar with elastic cache, looking at PKB documentation, doesn't mention how schema is set. But size definitely shouldn't be a Long.

For hpcc, if it fails on a subset of machines, I guess you are out of memory, maybe try --memory_size_mb and set it manually or paste stacktrace.
