### ISSUE TITLE
Does pkb support kubernetes on centos8 ？or how to do the configuration？

### ISSUE THREAD

**Issue by zzniwei** [GoogleCloudPlatform/PerfKitBenchmarker#2774]
Hello expert，
When I do the performance test on kubernetes， every time when I run command like ‘./pkb.py --cloud=Kubernetes --benchmarks=iperf --kubectl=/usr/bin/kubectl --kubeconfig=/root/.kube/config --image=centos:8 --os_type=centos8’ ,
pkb will rasied  error like below picture displayed, so is it bug and how to fix it ? thanks !

![pkb-error](https://user-images.githubusercontent.com/29447404/109620598-062dff80-7b75-11eb-9f0d-1db0dd2e7c3b.png)

**Comment by bvliu** [comment]
Hi there, looks like we don't support the centos 8 image on Kubernetes yet, you'll need to add something like `class Centos8BasedKubernetesVirtualMachine ` under `kubernetes_virtual_machine.py`.  See https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/19c10d30d43f209941bd2e439524a9f45bdc423a/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py#L978 for an example. Unfortunately I'm not super familiar with how the kubernetes provider works. ccing @pmkc in case they know more.

**Comment by pmkc** [comment]
It's a little more complicated than that. A lot of the `KubernetesVirtualMachine` functionality is in subclass `DebianBasedKubernetesVirtualMachine`:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/kubernetes/kubernetes_virtual_machine.py#L339, which should not be extended by a CentOS os_type. I'm not sure why that's the case. It doesn't seem to require Debian to me, but a lot of the k8s architecture is a little shoe horned into the existing VM architecture.

It would require a bit of a refactor to have that functionality available to CentOS 8.

**Comment by zzniwei** [comment]
hi bvliu ， pmkc，
looks like centos8 is not supported yet，so it there any plan to realize the function?

brs
