### ISSUE TITLE
Question: Benchmarks sets and benchmark flags

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#285]
For Rackspace's benchmark set we would like to include certain flags along with the benchmark set. For example, include the `--unixbench_all_cores` flag, since that's how we promote executing UnixBench.

Is there a way to achieve this?

**Comment by voellm** [comment]
Not as of today but we have it planned as part of the flags refactor.

As for Unixbench now that I'm a maintainer how about we open and issue in
https://github.com/kdlucas/byte-unixbench and roll a spot release?

On Thu, May 28, 2015 at 4:07 PM, Carlos Torres <notifications@github.com>
wrote:

> For Rackspace's benchmark set we would like to include certain flags along
> with the benchmark set. For example, include the --unixbench_all_cores
> flag, since that's how we promote executing UnixBench.
>
> Is there a way to achieve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/285>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by meteorfox** [comment]
@voellm Sounds good. The issue has been open for a few years, it even has the patch attached to it, which is the same we've been using here at Rackspace, and the same one I contributed as part of perfkit.

https://github.com/kdlucas/byte-unixbench/issues/4

**Comment by voellm** [comment]
What is different now is I get to make the decision and roll a new
release.  Cheers....

On Fri, May 29, 2015 at 10:05 AM, Carlos Torres <notifications@github.com>
wrote:

> @voellm <https://github.com/voellm> Sounds good. The issue has been open
> for a few years, it even has the patch attached to it, which is the same
> we've been using here at Rackspace, and the same one I contributed as part
> of perfkit.
>
> kdlucas/byte-unixbench#4
> <https://github.com/kdlucas/byte-unixbench/issues/4>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/285#issuecomment-106871997>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by voellm** [comment]
I'm OOO next week but will pick up doing a Unixbench release after that.

**Comment by voellm** [comment]
I'm going to close this bug and pick up the flags issues as part of a larger refactor around config.  Lets track this is issue https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/193
