### ISSUE TITLE
Error fetching the ip of OpenStack VM

### ISSUE THREAD

**Issue by kevin-fibich** [GoogleCloudPlatform/PerfKitBenchmarker#2852]
The function _GetNetworkIPAddress seems to expect the content of server_dict['addresses'] to be formatted like it's usual cli string output ( "network=ip, network2=ip2" ) but because it requests format=json it receives a dict/list structure like { 'network' => [ ip ], 'network2' => [ ip2 ] } instead.

Current code then fails on line 355: addresses = server_dict['addresses'].split(',')

I guess the handling code to correctly identify the right IP to connect to requires an overhaul to deal with all the possibilities.

As a quick hack, this worked for our case:

def _GetNetworkIPAddress(self, server_dict, network_name):
    addresses = server_dict['addresses']
    for address in addresses:
      if network_name in address:
        ip = addresses[network_name][0]
        return ip

If the VM has multiple IPs in that network, it will return the first.

I will not put this into a pull request since this is a really crappy monkeypatch but if anyone runs into the same trouble maybe this helps you as well. Or maybe your datacenter burns down, so use this at your own risk.

**Comment by dlott** [comment]
@keerockl has most recently updated the OpenStack provider and may have additional thoughts?

**Comment by yasmindemiral** [comment]
Is there any progress this issue ?
