### ISSUE TITLE
GCP provider; Can we run the benchmarks with OSLOGIN enabled.

### ISSUE THREAD

**Issue by salmr0** [GoogleCloudPlatform/PerfKitBenchmarker#2903]
Is there a way to run the benchmarks with OSLOGIN enabled? 

If not is there a way to run the benchmark and disable OSLOGIN at the instance level and the project level?  Some users may not have permissions to disable OSLOGIN at a project level.

**Comment by shyamsabhaya** [comment]
PKB currently does not support OSLOGIN.

Ways to disable OSLOGIN:

1.  Project Level: `gcloud compute project-info add-metadata \
    --metadata enable-oslogin=FALSE`
2. Instance level:   `gcloud compute instances add-metadata VM_NAME \
    --metadata enable-oslogin=TRUE` OR `gcloud compute instances create VM_NAME \
    --metadata enable-oslogin=FALSE`

https://cloud.google.com/compute/docs/instances/managing-instance-access#enable_oslogin

An implementation to support OSLOGIN would be to add a boolean flag to support gcp os login. This flag would then add `--metadata enable-oslogin=TRUE` to create gce_instance when set tot true.

**Comment by s-deitz** [comment]
Please also see the section on disabling OS Login in the beginner walkthrough. It points to the same solution.
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/master/tutorials/beginner_walkthrough#disable-os-login-in-favor-of-legacy-ssh-keys

@shyamsabhaya: Since PKB doesn't use oslogin, should we always just disable oslogin on the VMs that PKB spins up?

**Comment by shyamsabhaya** [comment]
We could do that. I believe oslogin is by default set to false. Unless a project has specified `enable-oslogin=TRUE` in its metadata.

**Comment by s-deitz** [comment]
If it wouldn't hurt, I think we should. If you follow the walk-through and activate cloud shell, then it sounds like OS Login becomes enabled.

**Comment by salmr0** [comment]
Thanks.  I am looking for a way to pass an argument to pbk.py so as to disable/enable OSLOGIN at the instance level(not project level).  Based on the [comment](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/2903#issuecomment-832811675) should Interpret this to mean I can do this by running the following:

`./pkb.py --benchmarks=fio --metadata enable-oslogin=FALSE`

**Comment by salmr0** [comment]
Looks like I can control OSLOGIN at the instance level with this command:

`  --gcp_instance_metadata=enable-oslogin:FALSE `

Thanks
