### ISSUE TITLE
[Breaking change]: Deprecate the mongodb benchmark

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#294]
Pull request #279 introduces a `mongodb_ycsb` benchmark, in line with `hbase_ycsb`, and `cassandra_ycsb` (in #278). I think this is a more realistic scenario than the current `mongodb` benchmark, which:

* Only loads 1000 records.
* Only runs 1000 operations.
* Stores data on the boot disk, without using scratch disk.
* Has non-durable writes (writes return [as soon as they are written to the network socket](http://api.mongodb.org/java/current/com/mongodb/WriteConcern.html#NORMAL)).

**Comment by klausw** [comment]
Ok to close this issue? Linked pull request #279 is marked as merged. If not, please clarify what's still missing, and if applicable retarget the milestone to v0.19.0.

**Comment by cmccoy** [comment]
Retargeting to v0.19.0.

**Comment by meteorfox** [comment]
:+1: With the merge for Rackspace support #336 , the `rackspace_set` already swapped  `mongodb` for `mongodb_ycsb`

**Comment by cmccoy** [comment]
Removed in #403.
