### ISSUE TITLE
AWS VM Type m3.medium not supported

### ISSUE THREAD

**Issue by yingxia2020** [GoogleCloudPlatform/PerfKitBenchmarker#2941]
m3.medium VM type is out of date on AWS already. Any plan to replace it with an updated one?
https://aws.amazon.com/ec2/previous-generation/

We may see the following error messages when run PKB:
WARNING VM not placed in Placement Group. VM Type m3.medium not supported

**Comment by shyamsabhaya** [comment]
PKB supports all AWS machine types. It supports the latest M machines. Try running with an m5 machine by passing the name of the machine to the PKB flag `--machine_type`

**Comment by s-deitz** [comment]
When using PKB, it's generally important to always specify --machine_type so you test the machine type you are interested in, --zone so you choose a zone where you have quota for that machine type, and --benchmarks to choose which tests to run.

On the PKB side, our defaults are very out-of-date in default_config_constants.yaml. We should update these as part of this issue. What do you think @shyamsabhaya?

**Comment by shyamsabhaya** [comment]
I don't believe `default_config_constants.yaml` is out of date. PKB without flags specified will run the single core machines. m3.medium is a single core machine - AWS latest family does not have any single core machines. We could look into removing the `default_single_core`  and switch default setting to `default_dual_core` as most benchmarking has moved towards higher CPU core machines.

**Comment by yingxia2020** [comment]
Right, if change m3.medium to such as a m5 instance, default_single_core will become default_dual_core since there is not single core machines on AWS. And some README refer to m3.medium if do a grep on the code base. For backward compatible, AWS still supports m3.medium, after some retries, the VM still could be created now. But not sure how long AWS will keep supporting m3.medium.

**Comment by s-deitz** [comment]
That depends on whether we define core as a vCPU or as a physical core containing two hyperthreads. We could call m5.large a single core VM by the latter definition, but then we would need to update the default_dual_core as well. All that said, I don't think we should have benchmarks defaulting to the m3.medium. All of these machines should be updated. On GCP, I think we should update n1-standard-2 to n2-standard-2.
