### ISSUE TITLE
Netperf test fails due to parse STDOUT error

### ISSUE THREAD

**Issue by rohanshetty10** [GoogleCloudPlatform/PerfKitBenchmarker#2965]
Hello, I am trying to run the netperf test on GCP VM instances. I am getting the following error for every instance that I try it with. This is the command I am running:
`./pkb.py --project=<GCP-projectid> --benchmarks=netperf --machine_type=n2-standard-2 > n2-standard-2/netperf.log`

This is the error in the logs:

> 
> STDERR: 
> 2021-06-02 13:41:45,270 89f53144 MainThread netperf(1/1) ERROR    Netperf ERROR: Failed to parse stdout. STDOUT: MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 35.225.153.117 () port 20001 AF_INET : histogram : demo
> recv_response_timed_n: no response received. errno 4 counter 0
> 
> 2021-06-02 13:41:45,271 89f53144 MainThread netperf(1/1) ERROR    Error during benchmark netperf
> Traceback (most recent call last):
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 272, in ParseNetperfOutput
>     results = next(r)
>   File "/usr/lib/python3.7/csv.py", line 112, in __next__
>     row = next(self.reader)
> StopIteration
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 972, in RunBenchmark
>     DoRunPhase(spec, collector, detailed_timer)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 792, in DoRunPhase
>     samples = spec.BenchmarkRun(spec)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 508, in Run
>     server_vm.ip_address, num_streams)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in RunNetperf
>     for stdout in stdouts]
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in <listcomp>
>     for stdout in stdouts]
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 283, in ParseNetperfOutput
>     raise errors.Benchmarks.KnownIntermittentError(message)
> perfkitbenchmarker.errors.Benchmarks.KnownIntermittentError: Netperf ERROR: Failed to parse stdout. STDOUT: MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) p
> ort 0 AF_INET to 35.225.153.117 () port 20001 AF_INET : histogram : demo
> recv_response_timed_n: no response received. errno 4 counter 0
>
> ...
>
> 2021-06-02 13:43:36,620 89f53144 MainThread netperf(1/1) ERROR    Exception running benchmark
> Traceback (most recent call last):
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 272, in ParseNetperfOutput
>     results = next(r)
>   File "/usr/lib/python3.7/csv.py", line 112, in __next__
>     row = next(self.reader)
> StopIteration
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1131, in RunBenchmarkTask
>     RunBenchmark(spec, collector)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 972, in RunBenchmark
>     DoRunPhase(spec, collector, detailed_timer)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 792, in DoRunPhase
>     samples = spec.BenchmarkRun(spec)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 508, in Run
>     server_vm.ip_address, num_streams)
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in RunNetperf
>     for stdout in stdouts]
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in <listcomp>
>     for stdout in stdouts]
>   File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 283, in ParseNetperfOutput
>     raise errors.Benchmarks.KnownIntermittentError(message)
> perfkitbenchmarker.errors.Benchmarks.KnownIntermittentError: Netperf ERROR: Failed to parse stdout. STDOUT: MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) p
> ort 0 AF_INET to 35.225.153.117 () port 20001 AF_INET : histogram : demo
> recv_response_timed_n: no response received. errno 4 counter 0
> 2021-06-02 13:43:36,621 89f53144 MainThread netperf(1/1) ERROR    Benchmark 1/1 netperf (UID: netperf0) failed. Execution will continue.

Please let me know how I can go about fixing this issue and running the tests or if I am missing any flags/running the tests incorrectly. I would also appreciate it if the equivalent command to run this in AWS or Azure is also provided. Thank you!

**Comment by yuyantingzero** [comment]
Suggest start with `--ip_addresses=INTERNAL`  and specify netperf subtests, e.g. `--netperf_benchmarks=TCP_STREAM`, which can hopefully narrow down which exact netperf subtest is failing and/or if you are running into some firewall issues.

**Comment by rohanshetty10** [comment]
> Suggest start with `--ip_addresses=INTERNAL` and specify netperf subtests, e.g. `--netperf_benchmarks=TCP_STREAM`, which can hopefully narrow down which exact netperf subtest is failing and/or if you are running into some firewall issues.

Thanks for replying, I have run the netperf test with the `--ip_addresses=INTERNAL` flag and with and without the specific benchmark flag (TCP_STREAM), both seem to work fine. I have also run TCP_STREAM and TCP_RR benchmarks without the INTERNAL flag, this seems to work fine as well. But just running the same without benchmark or internal flags specified gives the same error. 

I have tried running this test both from a GCP VM instance with PKB and Cloud APIs enabled and also from the GCP console. 

Another assistance I required was running long tests on AWS Console leads to timeout and loss of test progress, any way to mitigate that?
Please advise. Thanks.

**Comment by yuyantingzero** [comment]
Can you confirm your 2 VMs can talk to each other through external ip.  Seems like a firewall issue, although iirc pkb should create a new firewall by default. \
In addition, TCP_CRR running on external ip is known to be flaky (but your stacktrace seems something different). Full list of supported netperf tests [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py#L81).

Can you be more specific about timeout on AWS? e.g. how long, what test/flags, log file, vm died, connection lost? \
We haven't noticed anything like that.

**Comment by rohanshetty10** [comment]
> Can you confirm your 2 VMs can talk to each other through external ip. Seems like a firewall issue, although iirc pkb should create a new firewall by default.

Hey, I have tried running 2 instances and pinging, communication through external ip works fine. I have also run pkb ping and iperf tests which work fine as well.

> In addition, TCP_CRR running on external ip is known to be flaky (but your stacktrace seems something different). Full list of supported netperf tests [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py#L81).

Looks like this could be the issue as this test failed as well without the internal flag. Here is the error details:

```
2021-06-04 04:35:07,130 ba74b701 MainThread netperf(1/1) ERROR    Error during benchmark netperf
Traceback (most recent call last):
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 272, in ParseNetperfOutput
    results = next(r)
  File "/usr/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 972, in RunBenchmark
    DoRunPhase(spec, collector, detailed_timer)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 792, in DoRunPhase
    samples = spec.BenchmarkRun(spec)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 508, in Run
    server_vm.ip_address, num_streams)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in RunNetperf
    for stdout in stdouts]
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in <listcomp>
    for stdout in stdouts]
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 283, in ParseNetperfOutput
    raise errors.Benchmarks.KnownIntermittentError(message)
perfkitbenchmarker.errors.Benchmarks.KnownIntermittentError: Netperf ERROR: Failed to parse stdout. STDOUT: MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 34.71.84.234 () port 20001 AF_INET : histogram : demo
recv_response_timed_n: no response received. errno 104 counter 0

...

2021-06-04 04:36:52,585 ba74b701 MainThread netperf(1/1) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 272, in ParseNetperfOutput
    results = next(r)
  File "/usr/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1131, in RunBenchmarkTask
    RunBenchmark(spec, collector)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 972, in RunBenchmark
    DoRunPhase(spec, collector, detailed_timer)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 792, in DoRunPhase
    samples = spec.BenchmarkRun(spec)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 508, in Run
    server_vm.ip_address, num_streams)
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in RunNetperf
    for stdout in stdouts]
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 427, in <listcomp>
    for stdout in stdouts]
  File "/home/rohan_shetty/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 283, in ParseNetperfOutput
    raise errors.Benchmarks.KnownIntermittentError(message)
perfkitbenchmarker.errors.Benchmarks.KnownIntermittentError: Netperf ERROR: Failed to parse stdout. STDOUT: MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 34.71.84.234 () port 20001 AF_INET : histogram : demo
recv_response_timed_n: no response received. errno 104 counter 0

2021-06-04 04:36:52,585 ba74b701 MainThread netperf(1/1) ERROR    Benchmark 1/1 netperf (UID: netperf0) failed. Execution will continue.
```
Any way I can run the entire netperf on GCP without the internal flag? The netperf tests are working fine on AWS.

> 
> Can you be more specific about timeout on AWS? e.g. how long, what test/flags, log file, vm died, connection lost?
> We haven't noticed anything like that.

I am running the tests on AWS using the AWS CLI. Long tests like block_storage_workload, unixbench which take a couple of hours to finish and which are running in the background end up losing progress. This happens because AWS times out after 60m  usually and has to reconnect. This also leads to resources created by pkb never getting deleted. Is there a better option to run these long tests on AWS? Because keeping the AWS CLI active in the foreground for hours doesn't seem like a viable option.
Please advise. Thanks.

**Comment by yuyantingzero** [comment]
> Any way I can run the entire netperf on GCP without the internal flag? The netperf tests are working fine on AWS.

Adding David and Shyam, who is more knowledgable about networking tests. Can you confirm TCP_CRR with external IP is the only failing tests? \
David and Shyam, do we have any workarounds?

> I am running the tests on AWS using the AWS CLI. Long tests like block_storage_workload, unixbench which take a couple of hours to finish and which are running in the background end up losing progress. This happens because AWS times out after 60m usually and has to reconnect. This also leads to resources created by pkb never getting deleted. Is there a better option to run these long tests on AWS? Because keeping the AWS CLI active in the foreground for hours doesn't seem like a viable option.

Sorry, can you provide some more details regarding how you run PKB? In general, we run with (as shown [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/0783f1de38d3867d17bfcb12514c54877c73d214#example-run-on-aws))
```
python pkb.py --benchmarks=....
```

**Comment by dlott** [comment]
Please post the full pkb.log from your TCP_CRR with external IP (or whichever subtest is failing) as this will help us diagnose what's going on.  It does sound like some sort of firewall/connectivity issue.  As Yanting mentioned, this sometimes happens, but usually with high numbers of parallel threads which you don't appear to be using.

Please open a separate issue for long running AWS just so we can keep the discussions more focused.

**Comment by rohanshetty10** [comment]
>Can you confirm TCP_CRR with external IP is the only failing tests?

I have run all the netperf benchmark tests including UDP_RR and UDP_STREAM all seem to work fine, except TCP_CRR.

>Please post the full pkb.log from your TCP_CRR with external IP (or whichever subtest is failing) as this will help us diagnose what's going on.

I have attached the pkb.log for TCP_CRR. It is the only test which is failing which I assume is the reason the main netperf test is also failing.
[pkb.log](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/6621136/pkb.log)

>Please open a separate issue for long running AWS just so we can keep the discussions more focused.

I assumed the issue was small so I didn't want to create a new thread, but I will create one now.
Thanks.

**Comment by dlott** [comment]
Thanks for the log.  Can you rerun once with `--ip_addresses=EXTERNAL` and once with `--ip_addresses=INTERNAL`?  My hunch is external fails, but internal passes?

**Comment by rohanshetty10** [comment]
> Thanks for the log. Can you rerun once with `--ip_addresses=EXTERNAL` and once with `--ip_addresses=INTERNAL`? My hunch is external fails, but internal passes?

Yes this is the case. TCP_CRR runs fine with the INTERNAL flag.

**Comment by rohanshetty10** [comment]
Hey @yuyantingzero @dlott any updates on how I can fix this issue? Any help would be appreciated.

**Comment by dlott** [comment]
Hi @rohanshetty10 we've been able to intermittently (but not consistently) reproduce this issue.  We'll keep looking at it.  In the meantime for a workaround, what are you trying to measure?  You could just run with `--ip_addresses=INTERNAL` or use `--netperf_benchmarks` if a subset of the data suffices for your use case.  You could rerun repeatedly just `TCP_CRR` as well.

**Comment by rohanshetty10** [comment]
Thanks for the update, I was working on a standardized comparision between GCP vs AWS instances. I had run the netperf tests on AWS so was waiting for the equivalent on GCP. Please keep me updated if there's a fix for this issue. Thanks.
