### ISSUE TITLE
Clarify assert of required number of disks for a benchmark

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#302]
The `copy_throughput` benchmark by default requires 2 scratch_disks, when executed with a machine_type with less number of scratch_disks 1 or 0, it raises the following assertion error:

```
  File "/home/carl6796/programming/github.com/GoogleCloudPlatform/PerfKitBenchmarker/perfkitbenchmarker/disk.py", line 49, in __init__
    assert num_striped_disks >= 1, ('Disk objects must correspond to at least '
AssertionError: Disk objects must correspond to at least 1 real disk.
```

When I got this error, I was confused because I thought that the benchmark only required 1 disk, which the machine_type already includes 1 local disk, but when I inspected the copy_throughput code, then I found out it required 2 disks.

It'd be great if we could improve this message to print the required number of sctrach disks the benchmark needs vs. the number of disks available in the machine.

**Comment by voellm** [comment]
Eric - Can you look into this?

**Comment by ehankland** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/320
