### ISSUE TITLE
When executing a benchmark set, PKB exits when there's a failure with one benchmark

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#303]
When executing a benchmark set, it might be desirable that if a benchmark fails to execute for whatever reason, to let PKB continue with the next benchmark in the set, if there are any left. Perhaps, then at the final output, mark the benchmark as 'Skipped, because it failed with the following error: ...." or something similar.

In addition, we could include some error count to abort the execution, if there are too 'Failed' benchmarks.

**Comment by voellm** [comment]
Agree - We should a continue on failure flag.

**Comment by ehankland** [comment]
I think this was fixed in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/614 . Please reopen if this doesn't satisfy your requirements
