### ISSUE TITLE
Output the PKB version in the log and as part of help and have a -v flag

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#318]
Right now PKB does not report the version that is running.  This should be part of every log, the help, and we should have a -v flag.

**Comment by cmccoy** [comment]
We have `--version`.

**Comment by yuyantingzero** [comment]
gflag currently doesn't support alias, duplicating the --version flag.
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/463
