### ISSUE TITLE
Question: Adding additional ENA network interfaces for AWS

### ISSUE THREAD

**Issue by pavelbel97** [GoogleCloudPlatform/PerfKitBenchmarker#3250]
Hi, I've searched through the AWS provider module and can't find an out of the box solution to create and attach additional ENA interfaces to target VMs. Is it the case that this isn't supported out of the box and an 'network interface' resource needs to be defined on top of the existing AWS module? 

Thanks.

**Comment by yuyantingzero** [comment]
Not too familiar with ENA myself, are you suggesting attaching multiple ENA on the same VM or just enable ENA?

Regarding enabling ENA, it should be already enabled for newer common OS.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enhanced-networking-ena-ubuntu

**Comment by pavelbel97** [comment]
Thanks for the reply.
I would like to attach multiple ENA network interfaces on the same VM - normally I would create the interface with the AWS CLI `create-network-interface` command and attach it with the `attach-network-interface` command.
