### ISSUE TITLE
Add pre-push hook to reliably catch presubmit issues

### ISSUE THREAD

**Issue by klausw** [GoogleCloudPlatform/PerfKitBenchmarker#329]
If I'm understanding it right, the current git hooks work like this:

* in *prepare-commit-msg*, add special markers to the commit message if problems are detected.
* in *commit-msg*, fail commits if the markers are found.

The problem here is that prepare-commit-msg only runs when preparing the *default* commit message, not when an existing commit is modified. Various dev changes such as rebasing or amending commits can produce code that would fail tests, but this doesn't get detected since tests don't get re-run in this case.

I think we should be able to run essentially the same tests in a pre-push hook. One complication is that it's hard to find the set of changed files for the push without knowing the base commit. Currently it's still pretty fast to just lint all Python files, for example:

```
$ flake8 $(git ls-files '*.py')
```

(This takes 0.4s on my machine for the current source.)

If checking everything gets too slow, we could reduce the set of checked files by using a diff list versus `@{upstream}` or `origin/dev`.

Out of curiosity, why does the current test setup use "1"/"0" string output for results? Seems easier to just base the logic on plain exit codes, but I may be missing something.

**Comment by cmccoy** [comment]
> Out of curiosity, why does the current test setup use "1"/"0" string output for results? Seems easier to just base the logic on plain exit codes, but I may be missing something.

We borrowed them from the good folks at [`GoogleCloudPlatform/kubernetes`](http://github.com/GoogleCloudPlatform/kubernetes) :)

**Comment by cmccoy** [comment]
Closed by #376, #363.

**Comment by klausw** [comment]
FYI, the current pre-push hook is opt-in since there's no entirely reliable way to determine the correct base branch for use in comparisons. See https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/hooks/README.md for instructions how to activate it.
