### ISSUE TITLE
create aws spot instance failed 

### ISSUE THREAD

**Issue by kwinstonix** [GoogleCloudPlatform/PerfKitBenchmarker#3291]
I want to run benchmarks with aws  spot instance,  setting flag `aws_spot_instances: true`  inf config files, then pkb.py reports this error:

> perfkitbenchmarker/pkb.py in CheckInterrupt
> AttributeError: 'AmazonLinux2BasedAwsVirtualMachine' object has no attribute 'GetInterruptableStatusPollSeconds'

This commit changed `CheckInterrupt` method,  could you have a look at this issue ?  @pmkc 

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/70609907045205219965bbaf540d4f172a0b45c7#diff-a17d1414adadeaf09b631d0d4c9a6ac3e027ef5bba6e3a6ae56fbed904549009L719-L724

**Comment by yuyantingzero** [comment]
Hao might have more context regarding this.

Does seem like a bug in our codebase.

**Comment by kwinstonix** [comment]
`perfkitbenchmarker.virtual_machine.BaseVirtualMachine.GetPreemptibleStatusPollSeconds` this method in base class should be renamed to `GetInterruptableStatusPollSeconds`.
