### ISSUE TITLE
[GCP] Missing support for Intel Ice Lake and AMD Rome/Milan

### ISSUE THREAD

**Issue by m4r1k** [GoogleCloudPlatform/PerfKitBenchmarker#3324]
Similarly to https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/2469, PBK currently doesn't support `--gcp_min_cpu_platform=icelake`, `--gcp_min_cpu_platform=rome`, and `--gcp_min_cpu_platform=milan`

Follows the description of a GCP zone where several CPU uArch are displayed
```
$ gcloud compute zones describe us-central1-a --format="value(availableCpuPlatforms)"
Intel Ice Lake;Intel Cascade Lake;Intel Skylake;Intel Broadwell;Intel Haswell;Intel Ivy Bridge;Intel Sandy Bridge;AMD Milan;AMD Rome
```

Would be possible to add support for these three missing ones?

**Comment by bvliu** [comment]
Are you looking for [these](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/gcp/flags.py#L96)? As far as I know, you can't enforce Rome on a machine, only that the machine will be rome or higher. Let me know if that helps.

**Comment by m4r1k** [comment]
Hey Brandon,

Thanks to you and @spencerghkim for making sure Ice Lake and Milan would be supported options.
From my test with N2D, it actually never happened to get a Milan system using `--gcp_min_cpu_platform=rome` (local PBK patch).

Follows the `gcloud` to get a `Rome or later` system.

```
gcloud compute instances create instance-1 --project=xxx --zone=europe-west4-a --machine-type=n2d-standard-2 \
  --network-interface=network-tier=PREMIUM,subnet=europe-west4 --maintenance-policy=MIGRATE \
  --service-account=xxx-compute@developer.gserviceaccount.com \
  --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
  --min-cpu-platform=AMD\ Rome \
  --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-10-buster-v20211209,mode=rw,size=10,type=projects/xxx/zones/europe-north1-a/diskTypes/pd-balanced \
  --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
``` 

I guess the `Rome and later` option somehow arrives to the GCE Scheduler and respected?

**Comment by yuyantingzero** [comment]
Not sure if I follow, Rome is older generation compared to Milan, so when you specify `--min-cpu-platform=AMD\ Rome \`, you will most of the time get Rome and occasionally land on Milan. 
If you do want to land on Milan, then use `--gcp_min_cpu_platform=milan`. 

Similarly for icelake, cascadelake, icelake is newer, so if you want icelake, use `--gcp_min_cpu_platform=icelake`.
