### ISSUE TITLE
[SPEC CPU2017] make build_ncpus configurable

### ISSUE THREAD

**Issue by m4r1k** [GoogleCloudPlatform/PerfKitBenchmarker#3329]
Hey there,

Currently, `build_ncpus` is a hardcoded value that comes from the config file.

To speed up the SPEC binary building process, it would be attractive to either expose a user-configurable flag (something like `--spec17_build_ncpus`) or perhaps reuse the same logic used by `--spec17_threads`[1] and then pass the `--define build_ncpus=<total num threads>` to `runcpu`.

Follows a sample code
```python
  version_specific_parameters.append(
      ' --define build_ncpus=%s ' % (vm.NumCpusForBenchmark()))
```

Here also the SPEC CPU2017 documentation regarding the `--define` argument
https://www.spec.org/cpu2017/Docs/runcpu.html#define

What do you think?

[1] https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/speccpu2017_benchmark.py#L224-L229

**Comment by spencerghkim** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/26a4c09ef4fe2343df70954d7d030752f4db3929
