### ISSUE TITLE
Redis ports configured in Firewall

### ISSUE THREAD

**Issue by kivio** [GoogleCloudPlatform/PerfKitBenchmarker#334]
Currently i can't found line in code for allow access between VM on Redis Port.

**Comment by cmccoy** [comment]
Communication between the client and redis is done over the internal IP: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/benchmarks/redis_benchmark.py#L108

**Comment by kivio** [comment]
Ok, sorry it is specific for OpenStack driver where private network needs firewall configuration too.

But we resolve this issue another way then i close this issue and remove pull request.
