### ISSUE TITLE
Is there an option to directly run ycsb perf test against an existing hbase server?

### ISSUE THREAD

**Issue by sushanb** [GoogleCloudPlatform/PerfKitBenchmarker#3372]
For the context, ycsb allows to do this through hbase-site.xml file in the class path.

bin/ycsb load hbase10 -P workloads/workloada -cp /home/ycsb-hbase/conf -p table=usertable -p columnfamily=family -threads 100.

Is there a way to do this in perfkitbenchmarker? As i see, the script does the hbase installation and everything. I wonder how hard it will be to force it to use the hbase-site and run the workload?

**Comment by bvliu** [comment]
Hi sorry for the delayed response. We don't have existing functionality to do this, however it could be implemented with some effort. I recommend taking a look at linux_packages/hbase.py as well as linux_benchmarks/cloud_bigtable_ycsb_benchmark.py, which is able to use preprovisioned bigtable instances.

**Comment by bvliu** [comment]
Closing this now, feel free to reopen.
