### ISSUE TITLE
Can you use Static Preprovisioned VMs for the Network Benchmark Tests?

### ISSUE THREAD

**Issue by HariChepyala** [GoogleCloudPlatform/PerfKitBenchmarker#3373]
Hello,

I am trying to run the Network Benchmark tests in my organization for the VPN metrics between the regions and in my Organization, it is prohibited to provision the VMs using the PKB from the Cloud Shell. Can I use the VMs that are pre-provisioned in the other projects to perform these tests?

**Comment by yuyantingzero** [comment]
Suggest you read follow section 
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker#advanced-how-to-run-benchmarks-without-cloud-provisioning-eg-local-workstation

**Comment by HariChepyala** [comment]
My --benchmark_config_file won't take the static VMs that I created to run the test. Can somone help?
