### ISSUE TITLE
Can you use Internal IP address for Network Benchmark Tests?

### ISSUE THREAD

**Issue by HariChepyala** [GoogleCloudPlatform/PerfKitBenchmarker#3374]
Hello,

I am trying to perform the Network Benchmark tests in my Organization and to test this I have run the same tests in my private gcp account. It is trying to go to the Public IP address. Is there an option to use the internal IP address with out going to the internet?

**Comment by yuyantingzero** [comment]
IIRC, you can set `ip_addresses=INTERNAL` from https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/ac1093a69f15a20d19d0296fb9e8847b6063c8c6/perfkitbenchmarker/vm_util.py#L130 

This flag is respected by netperf and iperf.
