### ISSUE TITLE
Aerospike service-threads and transaction-queues should match vm.num_cpus

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#354]
These parameters are recommended to match the number of cores per http://www.aerospike.com/docs/reference/configuration/, currently they are fixed at 4.

**Comment by voellm** [comment]
+1 to fix this.  We should follow the [default] recommendations.  Any idea
why Aerospike does not default to this behavior?

On Mon, Jun 29, 2015 at 3:21 PM, Connor McCoy <notifications@github.com>
wrote:

> These parameters are recommended to match the number of cores per
> http://www.aerospike.com/docs/reference/configuration/, currently they
> are fixed at 4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/354>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by cmccoy** [comment]
I'm not sure, but it's hardly the only product where recommended values are in the docs rather than automatically set.  Opened #360 to address this.

**Comment by cmccoy** [comment]
Resolved by #360.
