### ISSUE TITLE
[dev] image and machine_type flags are None when printed on the summary results

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#356]
On the `dev` branch, when using the default values for either image, and/or machine_type, when printed at the end in the summary results, they are shown as `None`.

Command used:
```bash
./pkb.py --cloud=Rackspace --benchmarks=iperf --scratch_disk_type=local
```

Snippet of output:
```
For all tests: cloud="Rackspace" image="None" machine_type="None" perfkitbenchmarker_version="v0.17.0-120-gbf7b0c4" zones="IAD"
```

**Comment by ehankland** [comment]
Fixed in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/357

**Comment by ehankland** [comment]
Should be fixed now - if you still have problems, please reopen the issue.
