### ISSUE TITLE
[dev] boilerplate.sh check regression

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#359]
It seems a regression has been introduced in the `boilerplate.sh` script, by the commit
[8dd30b2 Update copyright year in boilerplate files].

Looking at the step-by-step output while executing the script with the bash flag `-x`, it shows why it fails,

The output, or `DIFFER`, of the diff returns the following:
```diff
1c1
< # Copyright 2014 Google Inc. All rights reserved.
---
> # Copyright 2015 Google Inc. All rights reserved.
```

when the `boilerplate.sh` does the regex comparison with the following regex 
(Scroll to the right: interesting bit is at the end of the regex):
```bash
 "${DIFFER}" =~ ^[[:alnum:]]+[[:space:]]*< # Copyright [0-9]+ Google Inc[.] All rights reserved[.][[:space:]]*---[[:space:]]*> # Copyright 2014 Google Inc[.] All rights reserved[.]$
```
It expects the second part of the diff, after the line `---`, to contain `2014` as the reference line.

It's a simple fix, in `boilerplate.sh`, (should be good enough until 2099 :smile: )

```diff
diff --git a/hooks/boilerplate.sh b/hooks/boilerplate.sh
index 6380f10..2f56fc8 100755
--- a/hooks/boilerplate.sh
+++ b/hooks/boilerplate.sh
@@ -53,7 +53,7 @@ if [ "$(echo "${DIFFER}" | wc -l)" -eq 4 ]; then
   LINE_PREFIX='# Copyright '
   LINE_SUFFIX=' Google Inc[.] All rights reserved[.]'
   HEADER_LINE=${LINE_PREFIX}'[0-9]+'${LINE_SUFFIX}
-  REF_LINE=${LINE_PREFIX}'2014'${LINE_SUFFIX}
+  REF_LINE=${LINE_PREFIX}'20[0-9]{2}'${LINE_SUFFIX}
   DIFF_PREFIX='[[:alnum:]]+[[:space:]]*< '
   DIFF_MIDDLE='[[:space:]]*---[[:space:]]*> '
   DIFF_PATTERN='^'${DIFF_PREFIX}${HEADER_LINE}${DIFF_MIDDLE}${REF_LINE}'$'
```

**Comment by meteorfox** [comment]
@klausw can you confirm this?

**Comment by meteorfox** [comment]
@klausw Nevermind, it seems you already fixed this on #358. Thank you

**Comment by voellm** [comment]
Its and awesome community effort.

On Wed, Jul 1, 2015 at 10:03 AM, Carlos Torres <notifications@github.com>
wrote:

> @klausw <https://github.com/klausw> Nevermind, it seems you already fixed
> this on #358
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/358>.
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/359#issuecomment-117752273>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by klausw** [comment]
Sorry about the regression. FYI, I'm currently working on refactoring the hook scripts. Goals include making it easier to run checks on arbitrary sets of files, and adding a pre-push hook to consistently catch issues. (The current prepare-commit-msg hook doesn't run when amending existing commits.)

**Comment by meteorfox** [comment]
@klausw No problem. Have you looked at tox ? This how most openstack projects execute all their linters, tests, and even test on different python versions. https://wiki.openstack.org/wiki/Testing

**Comment by meteorfox** [comment]
haha :laughing: spoke too soon. Tox is already in the repo.
