### ISSUE TITLE
Defer initialization of cloud providers.

### ISSUE THREAD

**Issue by klausw** [GoogleCloudPlatform/PerfKitBenchmarker#373]
Currently, `benchmark_spec.py` always imports all known cloud provider modules including implementation modules and their dependencies, even though only one cloud provider will end up being actually used. This required some extra workarounds for lazy loading for the *openstack* provider to avoid making its requirements needed for everyone.

Investigate alternate ways of doing this so that the implementation modules only need to get loaded when the cloud type is actually being used.

**Comment by ehankland** [comment]
Fixed with https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/636
