### ISSUE TITLE
object storage benchmarks on GCP should not copy the gcloud logs

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#381]
The Object Storage benchmarks copy the .config/gcloud directory in order to get permissions.  As part of this it also copies the logs from the local machine. 

Ideally GCP should use the delegated auth mode vs trying to copy in permissions. 

However in the short term we should just stop copying the logs.

**Comment by stfeng** [comment]
Fix in pr #383 out for review.

**Comment by stfeng** [comment]
PR merged. Fixed.
