### ISSUE TITLE
Running the tutorials "inter_region_ reports" creates a VM in only one region, us-central1.

### ISSUE THREAD

**Issue by lbj0412** [GoogleCloudPlatform/PerfKitBenchmarker#3947]
I am testing while seeing the tutorial in "Reproducting inter-Region Test with Benchmarker" (1).
Proceed through the tutorial, but create an instance only in us-central1-a and run a ping test.

As instructed in "Task 3. Start a benchmark test for latency", I proceeded without changing a single letter, but instances were created only in us-central1-a and not in other regions.
The ping test runs 190 times, but all tests run only on us-central1-a.

Any workaround?

(1)https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/tutorials/inter_region_reports/README.md

**Comment by dlott** [comment]
@dPhanekham is this on your radar?

**Comment by dPhanekham** [comment]
Yes, I think I have a solution and I'll submit an update soon

**Comment by bvliu** [comment]
Should be fixed with 4fe1f18b0eaf51cbee11194f163ac8515775d93c.
