### ISSUE TITLE
Update SPEC CPU 2017 prior running

### ISSUE THREAD

**Issue by m4r1k** [GoogleCloudPlatform/PerfKitBenchmarker#3950]
SPEC CPU2017 had several updates over the years, the latest being released in Nov 2022.
https://www.spec.org/cpu2017/Docs/changes.html#v119

If anybody plans on formally submitting the results, running the latest version is also a requirement:
https://spec.org/cpu2017/press/academicpricing.html#:~:text=Starting%20February%2028%2C%202023%2C%20all%20SPEC%20CPU%202017%20benchmark%20suite%20submissions%20to%20the%20SPEC%20website%20must%20use%20Version%201.1.9

Would something like this be acceptable?
```
--- a/perfkitbenchmarker/linux_packages/speccpu2017.py
+++ b/perfkitbenchmarker/linux_packages/speccpu2017.py
@@ -85,6 +85,10 @@ def Install(vm):
   vm.RemoteCommand('echo yes | {0}/cpu2017/install.sh'.format(
       vm.GetScratchDir()))
 
+  """Updates SPECCPU 2017."""
+  # spec17 had several updates, hence let's ensure to run the latest version
+  vm.RemoteCommand('echo yes | {0}/cpu2017/bin/runcpu --update'.format(
+      vm.GetScratchDir()))
 
 def AptInstall(vm):
   vm.InstallPackages('libjemalloc-dev libomp-dev')
```

**Comment by spencerghkim** [comment]
Added in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/06523ab1915f98aab6de07a2e194e7100eb5d047
