### ISSUE TITLE
Document `--static_vm_file` format

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#40]
The format expected by `--static_vm_file` is only encapsulated in the docstring [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/606f4ce33ce5dd4fcb9dd693b639f6b22f58a0f9/perfkitbenchmarker/static_virtual_machine.py#L100-L121).

See also #38

**Comment by voellm** [comment]
From Carlos
@voellm @ehankland 
It seems to me we need to add more documentation around static_vm configurations, perhaps even sample configuration files that they can based their config from.

Also, I propose using something like a json schema to validate the config file. Here's a popular pytthon library, jsonschema

I'll make a pull request with unit test that fails by replicating this issue, and along with it we could include a fix for handling it.

----------------
Ack... I also think we need to do validation up from and have tests.

**Comment by cmccoy** [comment]
#166 addressed the validation issue, at least for scratch disk mountpoints.

**Comment by yuyantingzero** [comment]
Progress updates? Is this issue still targeting v0.16.0?

**Comment by voellm** [comment]
We've added more documentation and examples.  Not sure there is more that needs to be done.

**Comment by voellm** [comment]
Documented here - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/Can-I-run-PerfKitBenchmarker-on-my-local-machine-or-data-center%3F
