### ISSUE TITLE
Allow launching preemptible instances on Google Cloud

### ISSUE THREAD

**Issue by bogdanr** [GoogleCloudPlatform/PerfKitBenchmarker#406]
It could be very useful to specify if the instance is normal or preemptible in order to determine if there is a performance penalty. Of course, normally it shouldn't be a difference but the point of the benchmark is to show that.

**Comment by voellm** [comment]
This should already be possible with the --machine_type flag.  Though not
all co de paths in PKB handle VM failures well.

Did you try it and it not work?

**Comment by voellm** [comment]
I see the issue you are asking about.  gcloud in alpha used discreet names to those machine types but in beta it requires the "--preemptible" flag.

**Comment by voellm** [comment]
To be consistent with other compute only flags the change should be made in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/gcp/gce_virtual_machine.py much like the gcloud_scopes flag.

**Comment by voellm** [comment]
FYI ... there is a new flag added to make an instance pre-emptible.

Use "--gce_preemptible_vms --machine_type=n1-standard-1" for example to get
a preemptible n1-standard-1

Even more details...
flags.DEFINE_boolean('gce_preemptible_vms', False, 'If true, use
preemptible '52
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/20b29071f57322ff59d9a9e6ae01f4ad82f5b84a/perfkitbenchmarker/gcp/gce_virtual_machine.py#L52>
'VMs on GCE.')

On Thu, Oct 1, 2015 at 11:08 AM, noahl <notifications@github.com> wrote:

> Closed #406
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/406>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/406#event-424519662>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>
