### ISSUE TITLE
Breakdown benchmark stages to be a bit more granular

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#409]
we have today: prepare, run, cleanup
we would have liked: allocate, prepare, run, cleanup, teardown

**Comment by kivio** [comment]
I think this is part of this task: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/429

**Comment by ehankland** [comment]
Above PR fixes this
