### ISSUE TITLE
Unixbench version very old, missing ARM support

### ISSUE THREAD

**Issue by vjpai** [GoogleCloudPlatform/PerfKitBenchmarker#4130]
Hi there,

The Unixbench version downloaded as part of PKB is [version 5.1.3](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/74e9213da8238e9166461c983f105a786af5b1dc/perfkitbenchmarker/linux_packages/unixbench.py#L20-L23) which is at least 12 years old.

Master versions of Unixbench before 2022 are subject to a bug in which they [only recognize a single core on an ARM machine](https://github.com/kdlucas/byte-unixbench/issues/60) because of a [capitalization difference in the `/proc/cpuinfo`](https://github.com/kdlucas/byte-unixbench/commit/d9242458bacef0364074e28fb652fa90346d29df) file between x86 and ARM Linux. As a result, Unixbench under PKB doesn't currently yield useful results on ARM platforms like AWS Graviton instances.

The fix for this is just to use a newer version of Unixbench in the PKB Linux package.

Thanks for your consideration!

**Comment by voellm** [comment]
Can you please propose a PR to merge.  The general process is to create a fork.  Make your change and validate it.  Then create a PR for it.

**Comment by vjpai** [comment]
According to https://github.com/kdlucas/byte-unixbench/blob/master/README.md?plain=1#L34, @voellm will release a v5.2 of Unixbench when there have been enough PRs since 5.1.3. Given that it's been 8 years, would you a say that it would be a good time for a release, particularly since we know of new functionality solved since then (ARM64 support)? The answer to that question will affect the PR since it can be a decision of pulling from a new release tag or just pulling a specific tested commit. Thanks!

**Comment by s-deitz** [comment]
@vjpai Any luck on unixbench updates?

**Comment by vjpai** [comment]
I'm not pursuing this topic anymore.

**Comment by s-deitz** [comment]
Thanks for the update. Closing, but reopen if this benchmark becomes a priority and can be updated.
