### ISSUE TITLE
Error: No module named ['absl', 'blinker', ...] first time running

### ISSUE THREAD

**Issue by nurSaadat** [GoogleCloudPlatform/PerfKitBenchmarker#4178]
OS: Ubuntu 18.04

I encountered an error that I was not able to run this command `./pkb.py --benchmarks=cluster_boot --machine_type=n1-standard-2 --zones=us-central1-f --run_stage=provision,prepare,run` without getting "No module named ..." error.

Here are steps to resolve it:
1. make sure that in your virtual environment Python version is 3.9. 
   - check current Python version by running `python --version`
   - use `sudo update-alternatives` to manage Python version. In my case, I had to run
   -  `sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1`
   -  `sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2`
   -  `sudo update-alternatives --config python3` and choose number corresponding to Python 3.9
2. delete all dependencies installed by pip, otherwise you might always get message `Requirement already satisfied`. You can do it using next command `pip freeze | xargs pip uninstall -y`
3. Install dependencies using command `python3 -m pip install -r requirements.txt`

**Comment by nurSaadat** [comment]
What if docs should be updated or is there any particular reason why simple `pip install` didn't work? Maybe `pip3 install` should be used instead?

**Comment by pmkc** [comment]
This is an issue with your Python setup and not with PerfKitBenchmarker.

In our README we recommend using [venv](https://docs.python.org/3/library/venv.html) or [virtualenv](https://virtualenv.pypa.io/en/latest/) to make managing pypi dependencies easoer.

Here is a Dockerfile that installs Python3.9, venv, and PerfkitBenchmarker in Ubuntu 18.

```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git software-properties-common

# Install Python 3.9
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.9-venv

# Setup venv
RUN python3.9 -m venv /root/virtualenv
# Equivalent to `source /root/virtualenv/bin/activate` in a terminal
ENV PATH="/root/virtualenv/bin:$PATH"
# Check that we are running Python 3.9
RUN python3 --version | grep '3.9'
RUN python --version | grep '3.9'

# Install PerfKitBenchmarker
RUN git clone https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/
WORKDIR PerfKitBenchmarker
RUN pip3 install -r 'requirements.txt'

# Validate PerfKitBenchmarker
RUN ./pkb.py --version
# Will fail with FileNotFoundError: [Errno 2] No such file or directory: 'gcloud' not a module error
RUN ./pkb.py --benchmarks=cluster_boot --machine_type=n1-standard-2 --zones=us-central1-f --run_stage=provision,prepare,run || true
```

it built fine for me and the last command only fails with gcloud not being found.

On a clean machine a global update-alternatives and a root pip installation should also work fine, but it will not be stable and I strongly recommend trying out venv or virtualenv (and ideally a newer OS that has a built-in newer Python).
