### ISSUE TITLE
PerfKitBenchmarker Community Meeting #5 - August 19th

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#418]
Perfies,

The next meeting is August 19th from 10am PST to 11:30 PST.  If you have not received and invite and would like one please email voellm@google.com.

Planned Agenda:
- Rackspace on adding their Cloud to PKB
- MIT on benchmarking
- Update on PKB if there is time.
- Open discussion

  Cheers,
     Tony

**Comment by cmccoy** [comment]
Closing as stale.
