### ISSUE TITLE
Problem with start test uses OpenStack driver - KeyError 'pkb_label'

### ISSUE THREAD

**Issue by kivio** [GoogleCloudPlatform/PerfKitBenchmarker#419]
When start pkb on OpenStack based cloud we get error:
```
Logged from file connectionpool.py, line 203
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: 'pkb_label'
```

Fix proposal is here: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/410

It's not general solution (when is need to add new handler filter add is required) but works good currently and fix problem.

**Comment by voellm** [comment]
Connor I think you have reviewed this.

**Comment by voellm** [comment]
And the pull request is closed.  marking this as closed as well.
