### ISSUE TITLE
Run fio benchmark on a physical host

### ISSUE THREAD

**Issue by avinxxsh** [GoogleCloudPlatform/PerfKitBenchmarker#4248]
I want to run fio on a physical host rather than a virtual one. Is this possible? If yes, what changes will I have to make and to which files?

**Comment by s-deitz** [comment]
You can do this with a static VM, but this doesn't first-class support. Alternatively you can manually install and run FIO on the physical host without using PerfKitBenchmarker to coordinate it. Do you get some benefit of running FIO via PerfKitBenchmarker? Are you comparing it to a cloud instance?

**Comment by s-deitz** [comment]
Please reopen if this is still a problem.
