### ISSUE TITLE
Cassandra provisioning is slow.

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#434]
See comments on #430.

**Comment by cmccoy** [comment]
For `cassandra_ycsb`, this will be partly addressed by #428 (using a pre-compiled YCSB release).
I'm putting together a patch to install Cassandra and YCSB in parallel - currently the Cassandra nodes are bootstrapped, then YCSB is installed on the client.

**Comment by cmccoy** [comment]
#435 parallelizes the install of YCSB and Cassandra.
#428 speeds up the YCSB provisioning component.

**Comment by voellm** [comment]
Do you have an performance times to share?  How much faster did it get?

On Thu, Sep 3, 2015 at 1:08 PM, Connor McCoy <notifications@github.com>
wrote:

> #435 <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/435>
> parallelizes the install of YCSB and Cassandra.
> #428 <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/428>
> speeds up the YCSB provisioning component.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/434#issuecomment-137560575>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by cmccoy** [comment]
With 3 cassandra VMs and one client, the prepare phase decreases by ~67% (9 minutes to 5.5). Gains will be lower for larger cluster sizes.

**Comment by voellm** [comment]
Looks good to me... should we close?

On Fri, Sep 4, 2015 at 10:32 AM, Connor McCoy <notifications@github.com>
wrote:

> With 3 cassandra VMs and one client, the prepare phase decreases by ~67%
> (9 minutes to 5.5). Gains will be lower for larger cluster sizes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/434#issuecomment-137800816>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>
