### ISSUE TITLE
The object storage service benchmarks should specify specific versions of libraries rather than pull the latest

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#448]
In pull request #446  PKB was updated to handle the new Azure storage libraries.  What we should do to avoid breaks like this in the future is to declare the version on the pip install etc in the prepare.

**Comment by stfeng** [comment]
Done. https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/461
