### ISSUE TITLE
observed error at  BENCHMARKS = _LoadBenchmarks() in linux_benchmarks/__init__.py 

### ISSUE THREAD

**Issue by ankita121212** [GoogleCloudPlatform/PerfKitBenchmarker#4645]
Executed below pkb command and observed error.

**command** - /pkb.py --cloud=Azure --machine_type=Standard_DC8s_V3 --benchmarks=coremark

**Error** - BENCHMARKS = _LoadBenchmarks()
         return list(import_util.LoadModulesForPath(__path__, __name__)) in _LoadBenchmarks
observed above error at  linux_benchmarks/__init__.py file

**Comment by Arushi-07** [comment]
Hi, could you please share the entire pkb log.

In the command, machine type should be [Standard_DC8s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/dcv3-series#dcsv3-series) (lowercase v). This might not be cause the of the error.

**Comment by s-deitz** [comment]
Please reopen if this is still happening and share more details.
