### ISSUE TITLE
fio can be run directly on disk ?

### ISSUE THREAD

**Issue by srinivaslpalli** [GoogleCloudPlatform/PerfKitBenchmarker#472]
Hi,

 fio running fine by providing 'scratch_disk_mountpoints', but I want to run fio benchmark directly on disk ? is that possible ?

want to give like "/dev/xvdb" 

Thanks
-srinivas

**Comment by yuyantingzero** [comment]
Yes, it is possible. To run against device, you can specify --against_device=True flag while running fio benchmark. Also --device_fill_size (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/benchmarks/fio_benchmark.py#L41) to specify the size of the disk(default 100%) to prewarm. But it currently doesn't work with static_vms, since static_vm file doesn't include the device path https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/341.

**Comment by yuyantingzero** [comment]
@srinivaslpalli , just to make sure I understand your question correctly. 
Are you asking if fio benchmark can test against raw block device(answered above) or are you asking about if fio benchmark can pick a specific disk on the vm, if multiple disks is attached to that vm (which pkb doesn't have this feature yet, it always pickup the first data disk available)?

**Comment by srinivaslpalli** [comment]
Hi ,
I would want to test fio benchmark on raw device of VM. 
my VM is mounted devices like below 

[opc@c5d214 ~]$ df -m
Filesystem     1M-blocks  Used Available Use% Mounted on
/dev/xvda3         16018  5923      9259  40% /
tmpfs              29981     0     29981   0% /dev/shm
/dev/xvda1           477   148       300  34% /boot
/dev/xvdb         100794 22280     73394  24% /u02
[opc@c5d214 ~]$ 

And I am able to do fio testing on  "/" and "/u02".

But I want to test directly on "/dev/xvda3" , is that anyway possible ?

Thanks
-Srinivas

**Comment by yuyantingzero** [comment]
I don't think it is possible right now. Currently testing against raw device only works on vms created by PerfkitBenchmarker. From your setup, you are using static vms. Static vm file doesn't contain a device path, so fio benchmark won't be able to run against raw device with static vms https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/341.

**Comment by voellm** [comment]
How about we convert this in a feature ask then to include the path in the
static VM's files?

On Tue, Sep 15, 2015 at 10:09 AM, yuyanting <notifications@github.com>
wrote:

> I don't think it is possible right now. Currently testing against raw
> device only works on vms created by PerfkitBenchmarker. From your setup,
> you are using static vms. Static vm file doesn't contain a device path, so
> fio benchmark won't be able to run against raw device with static vms #341
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/341>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/472#issuecomment-140466084>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by ehankland** [comment]
You can now do this either by specifying the key "local_disks" in the old static vms json file, or by using the new config support.
To run against a device you would use the following command line:
```./pkb.py --benchmark_config_file=fio.yaml --against_device```

Where fio.yaml would have these contents:
```
static_vms:
  - &static_vm_1
    ip_address: 1.1.1.1
    user_name: perfkit
    ssh_private_key: /path/to/private/key
    disk_specs:
      - device_path: /dev/sdb

benchmarks:
  - fio: {vm_groups: {default: {static_vms: [*static_vm_1]}}}
```
