### ISSUE TITLE
Release v0.22.0

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#482]
Calls for all changes for v0.22.0.  I'll do a first "build" today to see how things look later today and release by Friday/Monday.

**Comment by voellm** [comment]
Did a scrub of all issues, pull requests, etc.  Pinged the,,, just waiting on one before doing the release https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/475

**Comment by voellm** [comment]
Update on this release... there have been a number of changes around fio and some are still in progressed.  I'd rather wait for these to be resolved before completing this.  Likely I'll roll up the release Friday and release Monday (10/5)

**Comment by voellm** [comment]
This release is making progress.  I pulled in a few this from early this morning.

So far all tests are looking good.  Should have this released tomorrow.

**Comment by voellm** [comment]
All runs are complete.  There is one issue which is the fio defaults where changed causing the runs to go from ~1000 seconds to ~7000.  We've talked about this change and for this release it will be rolled back.  

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/515

One that is in I'll cherrypick it into the release and commit today.

**Comment by stfeng** [comment]
Please also cherrypick #516 which fixes some issues introduced by #515. Without #516, existing automations that test against device will be broken because they are not aware of the need to specify the new prefill_device flag (and they should not have to). The fix in #516 will always pre-fill the device if the user is testing directly against the device.

**Comment by voellm** [comment]
This release is complete.  Connor/me also revved to v0.22.1 to fix a break on Azure VM's with apt-get.  The images had aged a bit.

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/releases/tag/v0.22.1
