### ISSUE TITLE
Tox weirdness

### ISSUE THREAD

**Issue by ehankland** [GoogleCloudPlatform/PerfKitBenchmarker#484]
I pulled down the latest bits and the unit tests failed with the following error:

$ tox
py27 develop-inst-nodeps: /usr/local/google/home/ehankland/PerfKitBenchmarker
py27 installed: blinker==1.3,colorama==0.3.3,colorlog==2.6.0,Jinja2==2.7.3,MarkupSafe==0.23,mock==1.0.1,nose==1.3.7,-e git+https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git@75dd41a6da4a2afb22be723beb423fe94bb633d2#egg=perfkitbenchmarker-master,psutil==3.0.1,python-gflags==2.0,wheel==0.24.0
py27 runtests: PYTHONHASHSEED='4239253669'
py27 runtests: commands[0] | nosetests /usr/local/google/home/ehankland/PerfKitBenchmarker/tests
EEEEEEEEEEEE........EEEE...............EE..........E
======================================================================
ERROR: Failure: ImportError (No module named concurrent)
....
....

(This was even after I made sure to pip install requirements.txt)

Modifying both the tox.ini and requirements.txt file and then undoing the changes seemed to fix whatever issue it was.

**Comment by cmccoy** [comment]
You likely need to rebuild the tox environment. By default dependencies are not reinstalled at each test run, which causes things to break when be dependencies are added. `tox -r` should do it.

**Comment by skschneider** [comment]
This was happening while attempting to commit. Should our pre-checkin use tox -r?

**Comment by cmccoy** [comment]
I'd tentatively vote to add a message with instructions to run `tox -r` if dependencies are missing. In my extremely unscientific testing, running `tox -r` doubled the testing time (5 -> 10 seconds).

**Comment by voellm** [comment]
Eric / Connor - Any takers for doing the update?

**Comment by cmccoy** [comment]
I'll update the message.
