### ISSUE TITLE
silo benchmark fails behind proxy

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#491]
From @mateusz-blaszkowski in #475: 

> silo - failed with Clone of 'git://github.com/kohler/masstree-beta.git' into submodule path 'masstree' failed. I run the test behind the proxy and this is the case. I would have changed the path to Git repository to https:// but it is hidden somewhere in 'dbtest' (look a the command which failed: cd /tmp/pkb/silo && MODE=perf DEBUG=0 CHECK_INVARIANTS=0 make -j80 dbtest). Oh, i found that the exact path is specified here: https://github.com/stephentu/silo/blob/cc11ca1ea949ef266ee12a9b1c310392519d9e3b/.gitmodules

We should switch it to `https://`.

**Comment by lleszczu** [comment]
Adding something like:
```git config --global url.https://github.com/.insteadOf git://github.com/```
in packages/build_tools.py ( or maybe directly in silo benchmark ) should fix the issue.

**Comment by voellm** [comment]
ping ... and update on this?  Should we assign it out?
