### ISSUE TITLE
Fio: when no jobfile is specified, fio is not running against scratch disk

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [GoogleCloudPlatform/PerfKitBenchmarker#496]
Let's say that scratch disk is by default mounted in /scratch0 directory.

Current simplified fio benchmark flow:
1. Fill scratch disk with 'fio-temp-file' - look at the `GenerateFillCommand()` method. It uses `fill_path` which is retrieved directly from disk object (either `mount_point` or by `GetDevicePath()` method). As a result, the following file is created: /**scratch0**/fio-temp-file . This part is OK - scratch disk is pre-filled with some data.
2. Run fio with the default fio.job file from perfkitbenchmarker/data directory. 
  - command which is being executed: `ssh root@... sudo /tmp/pkb/fio/fio --output-format=json /tmp/pkb/fio.job` (look at the Run() method)
  - fio will not be run against scratch because it produces 'fio_test_file' in /root directory (which is caused by logging as root. When logging as different user, another directory from /home will be used)
  
Expected behaviour:
fio should create a file in /scratch0 directory. In the past either --filename or --directory flag was passed to fio command, but since https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/421 it has been changed.

**Comment by yuyantingzero** [comment]
@stfeng

**Comment by noahl** [comment]
I'm testing a fix right now. PR should be coming soon.

**Comment by noahl** [comment]
Fixed in #502.
