### ISSUE TITLE
Fio: pre-filling the attached disk does not work

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [GoogleCloudPlatform/PerfKitBenchmarker#497]
Look at the fio_benchmark.Prepare() method:

`fill_size = str(DISK_USABLE_SPACE_FRACTION *
                        1000 * disk.disk_size) + 'M'`

Let's say that `disk.disk_size` is 3 and `DISK_USABLE_SPACE_FRACTION` is 0.9.
`fill_size` will be exactly `2700.0M`. This format is not accepted by fio and as a result, pre-filling the scratch volume will not work. What is worse, fio command will fail with exit_code=0 and we will not even see that something went wrong. 

My proposition would be:
1. convert `fill_size` to int before converting it to str (format like `2700M` is accepted by fio)
2. add more logging around fio command as it sometimes exits without error code.

**Comment by yuyantingzero** [comment]
@stfeng

**Comment by stfeng** [comment]
I think we should get rid of the DISK_USABLE_SPACE_FRACTION parameter, it's pretty flaky (and setting it to 90% is also just a rough estimate that don't really work for all file systems). 

If someone really wants to test against the file system (which isn't that encouraged for fio command anyway), and if they want to pre-warm the device before the testing, then the implementation here in FIO should reuse the device filling logic in the "against device case", fill the device first using /dev/*** first, then format the device again using a file system, and then mount it for subsequent testing.

**Comment by noahl** [comment]
Hi Mateusz,

This issue is already fixed in the latest fio_benchmark.py in the master
branch. It looks like the fix was committed 13 days ago, so it may not have
made it into the last release, but it will be in the next one.

Thanks,
Noah

**Comment by noahl** [comment]
If you want a fix right away, what you suggested with `int( ... )` is exactly what I implemented. You can patch your copy of fio_benchmark.py with that change, or cherry-pick commit 84dfd924fb6a4cd51485e8ae615527b9beb06a39 . I'm closing the issue, but please re-open if there's anything else I can do to help.

**Comment by stfeng** [comment]
I think to properly fix this issue, we should get rid off the DISK_USABLE_SPACE_FRACTION and merge the fill the file code with fill the device code.

**Comment by mateusz-blaszkowski** [comment]
@noahl - I have tested with a pretty fresh master version. PR with the fix was merged 2 days ago, so I was unlucky ;) anyway, thanks!

**Comment by noahl** [comment]
Fixed in #502.
