### ISSUE TITLE
Adding Cloudstack as a provider

### ISSUE THREAD

**Issue by syed** [GoogleCloudPlatform/PerfKitBenchmarker#503]
Hi, 

I'm working on adding Cloudstack as a providor to PerfKitBenchmarker. Is someone already working on it? I'm opening this to track my changes. 

-Syed

**Comment by voellm** [comment]
Syed - This would be great.  No one is working on this so it is all yours.  We do have OpenStack support so likely yours will be similar for CloudStack.

For those that dont know the difference here is a good explanation - http://www.datacenterknowledge.com/archives/2015/02/23/openstack-vs-cloudstack-the-platforms-and-the-cloud-apis/

  Tony

**Comment by voellm** [comment]
Assigning to me to handle the pull request when it comes.  Cheers...

**Comment by syed** [comment]
PR is at #527

**Comment by syed** [comment]
Closing this
