### ISSUE TITLE
Request for LOGO suggestions

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#513]
We are getting close the V1.0.0.  Some of the finishing changes are making there way in now so its time to think about a logo.

Some properties we should look for:
- Scales in size well
- Works in B&W and Color
- Is fun
- Should not be encumbered by or violate trademarks.

If you have ideas... please email them to voellm@google.com or perfkitconnect@googlegroups.com

**Comment by meteorfox** [comment]
I'm not good at designing art, but this my best try. Took me at least 2 hours to do this in GIMP.

I tried to follow the material design style. It's supposed to be a kit, kind of like like tray, with what I think are related things to PerfKitBenchmarker.

![pkb_logo_carlos](https://cloud.githubusercontent.com/assets/232300/10498765/06a437aa-7292-11e5-85fe-fae5dd92c778.png)

**Comment by voellm** [comment]
Thanks to everyone who gave suggestions.  We ran a couple of bakeoffs and landed on this...
![screenshot from 2015-11-18 10 05 13](https://cloud.githubusercontent.com/assets/5758832/11249605/bb43b9b4-8ddc-11e5-9ee2-f30c6aeb04b8.png)

**Comment by voellm** [comment]
Official logos are now checked into the gh-pages branch here - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/gh-pages/img

Thanks @yangsophia  for driving these!
