### ISSUE TITLE
Clean up fio benchmark flag logic

### ISSUE THREAD

**Issue by stfeng** [GoogleCloudPlatform/PerfKitBenchmarker#518]
1. We need to rename all fio flags to start with the "fio_" prefix.
2. We need to merge the against_device and prefill_device flags into one flag of the enum type, perhaps with the name fio_test_mode and it has the following four values: against_device_with_fill, against_device_without_fill, against_file_with_fill, against_file_without_fill
3. then we need to change the rest of code that currently consumes the against_device flag and the prefill_device flag to properly understand and process the new fio_test_mode flag.

Above is pretty much the code change involved, the more timing consuming part of this work is testing, we need to have complete test coverage of the newly named flags, including: 1) all 4 modes mentioned above, 2) for each renamed flags, test they can be used properly with their new names.

**Comment by stfeng** [comment]
@noahl, I've discussed this with @voellm. We are going to fix this issue (and make a breaking change) for the next release. (It's a p0 for the next release.)

Expected code change should be simple (search and replace), the more time consuming part is testing. I'd budget about 2 days on this. Let me or Yanting know once you are done, we'd be happy to CR. Thanks!

**Comment by noahl** [comment]
This is fixed by #581
