### ISSUE TITLE
Adding better error handling for mismatched CLI versions with PKB

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#521]
A couple of users have been hit by unmatched PKB and CLI.

Here is what I propose we do:

have PKB check the version of the CLI and error+exit if it has not been verified to work.
have a flag to turn the error+exit into a warning
The error+exit message should include the following:

A clear message on why the benchmarker exited. No exception stacks as the message.
A message on how to get the CLI version (eg: /npm install azure-cli#0.9.3 -g)
A message on how to override the error+exit using the flag "--ignore_cli_version" for example.
This should be a quick feature... and marking it P0 because it has been a pain point more than once.

(related issue - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/469)

**Comment by skschneider** [comment]
#958 and #967 address this.
