### ISSUE TITLE
Write a comprehensive guide to using configs

### ISSUE THREAD

**Issue by ehankland** [GoogleCloudPlatform/PerfKitBenchmarker#525]
Some config information has been included in the README, but we should have a second document that has everything that someone might want to know about using configs.

**Comment by voellm** [comment]
This should be on the Wikipages and the basics mentioned in the README.md

On Fri, Oct 9, 2015 at 2:37 PM, ehankland <notifications@github.com> wrote:

> Some config information has been included in the README, but we should
> have a second document that has everything that someone might want to know
> about using configs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/525>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by ehankland** [comment]
The guide to configs should also explain benchmark specific flags and how to specify them in configs

**Comment by cmccoy** [comment]
I'm planning to start the release tomorrow. Any chance of getting a start on this by then? At minimum we should document incompatible changes.

**Comment by ehankland** [comment]
I'm working on it now. I need to double check, but I think the only real breaking change was the move from --zones to --zone.

**Comment by ehankland** [comment]
Not done, but here's a start: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/PerfkitBenchmarker-Configurations

**Comment by cmccoy** [comment]
Nice. Could you add some examples and links wherever there's a "see python class x"?

**Comment by voellm** [comment]
Cool... I added it to the "how to's / FAQ" here ...
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/FAQ

You can also link the external design doc here -
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/FAQ

On Fri, Oct 23, 2015 at 10:07 AM, Connor McCoy <notifications@github.com>
wrote:

> Nice. Could you add some examples and links wherever there's a "see python
> class x"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/525#issuecomment-150635292>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by noahl** [comment]
I took a look at the wiki page above and I see a description of configs and several examples. Can we close this issue, or is there more to do?

**Comment by noahl** [comment]
I just talked with Eric. We can always expand our documentation, but we already have a good amount up. I'm marking this as complete. If anything is missing from the docs, we should file specific issues about the missing pieces.
