### ISSUE TITLE
Cleanup phase is not executed when running with --parallelism flag

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [GoogleCloudPlatform/PerfKitBenchmarker#529]
Run at least two benchmarks in parallel (using --parallelism flag). Interrupt the execution with Ctrl + C. Cleanup phase is not triggered at all.

**Comment by voellm** [comment]
Skyler - Can you look into this?

**Comment by skschneider** [comment]
Off the bat, I'd suspect that the KeyboardInterrupt is being caught by the main thread's RunThreaded that it uses to launch all the other threads that run benchmarks, whereas when running single-threaded it would be caught by the more general exception handler that makes sure Cleanup is executed if there's any exception during a benchmark's execution. This has probably been the behavior for a long time. Solution would probably be to add functionality to RunThreaded to handle KeyboardInterrupt. I'll look into it later this week.

**Comment by skschneider** [comment]
Ideally, we'd want Ctrl + C to trigger the cleanup behavior in benchmarks and to stop scheduling new benchmarks, so I considered if it was possible to get the main thread to have the benchmark threads raise a KeyboardInterrupt. There does exist an API PyThreadState_SetAsyncExc that could do this, but it looks like it can have unpredictable side effects depending on what the worker thread is doing. Alternatively, we could switch the call of RunThreaded into a RunParallelProcesses. That currently uses a ProcessPoolExecutor, which also reportedly has problems with interrupt signal handling, but there does exist a way to launch worker processes and control interrupt signals: http://noswap.com/blog/python-multiprocessing-keyboardinterrupt.

I would like if someone more experienced in Python weighed in on this one. I don't think there's a convenient model for redesigning the benchmarks themselves to poll for problems, and between the thread-based injected exception solution and process-based signal solution, I'm inclined toward a process approach with a modified RunParallelProcesses.

**Comment by voellm** [comment]
@skschneider  @mateusz-blaszkowski What is the next step here?  This is marked as a P0 bug so I'd like to either downgrade because its not important or work on a fix.

Thanks!

**Comment by skschneider** [comment]
Spoke with cmccoy. We're agreed that replacing the call to RunThreaded with RunParallelProcesses and then enhancing RunParallelProcesses is a good way to go. I'll work on that PR.

**Comment by skschneider** [comment]
Working on this now and almost done with implementation but need some more time for testing everything and then iterating with reviews. May not make it into the current release but will definitely be in by the release after that.

**Comment by skschneider** [comment]
The current plan has changed to removing the --parallelism flag. Discussions welcome on issue #616.

**Comment by skschneider** [comment]
--parallelism flag has been removed.
