### ISSUE TITLE
Benchmark configurations that make use of Rackspace's Block Storage service do not work

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#533]
Recently, there have been several changes in the OpenStack libraries, where block storage volume support has been deprecated and removed from the Nova client library. Since the current Rackspace provider implementation in PKB depends on Nova, this means it breaks all the volume operations.

Whenever a benchmark configuration that tries to use Rackspace Block Storage volumes as scratch disk will print the following error:
```bash
WARNING: Command volume-create is deprecated and will be removed after Nova 13.0.0 is released. Use python-cinderclient or openstackclient instead.
ERROR (EndpointNotFound):
```
To properly fix this issue, the Rackspace provider implementation has to move to the official [Rackspace CLI](https://developer.rackspace.com/docs/rack-cli/) or make use of Cinder client directly.

**Comment by meteorfox** [comment]
@cmccoy Please assign to me

**Comment by cmccoy** [comment]
Done - thanks!

**Comment by voellm** [comment]
Ping ... is this still and open issue not that the disk refactor is in?

**Comment by meteorfox** [comment]
@voellm Yes, this is still an issue. It's not related to the disk refactor. Benchmarks that make use of remote volumes are not working, a temporary workaround is to use an older Nova client, instead of installing latest with `pip`. I expect something similar to happen soon to the OpenStack provider bindings as well since we are using the `python-novaclient` library which has deprecated the same volume operations.

As for the Rackspace provider, we want to move it to use our official CLI instead of OpenStack's. That way we can lower the risks of similar problems in the future, with the extra bonus that the CLI client is actually more performant for both speed and footprint, it can return JSON output which will simplify our bindings, and is much easier to install than Nova CLI since the `rack` CLI is just a Go static binary.

I've a local branch in my laptop with a semi-working implementation that uses the new CLI, but I haven't had the time to finish it.

**Comment by meteorfox** [comment]
Closing #844 fixed this.
