### ISSUE TITLE
Cloudsuite Web Search failure

### ISSUE THREAD

**Issue by ehankland** [GoogleCloudPlatform/PerfKitBenchmarker#535]
I recently tried running cloudsuite_websearch and got this error:
```
RemoteCommandError: Got non-zero return code (1) executing export FABAN_HOME=/tmp/pkb/faban && java -classpath $FABAN_HOME/lib/fabanagents.jar:$FABAN_HOME/lib/fabancommon.jar:$FABAN_HOME/lib/fabandriver.jar:$JAVA_HOME/lib/tools.jar:$FABAN_HOME/search/build/lib/search.jar -Xmx2g -Xms2g -Djava.security.policy=/tmp/pkb/faban/search/config/security/driver.policy -Dbenchmark.config=/tmp/pkb/faban/search/deploy/run.xml com.sun.faban.driver.engine.MasterImpl
Full command: ssh -A -p 22 perfkit@104.197.53.161 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/run_cb3b806e/perfkitbenchmarker_keyfile export FABAN_HOME=/tmp/pkb/faban && java -classpath $FABAN_HOME/lib/fabanagents.jar:$FABAN_HOME/lib/fabancommon.jar:$FABAN_HOME/lib/fabandriver.jar:$JAVA_HOME/lib/tools.jar:$FABAN_HOME/search/build/lib/search.jar -Xmx2g -Xms2g -Djava.security.policy=/tmp/pkb/faban/search/config/security/driver.policy -Dbenchmark.config=/tmp/pkb/faban/search/deploy/run.xml com.sun.faban.driver.engine.MasterImpl
STDOUT: STDERR: Warning: Permanently added '104.197.53.161' (ECDSA) to the list of known hosts.
Oct 13, 2015 5:39:58 PM com.sun.faban.driver.engine.MasterImpl runBenchmark
INFO: RunID for this run is : 1
Oct 13, 2015 5:39:58 PM com.sun.faban.driver.engine.MasterImpl runBenchmark
INFO: Output directory for this run is : /tmp/pkb/outputFaban/1
Oct 13, 2015 5:39:59 PM com.sun.faban.driver.engine.MasterImpl configure
WARNING: Cannot find SearchDriverAgents. Not starting SearchDriver.
Oct 13, 2015 5:39:59 PM com.sun.faban.driver.util.Timer idleTimerCheck
INFO: SearchDriverAgent[0]: Performing idle timer check
Oct 13, 2015 5:39:59 PM com.sun.faban.driver.util.Timer idleTimerCheck
INFO: SearchDriverAgent[0]: Idle timer characteristics:
Accuracy=3,
min. invocation cost=83,
med. invocation cost (math)=103.0,
med. invocation cost (phys)=103,
avg. invocation cost=118.5895,
max. invocation cost=14078,
variance of invocation cost=167701.96138974998.
Oct 13, 2015 5:40:02 PM com.sun.faban.driver.engine.AgentImpl run
INFO: SearchDriverAgent[0]: Successfully started 50 driver threads.
Oct 13, 2015 5:40:02 PM com.sun.faban.driver.engine.MasterImpl executeRun
INFO: Started all threads; run commences in 2998 ms
Oct 13, 2015 5:40:09 PM sample.searchdriver.SearchDriver doGet
SEVERE: ERROR!!!!!!!!!!!!!!!

Oct 13, 2015 5:40:09 PM sample.searchdriver.SearchDriver doGet
SEVERE: ERROR!!!!!!!!!!!!!!!
```
The severe error repeated a bunch and then I got this:
```
WARNING: SearchDriverAgent[0]: Killing benchmark run
Oct 13, 2015 5:40:11 PM com.sun.faban.driver.engine.AgentThread logError
WARNING: SearchDriverAgent[0].24.doGet: java.lang.RuntimeException: Sleep interrupted. Run terminating.
Note: Error not counted in result.
Either transaction start or end time is not within steady state.
java.lang.RuntimeException: java.lang.RuntimeException: Sleep interrupted. Run terminating.
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1243)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2727)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:477)
	at com.sun.faban.driver.transport.sunhttp.SunHttpTransport.readURL(SunHttpTransport.java:177)
	at com.sun.faban.driver.transport.sunhttp.SunHttpTransport.readURL(SunHttpTransport.java:191)
	at com.sun.faban.driver.transport.sunhttp.SunHttpTransport.readURL(SunHttpTransport.java:217)
	at sample.searchdriver.SearchDriver.doGet(SearchDriver.java:189)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.faban.driver.engine.TimeThread.doRun(TimeThread.java:169)
	at com.sun.faban.driver.engine.AgentThread.run(AgentThread.java:202)
Caused by: java.lang.RuntimeException: Sleep interrupted. Run terminating.
	at com.sun.faban.driver.util.Timer.wakeupAt(Timer.java:405)
	at com.sun.faban.driver.engine.DriverContext.recordStartTime(DriverContext.java:599)
	at com.sun.faban.driver.transport.util.TimedSocket.connect(TimedSocket.java:289)
	at java.net.Socket.connect(Socket.java:528)
	at com.sun.faban.driver.transport.sunhttp.HttpClient.doConnect(HttpClient.java:182)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at com.sun.faban.driver.transport.sunhttp.HttpClient.<init>(HttpClient.java:130)
	at com.sun.faban.driver.transport.sunhttp.HttpClient.New(HttpClient.java:111)
	at com.sun.faban.driver.transport.sunhttp.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:99)
	at com.sun.faban.driver.transport.sunhttp.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:41)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	... 9 more
```
Some variation of that repeated a bunch, and then the benchmark eventually failed.

**Comment by ehankland** [comment]
@Vukasin92 Any idea why this might have happened?

The run was on GCP - I still have the log so I should be able to give more details if you want them.

**Comment by Vukasin92** [comment]
Have you changed any of the default parameters? Also, on which machine type are you running it?
It might be one of few things: Java heap size on the client or on the server size is too big. Or scale (number of client users per machine*client machines) produces too much workload for the machine the server is on, or it hasn't ramped up enough (Sometimes increasing warm up time can't help because it still hasn't cached index into memory, but instead it first needs to be run with low workload before you increase it). It might just be that the server has low memory and can't fit whole index into it, which is why it has big latencies during accessing files on disk, which decreases the number of users it can serve.
Can you reproduce the error? The best way to investigate this is to run the benchmark in stages, and then after the prepare phase to ssh into machines and see if everything is running, run the benchmark, ssh again and see what has happened, and then maybe execute commands from perfkit through the ssh console(either to restart the Solr server, or to monitor if all the processes are starting correctly on the clients). 
The problem is that those parameters are really machine dependent and there is no way to make defaults work on every machine. But I tested them on n1-standard-1. Ideally, the user should tune them to their own machine capabillites before making the results.
Also, if you want to make sure that the problem is tuning and not the code itself, before anything of this, just try running it with scale set to 1 and java heap spaces set to 1g - that shouldn't break on any machine types.

**Comment by ehankland** [comment]
I was running with the defaults on an n1-standard-8. 

I'll try to see if I always get the same error - I think I only tried twice yesterday. If it does produce the same error, I'll try playing with the scale to see if that fixes it.

**Comment by Vukasin92** [comment]
Hmm, doesn't make sense then. Can you try running prepare stage, then ssh into both machines and type 'jps'. The output on the client machine should display one process named Bootstrap, and the output on the server machine should display process named jar. In the run stage processes RegistryImpl, MasterImpl and AgentImpl should also start on the client.

Which OS are you using? I used default - think it is debian. Might be that JAVA_PATH is not correct - I don't think so but still worth checking.

**Comment by ehankland** [comment]
Hmm I wasn't able to reproduce it today, even using exactly the same flags. If I see this again I'll reopen.

**Comment by xwzyb** [comment]
@Vukasin92 
Hi, if I want to set the all clients number very big to stress the server as much as possible, what I can do to set the server configirations to avoid the server error.
Thank you very much.

**Comment by Vukasin92** [comment]
What have you tried?

Could it be that you already stressed server too much? Try increasing client scale gradually, and see if latency starts to prolong. Once it starts to prolong, it might increase exponentially, hence server crashing once it becomes too big, and too many requests accumulate. Also, I'm not sure if server is the one who crashed, as you haven't posted anything related to error. It could be that it is client side issue - if you increase scale, make sure you increase number of client VMs also. In the end, the best advice for finding out what is really going on is to run benchmark in stages, and SSH into machines to see what is really going on, which processes are still alive after benchmark, before cleanup.

Note that I haven't been maintaining this code for a while, so my memory isn't fresh, and it may have changed. I'm adding @javpicorel, maybe he can help.

**Comment by maggiejiao** [comment]
@Vukasin92 
Hi, I've met the same issue when running the benchmark on ubuntu1604 image and with n1-standard-1 VM. The test result is very flaky and fails in 4/9 tests even with scale set to 1 and java heap spaces set to 1g and with larger machine shape n1-standard-8. Any ideas about that?

Apr 11, 2017 4:17:34 AM sample.searchdriver.SearchDriver doGet
SEVERE: ERROR!

Apr 11, 2017 4:17:34 AM com.sun.faban.driver.engine.AgentThread validateTimeCompletion
SEVERE: SearchDriverAgent[0].48.doGet: Transport incomplete! Please ensure transport exception is thrown from operation.
Apr 11, 2017 4:17:34 AM com.sun.faban.driver.engine.AgentThread run
SEVERE: SearchDriverAgent[0].48: SearchDriverAgent[0].48.doGet: Transport incomplete! Please ensure transport exception is thrown from operation.
com.sun.faban.driver.FatalException: SearchDriverAgent[0].48.doGet: Transport incomplete! Please ensure transport exception is thrown from operation.
	at com.sun.faban.driver.engine.AgentThread.validateTimeCompletion(AgentThread.java:532)
	at com.sun.faban.driver.engine.TimeThread.doRun(TimeThread.java:173)
	at com.sun.faban.driver.engine.AgentThread.run(AgentThread.java:202)

Apr 11, 2017 4:17:34 AM com.sun.faban.driver.engine.MasterImpl$2 run
SEVERE: Run aborted. Master terminating!
cat: /usr/src/outputFaban/1/summary.xml: No such file or directory

**Comment by Vukasin92** [comment]
Hi Mengjiao,

Sorry for replying late. Unfortunately, I cannot help you, as I've been completely detached from this project for 2 years already. The comments above are the troubleshooting guide even I would now have to use, since I don't remember much. Hope that someone will take it from here.
