### ISSUE TITLE
Consider moving the SPEC CPU runs to use LongRunningRemoteCommand

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#56]
For commands that take hours to days there are issues that can arise when connection failures happen.  Today SPEC is running on an active connection vs HPCC which is using nohup an logging out.

We should consider moving    

vm.RemoteCommand('cd %s; . ./shrc; ./bin/relocate; . ./shrc; rm -rf result; '
                   'runspec --config=linux64-x64-gcc47.cfg --tune=base '
                   '--size=ref --noreportable -rate %s %s '
                   % (vm.spec_dir, num_cpus, FLAGS.benchmark_subset))

To use the vm.LongRunningRemoteCommand.

**Comment by cmccoy** [comment]
This was done.
