### ISSUE TITLE
Possibility to run the same type of benchmark in one run.

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [GoogleCloudPlatform/PerfKitBenchmarker#561]
Currently when I pass the same benchmark twice (like `--benchmarks=ping,ping`), the benchmarker will create a _set_ from the provided benchmarks list. This way I am not able to run the same type of benchmark in one run which would be useful when i.e. running the benchmarks in parallel.

**Comment by cmccoy** [comment]
@ehankland is working on that in #546 - perhaps you could see if that implementation suits your needs?

**Comment by ehankland** [comment]
That functionality is already in master - (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/546 just lets you specify different flags for each run). You can use a configuration file or specify it on the command line.
Config file approach:
`./pkb.py --benchmark_config_file=ping.yml`
[ping.yml]
```
benchmarks:
  - ping: null
  - ping: null
```
Or the equivalent on the command line:
`./pkb.py --config_override="benchmarks=[{ping: null}, {ping: null}]"`

**Comment by mateusz-blaszkowski** [comment]
Ok, that's great. Tomorrow I will take a look at this. Thanks

**Comment by voellm** [comment]
If this works for you please close the issue.  THanks!

**Comment by mateusz-blaszkowski** [comment]
Verified - works for me. I'm closing the issue.
