### ISSUE TITLE
Link to PIP installation is broken on readme.md

### ISSUE THREAD

**Issue by ivansmf** [GoogleCloudPlatform/PerfKitBenchmarker#568]
It is http://pip.readthedocs.org/en/index/stable/index/index/index/index/index/index/index/index/

It should be http://pip.readthedocs.org/en/stable/installing/

**Comment by voellm** [comment]
Fixed https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/cb0faaffb6de299a97545e7fda4e064b7c4bd547
