### ISSUE TITLE
Documentation for the result output

### ISSUE THREAD

**Issue by syed** [GoogleCloudPlatform/PerfKitBenchmarker#570]
I don't know if this is a good place to ask questions but the community email doesn't work. 

Is there any documentation about the result format? I was planning to use PerfKitExplorer but in its current state I find it too complicated. I might end up rolling my own simple dashboard. If there is any documentation that I can refer to for the output format that would be really awesome.

**Comment by voellm** [comment]
Added Joe and Klaus that can help you.

There are a set of dashboard checked in for PKB data here -
https://github.com/GoogleCloudPlatform/PerfKitExplorer/tree/master/data/dashboards


On Tue, Oct 20, 2015 at 2:26 PM, Syed Mushtaq Ahmed <
notifications@github.com> wrote:

> I don't know if this is a good place to ask questions but the community
> email doesn't work.
>
> Is there any documentation about the result format? I was planning to use
> PerfKitExplorer but in its current state I find it too complicated. I might
> end up rolling my own simple dashboard. If there is any documentation that
> I can refer to for the output format that would be really awesome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/570>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by voellm** [comment]
@Syed - Did you need more help on this?  If so feel free to ping me directly at voellm@google.com and I'll loop in @jmuharsky and @klausw  people to help you.

**Comment by syed** [comment]
Thanks @voellm, I think I understand the format a bit better after reading the code.
