### ISSUE TITLE
Passing project (or other param) to Network and Disk class when using *VmSpec

### ISSUE THREAD

**Issue by syed** [GoogleCloudPlatform/PerfKitBenchmarker#572]
the `project` field is optional in Cloudstack. Currently I am checking the `flags` to get its value but I wanted to add that as a `vm_spec` so that I can run the same benchmark on multiple clouds using the config. However, I don't find any way to pass `project` to the network or disk class apart from the global flags.

**Comment by syed** [comment]
I checked and it seems that I can modify my `Disk` class as that gets created in my `VM` class. However, network is not. Can we add a callback similar to `CreateScratchDisk()` for network?

**Comment by ehankland** [comment]
Yes we can - I'll work on a fix.

**Comment by ehankland** [comment]
This is possible now that the above PR is merged. You need to define a NetworkSpec object and implement  _GetKeyFromNetworkSpec as well as _GetNetworkSpecFromVm. If you need help, let me know.
