### ISSUE TITLE
VM "benchmark" metadata contains UID, rather than benchmark name

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#578]
As of #510. I think this should still be the benchmark name, rather than a (locally) unique name + index.

**Comment by ehankland** [comment]
The UID is the benchmark name + a number - just to confirm you are you saying you want only the benchmark name and no number?

**Comment by cmccoy** [comment]
Right.

**Comment by ehankland** [comment]
Looks like @skschneider is adding the benchmark name back to the spec in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/597/files - after this change, it should just be a one line change

**Comment by skschneider** [comment]
This might already solve the problem you're describing:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/597/files#diff-912d79fe2121b7a46a28c3792740162dR430

**Comment by ehankland** [comment]
Yep - that should do it - sorry I didn't check if you changed the metadata as part of that PR

**Comment by skschneider** [comment]
Fixed by #615.
