### ISSUE TITLE
Add OpenStack as a provider

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#58]

**Comment by chrisjackson1982** [comment]
+1 to this request please.

**Comment by alvico** [comment]
Doesn't tempest and rally tackle this already?

**Comment by voellm** [comment]
@alvico - What do me mean by tackle?  Do you have links so I can understand
what these are?

On Wed, Feb 18, 2015 at 3:57 AM, alvico <notifications@github.com> wrote:

> Doesn't tempest and rally tackle this already?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/58#issuecomment-74852889>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by alvico** [comment]
@voellm sure: Openstack tempest is the oficial Openstack testing suit: https://github.com/openstack/tempest/tree/master/tempest and Rally is kind of benchmarking tool for openstack as well https://wiki.openstack.org/wiki/Rally

**Comment by voellm** [comment]
Ok these look related but PerfKit is focused on performance only -and-
making it so workloads run on any Platform for easy comparisons.

./pkb.py --cloud=OpenStack --benchmarks=iperf

should run just as easily as

./pkb.py --cloud=GCP --benchmarks=iperf

We might be able to use some of the parts from tempest and or Rally to do
the automation.

Thanks for the pointers.

On Wed, Feb 18, 2015 at 4:20 AM, alvico <notifications@github.com> wrote:

> @voellm <https://github.com/voellm> sure: Openstack tempest is the
> oficial Openstack testing suit:
> https://github.com/openstack/tempest/tree/master/tempest and Rally is
> kind of benchmarking tool for openstack as well
> https://wiki.openstack.org/wiki/Rally
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/58#issuecomment-74855500>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by alvico** [comment]
Running workloads on different platforms it's very interesting. Probably you should just use https://libcloud.apache.org/ for easy integration with any cloud provider, instead of custom drivers.

**Comment by voellm** [comment]
We looked at libcloud and its pretty cool.  If you are really interested we
surveyed about 50+ such libs in various forms.  A design point we've stuck
with however is to use the CLI.  With the CLI you get a full audit log that
can be copied and pasted to repro.  It also aids developers when tuning
workloads or debugging.

If you want the background on this check out the community meeting slides
here -
https://docs.google.com/presentation/d/1nRO9Cfn6ADX3ueSdvCiPP3fk03f7rDDHdzNvofd2zfs/edit#slide=id.g432b0946a_00


On Wed, Feb 18, 2015 at 3:24 PM, alvico <notifications@github.com> wrote:

> Running workloads on different platforms it's very interesting. Probably
> you should just use https://libcloud.apache.org/ for easy integration
> with any cloud provider, instead of custom drivers.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/58#issuecomment-74871209>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by alvico** [comment]
Awesome, thanks!!

**Comment by meteorfox** [comment]
Sorry, to bump in. I just wanted to add to the conversation, since I'm a contributor to both projects (PerfKit, and Rally), and I'm using Rally to run several workloads against some OpentStack private clouds.  As far as I am aware, tempest is more of a unit test framework, than a performance framework, so I won't compare it to any of these other two.

I'd say as it stands right now, and besides the point that Rally is only for OpenStack, Rally is currently very good at control-plane benchmarks (APIs, etc), such as measuring time to boot and delete instances, creating/deleting volumes, uploading images, etc, while it is still somewhat lacking at data-plane benchmarks (iperf, unixbench, spec*, etc), which I find is where PerfKit excels at.

Rally does have in its roadmap[1] to improve data-plane benchmarking, and I know there's already some support built-in for it.  Also, I believe that PerfKit also wants to improve at including more of these control-plane scenarios.

The way I see it, for what is worth, is that they complement each other. PerfKit has to take a common denominator since it's built to run against multiple cloud providers, and might lack the coverage of some control-plane benchmarks that we see in Rally, but it's awesome at data-plane benchmarks. The fact remains is that Rally is, still today and for the short term future, only for OpenStack. 

[1] https://docs.google.com/spreadsheets/d/16DXpfbqvlzMFaqaXAcJsBzzpowb_XpymaK2aFY2gA2g/edit#gid=0
[2] Up to date docs for Rally: http://rally.readthedocs.org/en/latest/

**Comment by alvico** [comment]
I definitely will not call tempest unit testing... right now it's the basis for testing and QAing openstack deployments, any way. I think we need more open frameworks for cloud testing no matter what so we can establish proper metrics beyond marketing data, I'm totally in favour of more initiatives on that direction. 

cheers

**Comment by meteorfox** [comment]
+1000 this: 
" I think we need more open frameworks for cloud testing no matter what so we can establish proper metrics beyond marketing data, ..."

**Comment by rmrf** [comment]
+1, I need this for sure.

**Comment by kivio** [comment]
Hi guys, I'm working on that! I think simple version of that can be done to end of next week.

**Comment by alvico** [comment]
Nice!

**Comment by voellm** [comment]
klvio - Can you please assign the issue to yourself?  I may need to add you to an access group in GitHub so if it does not work please let me know.

In the meantime to indicate it is being worked I assigned it to me as a proxy.

One last step... to take the code into dev/master please sign the CLA here as per the CONTRIBUTING.md file - https://cla.developers.google.com/about/google-individual?csw=1

Many thanks for contributing!

**Comment by voellm** [comment]
Marcin - It looks like you work at Intel (?) which has signed the CLA so you should be able to as well.

**Comment by kivio** [comment]
@voellm i don't have option to assign this issue to me. Yes, I'm working in Intel.

**Comment by voellm** [comment]
Marcin - I'll get you added to a collaborators list which will give you
some extra permissions to the project.  That will allow me to assign the
feature bug to you properly.  Please accept the PerfKit-Collaborators@
invite when you see it.

On Mon, Mar 23, 2015 at 1:31 AM, Marcin Karkocha <notifications@github.com>
wrote:

> @voellm <https://github.com/voellm> i don't have option to assign this
> issue to me. Yes, I'm working in Intel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/58#issuecomment-84883904>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by voellm** [comment]
Marcin - Thanks for doing this.  I've assigned it to you not that we have the right permissions in place.  if you have an idea of when it might land you can mark the milestone now as well.

**Comment by ytsarev** [comment]
+1 for this feature. 

@kivio do you already have the code ? i'm willing to test it

**Comment by kivio** [comment]
@ytsarev Yes, i have part of code in my fork on branch openstack-integration. This code is little old but i plan to rebase it to new version of dev branch in short time. Currently i have proper runned 16 tests on my OpenStack setup.

**Comment by voellm** [comment]
Cool. Thanks for working on this. We have DigitalOcean pretty close to
check-in a branch off dev (done by klausw) and Rackspace has their provider
pretty close as well.

If you need help please feel free to ping me.

**Comment by kivio** [comment]
@voellm currently i'm going for honeymoon vacations for 4 weeks @mateusz-blaszkowski and @emaeliena will be my backup. Please add their to CLA

**Comment by voellm** [comment]
Time to close this issue?

**Comment by kivio** [comment]
I think yes. I have few fixes for that driver but it's separate subject
