### ISSUE TITLE
Q: Perfkit target users & comparison with CloudBench

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [GoogleCloudPlatform/PerfKitBenchmarker#606]
It's more like a question than an issue. We've just wondered if you had some discussions with cloud providers who wanted to use Perfkit in order to white-box test their own clouds. Was anyone interested in using Perfkit for e.g. stressing their private clouds to see what would be the best SW/HW configuration for the clouds?

Btw. Did you have a chance to look at the CloudBench project (https://github.com/ibmcb/cbtool)? If so, could you briefly explain what is the difference between Perfkit and CloudBench? After the quick glance it looks like they offer similar functionalities but Perfkit is growing much more rapidly.

Thanks!

**Comment by voellm** [comment]
Mateusz - It looks like that project has been around for a year.  Perhaps we should ask them to join us.  I'll open a discussion issue with them.

**Comment by voellm** [comment]
If you have contacts for contributors there please sent an introduction.  As a proxy I opened an issue - https://github.com/ibmcb/cbtool/issues/85

**Comment by mateusz-blaszkowski** [comment]
@voellm I don't have unfortunately. Thanks for opening the issue there

**Comment by voellm** [comment]
No follow-up from that community so I'm going to close this out.  Looks that that project is pretty stale.

**Comment by jtaleric** [comment]
The project is not "stale" -- what gave you that impression voellm? https://github.com/ibmcb/cbtool/commit/fc6395e159e0e10f21248473b4d709e7816995d2

**Comment by voellm** [comment]
@jtaleric - Thanks for the ping back.  Stale because there was no engagement on this issue - https://github.com/ibmcb/cbtool/issues/85

If you have time I'd be happy to chat about the goals of PKB and find out more about cbtool.

**Comment by hinesmr** [comment]
@voellm Cloudbench is 4 years old and not at all stale. We have a mailing list and active contributors as well as a set of fully documented wiki pages. I recommend you start there.
