### ISSUE TITLE
openstack: Benchmarks with scratch disk fail with AttributeError

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#619]
Whenever I try to execute a benchmark that makes use of a scratch disk using the OpenStack provider I get the following error:

```
perfkitbenchmarker.errors.ThreadException: The following exceptions occurred during threaded execution:
Exception occurred while calling PrepareVm(10.50.48.24):
Traceback (most recent call last):
  File "/opt/perkitbenchmarker_c4c250732399afef7a56f6da2704f3741e1aca0e/perfkitbenchmarker/vm_util.py", line 227, in _ExecuteThreadCa
ll
    queue.put(ThreadCallResult(call_id, target(*args, **kwargs), None))
  File "/opt/perkitbenchmarker_c4c250732399afef7a56f6da2704f3741e1aca0e/perfkitbenchmarker/benchmark_spec.py", line 381, in PrepareVm
    vm.CreateScratchDisk(disk_spec)
  File "/opt/perkitbenchmarker_c4c250732399afef7a56f6da2704f3741e1aca0e/perfkitbenchmarker/openstack/os_virtual_machine.py", line 185
, in CreateScratchDisk
    self.project)
AttributeError: 'DebianBasedOpenStackVirtualMachine' object has no attribute 'project'
```

Inspecting the code in `os_virtual_machine.py`, it seems the attribute `self.project` is never set.

**Comment by meteorfox** [comment]
@kivio @mateusz-blaszkowski PTAL, I can fix it, but I don't know what does the attribute self.project is supposed to be. Thanks

**Comment by kivio** [comment]
I was looking for this attribute in driver code and i think it is from base class of VirtualMachine.
You can find it in BaseVirtualMachine doc.

It is not used currently in my driver. I think we can remove it.

**Comment by kivio** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/622

**Comment by meteorfox** [comment]
Verified.
