### ISSUE TITLE
Require a disk_spec to provision a disk

### ISSUE THREAD

**Issue by noahl** [GoogleCloudPlatform/PerfKitBenchmarker#631]
Right now it is possible to choose a machine type that comes with a built-in disk and use that disk as a block device without ever creating a disk spec. It is also possible to do the same thing on GCP by passing the `--gcp_num_local_ssds` flag without also passing `--data_disk_type=local`. We should enforce that local disks always get disk specs.

**Comment by stfeng** [comment]
Let's start with thinking about these questions: 1) what are the current ways of "creating" and using local SSD/HDD on the major providers? 2) what are the desirable ways of doing such? 

Writing down specific command examples will help a lot.

**Comment by noahl** [comment]
After learning a lot more about PKB's disk creation mechanism, I think this is not actually an issue. While you can allocate a disk with `--gcp_num_local_ssds`, disk specs are actually created based on the benchmark spec, not the command-line flags passed. Closing this bug.
