### ISSUE TITLE
Maintain lists of supported benchmarks for each cloud provider

### ISSUE THREAD

**Issue by hildrum** [GoogleCloudPlatform/PerfKitBenchmarker#671]
Each cloud provider should maintain a list of benchmarks supported.  

When a run of PerfKit Benchmarker is started, only the benchmarks supported by the provider will be run.  The skipped benchmarks will be reported.  

I don't currently see a natural place for this in the provider-specific files, so perhaps a new properties.py in the provider directory could contain this information.

**Comment by voellm** [comment]
@mateusz-blaszkowski - Is there a set of "known" working benchmarks for OpenStack/Kubernetes?   Any not working as intended?

@syed -  Is there a set of "known" working benchmarks for CloudStack?   Any not working as intended?

@hicrazyboy  -  Is there a set of "known" working benchmarks for AliCloud?   Any not working as intended?

@meteorfox - Is there a set of "known" working benchmarks for Rackspace?   Any not working as intended?

**Comment by mateusz-blaszkowski** [comment]
There is a `kubernetes_set` with a list of benchmarks that worked well on K8S:

```
    'kubernetes_set': {
        MESSAGE: 'Kubernetes benchmark set.',
        BENCHMARK_LIST: ['block_storage_workload', 'cassandra_ycsb',
                         'cassandra_stress', 'cluster_boot', 'fio', 'iperf',
                         'mesh_network', 'mongodb_ycsb', 'netperf', 'redis',
                         'sysbench_oltp']
    }
```

Unfortunately I can't verify which benchmarks were working on Openstack cloud. @kivio - do you have a list of working benchmarks for OS?

**Comment by kivio** [comment]
@mateusz-blaszkowski @voellm - i have list of working benchmarks but from release 18.x, I haven't currently environment to test newest version of PKB

**Comment by voellm** [comment]
We can go with "it works" until proven not to or err on know is known.  Any
preference?

**Comment by kivio** [comment]
@voellm  Ok, we can assume "it works" for all. I want to test it in nearby future.

**Comment by kivio** [comment]
Another thing - OpenStack driver is currently implemented and tested just for Ubuntu image.

**Comment by voellm** [comment]
With the pull request complete is this feature complete?  If so please close.

**Comment by hildrum** [comment]
Closing, as it is complete.  Please reopen if something is missing.
