### ISSUE TITLE
PKB exits with status 0 even when all benchmarks fail

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#708]
It should exit with a non-zero exit code whenever any of the benchmarks specified failed to execute.

**Comment by mateusz-blaszkowski** [comment]
I'm sorry! - I've closed this by mistake while reading the issue. I just wanted to add that I had noticed this a day before the issue appeared ;) In our case we created the wrappers which execute the test in a loop with different parameters. I wanted to re-run the benchmark if it failed but I realized the return code is always 0. I'll be happy to verify the fix when it's ready!

**Comment by cmccoy** [comment]
@mateusz-blaszkowski  - no problem!
Fix in #713, if you want to test it out.

**Comment by mateusz-blaszkowski** [comment]
I've verified the fix works as expected, thanks!
