### ISSUE TITLE
Getting started page is trucated

### ISSUE THREAD

**Issue by Capstan** [GoogleCloudPlatform/PerfKitBenchmarker#711]
http://googlecloudplatform.github.io/PerfKitBenchmarker/getting-started#integration-testing terminates abruptly. If this is pulled from README.me, that looks fine, so maybe there's something odd about its excerpting?

**Comment by voellm** [comment]
Thanks for letting us know.

**Comment by voellm** [comment]
P0 = Will fix ASAP.

**Comment by yangsophia** [comment]
Good catch, there were some words left behind during copy paste... Sorry about that. It is fixed now. Close by 7fe557883d959fafc1b4b7c69ffc6cb53e10a0c6
