### ISSUE TITLE
object_storage_service benchmark quantiles should be symmetrical

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/PerfKitBenchmarker#718]
The summary output for object_storage_service lists p1, p5, p50, p90, p99 and p99.9, which is great for metrics where lower is better (e.g. latency) because you can see with good resolution how long the tail is, but for metrics where higher is better (e.g. throughput) there's less data around the "bad" side of the tail. Would be nice to have p0.1, p1, [p5,] p10, p50, p90, [p95,] p99, p99.9.

**Comment by voellm** [comment]
Would you like to take this on in terms of adding the metrics?  We can also do it.

**Comment by zbjornson** [comment]
I'm happy to do it. Will work on it today.
