### ISSUE TITLE
GCE Flags Error causing unit tests to fail

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#723]
I pulled the latest commits from master, and currently I'm getting 2 unit tests errors which is blocking my commits since I have the pre-commit hook setup.

Here's a link to stack traces:

https://gist.github.com/meteorfox/64934edbc07733a0ba53

**Comment by meteorfox** [comment]
According to git blame 

```
(pkb)carl6796@t450s:~/programming/github.com/GoogleCloudPlatform/PerfKitBenchmarker$ git blame -L110,115 /home/carl6796/programming/github.com/GoogleCloudPlatform/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py
85a34c9d (Skyler Schneider 2015-11-17 21:40:25 -0800 110)     self.flags['quiet'] = True
85a34c9d (Skyler Schneider 2015-11-17 21:40:25 -0800 111)     if resource.project is not None:
85a34c9d (Skyler Schneider 2015-11-17 21:40:25 -0800 112)       self.flags['project'] = resource.project
85a34c9d (Skyler Schneider 2015-11-17 21:40:25 -0800 113)     if hasattr(resource, 'zone'):
85a34c9d (Skyler Schneider 2015-11-17 21:40:25 -0800 114)       self.flags['zone'] = resource.zone
85a34c9d (Skyler Schneider 2015-11-17 21:40:25 -0800 115)     self.additional_flags.extend(FLAGS.additional_gcloud_flags)
```

It looks it comes from one of @skschneider commits, but it could be a side effect of another change.

Thanks ahead of time!

**Comment by skschneider** [comment]
This is likely because #695 was merged between the time I opened and submitted #675, and the tests weren't rerun. I will work on a fix.

**Comment by skschneider** [comment]
#724 has been submitted. tox and hooks/check-everything are clean on master.

**Comment by meteorfox** [comment]
Thanks!
