### ISSUE TITLE
Windows installation got a lot harder recently

### ISSUE THREAD

**Issue by noahl** [GoogleCloudPlatform/PerfKitBenchmarker#735]
Adding paramiko to the requirements.txt file means that we need to build pycrypto when installing dependencies, which means that the user needs Visual C++ installed to build PKB on Windows. We should either document this new requirement or change it. (paramiko is only required for AliCloud, and since we lazy-load providers, you don't actually need to install it unless you want to use AliCloud from Windows.)

**Comment by voellm** [comment]
Its only harder if you want to use Alicloud.  It is not impacted otherwise.  So that feature and the complexity go together.

There are lots of threads on StackOverflow on how to install paramiko on Windows.  Here is one such example - http://stackoverflow.com/questions/2964658/installing-paramiko-on-windows

**Comment by noahl** [comment]
The problem is that if you do 'pip install -r requirements.txt', it will automatically install paramiko. I had to figure out what the problem was and manually edit my requirements.txt to fix it, but I don't think that's reasonable for a non-PKB-developer. Ideally we would let you install PKB without paramiko and just complain if you tried to use Alicloud. I think it's doable.

**Comment by cmccoy** [comment]
Let's split out `requirements.txt` into core requirements (required to run PerfKitBenchmarker) and individual files for cloud providers with additional dependencies.

**Comment by cmccoy** [comment]
The default requirements.txt no longer introduces any dependencies that require a compiler toolchain.
