### ISSUE TITLE
object_storage_service consistency tests don't match perfdiag

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/PerfKitBenchmarker#739]
I'm trying to check that the object_storage_service benchmark's list-after-write consistency result is correct. It's reporting a surprisingly low consistency for GCS after 300 seconds (the timeout) -- between 78 and 82%, which also doesn't seem to (always) match up with the latency percentiles:

```
$ ./pkb.py --project=xxx --benchmarks=object_storage_service --machine_type=n1-standard-1 --object_storage_scenario=api_namespace
(...)
OBJECT_STORAGE_SERVICE:
  list-after-write consistency percentage       80.000000 na                            
  ...   
  list-after-write latency p50          1.131576 seconds                       
  ...
  list-after-write latency p95          1.242201 seconds                       
  list-after-write latency p99          1.242201 seconds                       
  list-after-write latency p99.9        1.242201 seconds                       
```

(I don't get how 99.9% of objects could be consistent by 1.24 seconds but only 80% are consistent. *edit* Sometimes p99 and p99.9 are 300 seconds.)

This appears to be the closest approximation to PKB using gsutil perfdiag:
```
gsutil perfdiag -t list -n 5000 -s 1 -k 100 gs://perfdiag562932
```
which is 5000x 1 byte objects using 100 threads, list-after-write and list-after-delete. (I know PKB deletes only a fraction of the objects in the list-after-delete test.) Result: 100% after 1st LAW (70 ms) and 100% after 5th LAD (140 ms).

The [PKB script](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/scripts/object_storage_api_tests.py#L387) for this test looks comparable to [perfdiag](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/perfdiag.py#L1024).

Am I misunderstanding the metrics, is this real, or is this a potential bug?

**Comment by voellm** [comment]
@stfengto comment more.

Perfdiag does not actually write or read data.  Hit the equivalent of
/dev/null.

**Comment by voellm** [comment]
I'm talking the remote end is like /dev/null.  Perfdiag does contact GCS
and send data to the service just it is never persisted.

**Comment by zbjornson** [comment]
Not quite following that comment, but can wait for @stfengto to comment more.

Also just figured out that "list-after-xxx consistency percentage" is not the *number* of files that are inconsistent, but the number of iterations that have *any* files inconsistently listed... I think.

**Comment by voellm** [comment]
Now that I have a real keyboard...

Sorry I created some confusion here.  Let me start with the "list after
write consistency".  The number is indeed the percentage of files vs number
of files.


On Tue, Dec 15, 2015 at 10:01 PM, Zach Bjornson <notifications@github.com>
wrote:

> Not quite following that comment, but can wait for @stfengto to comment
> more.
>
> Also just figured out that "list-after-xxx consistency percentage" is not
> the *number* of files that are inconsistent, but the number of iterations
> that have *any* files inconsistently listed... I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/739#issuecomment-165006425>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by noahl** [comment]
Fix the mention to @stfeng . He's on vacation, though, so I don't know when he'll be able to respond.

**Comment by stfeng** [comment]
@zbjornson 

Yes for this: ""list-after-xxx consistency percentage" is not the number of files that are inconsistent, but the number of iterations that have any files inconsistently listed"

Basically we write 5000 objects very quickly, and then do a list, if the provider returns all objects at the first try, we call it consistent, if anything is missing, we call it inconsistent. We repeat this 200 times per test run, and report the % of runs that we are able to get consistent list results at the first attempt.

The other question you had was about "list-after-write latency", it reports the latency of the list operation itself, the other metric "list-after-write inconsistency window" tells you how long we have to wait to get consistent results.

**Comment by zbjornson** [comment]
Thanks all, and thanks @stfeng for replying while on vacation.

Good to know that the criteria for "consistent" is based on the **first** try. That seems pretty stringent, and mostly explains why the number is lower than I'd expect.

**Comment by zbjornson** [comment]
Might be good to rename that to "list-after-write consistency on first LIST" and make the unit "%" instead of "na"... If you agree I can make a PR for that.

**Comment by voellm** [comment]
Name changes to metrics are a breaching change and the process is to have
both metrics for a period of time before removing the older metrics.

I am all for additional comments in the code.

**Comment by stfeng** [comment]
You are welcome! 

As to the metric names, the definition of a (strongly) consistent behavior is such that the first try must return all expected results. Therefore I believe the current metric name "list-after-write consistency" already implies the list must be the first operation, adding an additional word "first" would be redundant.

As to using the unit "%", I am on the fence here. since the name of the metrics already contains the world "percentage", then having this word again in unit would be a repeat, but I'm also open to change it to be more explicit.

**Comment by zbjornson** [comment]
Yea, but it doesn't say "strongly" :). No strong preference, and changing the unit was only to save space in the metric name if the metric name were to become longer. Alternatively, it would be great to start a wiki page explaining what the metrics do, or make the usage text more thorough (which is maybe what @voellm means). (No rush on this at all -- please enjoy your vacation!)
