### ISSUE TITLE
" sudo apt-get update" is called even when there is nothing to install

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#749]
It looks like VM's will " sudo apt-get update" even when there is nothing to install.  This is most notable on  the cluster_boot benchmark.

It seems like this should be deferred until and actual install is requested.

**Comment by voellm** [comment]
Maybe I'll take this one on.  The reason I opened it is I've seen a number of instances where boot stall because apt-get is failing.  Then either the benchmark fails or finished with a skewed value.

**Comment by cmccoy** [comment]
A skewed value for boot time? Updating packages isn't included in the boot time reported, though it of course affects end to end time.

**Comment by cmccoy** [comment]
If it's failing it's worth fixing soon. I decreased the priority because:

* AFAIK cluster boot is the only affected benchmark.
* Some providers don't bill exactly by the minute - GCP bills a minimum of 10, AWS in 1 hour increments, so we're not increasing cost in all situations.

I'm happy to fix.
