### ISSUE TITLE
Lucky #7 Community Meeting Feb 11th.

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#775]
Its that time again ... our next community meeting.  Since the last meeting we have hit "V1", added 3 new providers, disk improvements, new services, and a lot more we'll talk about.  

** The plan is to have the meeting Feb 11th.  This is when we first went public with alpha level code.

My asks:
- Who would you like to hear from at the community at the meeting?
- Self nominate topics.

Suggested topics:
- V2 - What major benchmarks to we want to address?
- What new services should we tackle?  Think Load Balancers, Pub/Sub services, etc.
- Scoring - I have a proposal to allow benchmark set based scoring.  So this is more about the mechanism of how we do it vs what a score should be.

Feel free to add to this bug or ping me voellm@google.com

**Comment by zbjornson** [comment]
Would love elastic load balancer and perhaps autoscaling benchmarks. Time to respond to traffic increases, maximum RPS, autoscaling latency perhaps.

**Comment by voellm** [comment]
Thanks to @zbjornson / @noahl / Javier for speaking.  Here is the slide deck which is also posted to the Wiki - https://docs.google.com/presentation/d/1B1jvWWh0ACaDv4ryEzLlH-KropXUNf6y4IGGjIL5uBo/edit#slide=id.g60dd38b59_1_0

**Comment by voellm** [comment]
And ... many thanks to @ivansmf  for hosting the meeting!
