### ISSUE TITLE
Separate synthetic_storage_workload benchmark into three benchmarks

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#78]
One each covering the logging, streaming, and database case.

**Comment by yuyantingzero** [comment]
I had a pull request(https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/195) awhile ago and decided to leave it as it is after talking to @voellm .
I will close the issue for now. If things have been changed, please reopen the issue and I will merge my PR.
