### ISSUE TITLE
Openstack: make image username an option

### ISSUE THREAD

**Issue by lwatta** [GoogleCloudPlatform/PerfKitBenchmarker#780]
Can we make the image username a cli option? Currently its hardcoded to "ubuntu". 
Can we create something like openstack_image_username and default to ubuntu?
We use tend to create all our images with "cloud-user" so its the same for RHEL and Ubuntu.

I've already hacked up my local copy to do this.

**Comment by voellm** [comment]
@meteorfox @mateusz-blaszkowski  Who might be able to add this in coming change.  You are also very welcome to make a prosed change.

**Comment by lwatta** [comment]
Working on it now

**Comment by skschneider** [comment]
Now that #788 is in, is this issue fixed?

**Comment by lwatta** [comment]
Yes it does fix it. So it can be marked as closed/fixed etc...

**Comment by skschneider** [comment]
Thanks again!
