### ISSUE TITLE
Openstack:Netperf No results for UDP tests on perfkit provisioned VMs

### ISSUE THREAD

**Issue by sgangaraju** [GoogleCloudPlatform/PerfKitBenchmarker#804]
When i ran netperf benchmark tests using default openstack config it seems to not get any values for udp tests wheras tcp tests run fine.

    ./pkb.py --cloud=OpenStack --machine_type=m1.medium --image ubuntu-14.04-cloud-image --benchmarks=netperf --openstack_public_network=ext-net --openstack_private_network=sai_proj_net 
   
   
2016-01-14 18:45:04,568 429f127d MainThread netperf(1/1) INFO     Ran ssh -A -p 22 ubuntu@10.210.18.202 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/6r/7jjg694x3w9_x9g2x7n7_0pj_m09f4/T/perfkitbenchmarker/run_429f127d/perfkitbenchmarker_keyfile /tmp/pkb/netperf-2.6.0/src/netperf -p 20000 -j -t UDP_RR -H 10.210.18.201 -l 60   -- -P 20001 -o THROUGHPUT,THROUGHPUT_UNITS,P50_LATENCY,P90_LATENCY,P99_LATENCY,STDDEV_LATENCY,CONFIDENCE_ITERATION,THROUGHPUT_CONFID. Got return code (0).
STDOUT: MIGRATED UDP REQUEST/RESPONSE TEST from 0.0.0.0 (0.0.0.0) port 20001 AF_INET to 10.210.18.201 () port 20001 AF_INET : first burst 0
Throughput,Throughput Units,50th Percentile Latency Microseconds,90th Percentile Latency Microseconds,99th Percentile Latency Microseconds,Stddev Latency Microseconds,Confidence Iterations Run,Throughput Confidence Width (%)
0.00,Trans/s,0,0,0,0.00,1,-1.000

```
 TCP_STREAM_Throughput               718.750000 Mbits/sec                      (ip_type="internal")
  UDP_RR_Transaction_Rate               0.000000 transactions_per_second        (ip_type="external")
  UDP_RR_Latency_p50                    0.000000 us                             (ip_type="external")
  UDP_RR_Latency_p90                    0.000000 us                             (ip_type="external")
  UDP_RR_Latency_p99                    0.000000 us                             (ip_type="external")
  UDP_RR_Latency_stddev                 0.000000 us                             (ip_type="external")
  UDP_RR_Transaction_Rate               0.000000 transactions_per_second        (ip_type="internal")
  UDP_RR_Latency_p50                    0.000000 us                             (ip_type="internal")
  UDP_RR_Latency_p90                    0.000000 us                             (ip_type="internal")
  UDP_RR_Latency_p99                    0.000000 us                             (ip_type="internal")
  UDP_RR_Latency_stddev                 0.000000 us                             (ip_type="internal")
Name     UID       Status   
----------------------------
netperf  netperf0  SUCCEEDED
```
I dont see any errors in logs

I ran the same set of tests on static vms (ubuntu14.04)i have in cloud and was able to get results for both tcp and udp

**Comment by cmccoy** [comment]
Thanks for reporting this. It looks to me like the OpenStack firewall rules function a bit differently than other cloud providers. For most providers we open TCP and UDP whenever a benchmark requests a port be allowed, but OpenStack defaults to [just TCP](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/3f8714a9e62edc715e3ebd634372810224764ec8/perfkitbenchmarker/providers/openstack/os_network.py#L51).

**Comment by meteorfox** [comment]
@sgangaraju The 'quick fix' is to open the UDP port(s) manually in the security group that perfkitbenchmarker creates since it re-uses it.

@cmccoy The 'proper fix' is to add code to open not just TCP but UDP ports as well automatically.

**Comment by meteorfox** [comment]
I'll work on the proper fix for this issue. Also looking at that part of the code I just noticed there's a race to when it check/creates the security group. There should be a lock in there.

**Comment by meteorfox** [comment]
@sgangaraju Also I forgot to mention, if you are using the static VMs then you need to open them manually. Even after the code is added for opening UDP ports, it will not try to open ports for a static VM. Don't forget to allow ICMP protocol as well, or the ping benchmark might not work either.

**Comment by sgangaraju** [comment]
@cmccoy @meteorfox Thanks

Yes, Perfkit_sc_group in openstack had no rules  to allow udp connections

The default security group i have for my cloud has udp,tcp ports open and allows icmp too and thus was able to run netperf,iperf and ping tests succesfully against static vms

I added the rules manually to Perfkit_sc_group to keep udp ports open and was able to get netperf results successfully for tcp and udp

**Comment by meteorfox** [comment]
@sgangaraju Awesome. I'm glad you got it working. The PR #805 should address your problem once it's merged.

**Comment by meteorfox** [comment]
@sgangaraju Closing this issue. The reporter found a workaround, and a solution has been merged.
