### ISSUE TITLE
Guidelines for benchmarking IaaS in a private cloud

### ISSUE THREAD

**Issue by Jramirezg** [GoogleCloudPlatform/PerfKitBenchmarker#823]
Do you have any guidelines for benchmarking IaaS in a private cloud? I am writting a study about how major cloud providers evaluate their data centers.

**Comment by voellm** [comment]
I can explain some things we do at Google.  Will update tomorrow (Tuesday).

**Comment by voellm** [comment]
Not forgotten ... just delayed.

**Comment by voellm** [comment]
PerfKit Benchmark (PKB) was designed to handle Cloud environments first and any cluster of machines (we call these static machines).

One thing I think studies often miss is provisioning speeds.  It is an important difference for Cloud vs Private Clusters,  Provisioning of resource dynamically is a key metric as well as end to end times as a measure of real work done.  Most studies focus on peak flows.

Here is a talk I did laying out the foundation of research which lead to the creation of PKB here https://docs.google.com/presentation/d/14iG0I_KH88V1-HAc-4-795ipM8n6DDILxb3oZB7wLIo/edit?usp=drive_web

Perhaps the most important slides is this one - https://docs.google.com/presentation/d/14iG0I_KH88V1-HAc-4-795ipM8n6DDILxb3oZB7wLIo/edit#slide=id.p74

So in terms of doing your research talk a look at the benchmarks_sets (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/benchmark_sets.py) which group benchmarks together.  Looking at these will start to give you an idea of what difference providers think are important to look at.

As for Google we look at a number of thing;
- Microbenchmarks - These are often the first things customers look at so it make sense that these work well even if they are not fully indicative of true performance. (iperf, netperf, fio, coremark, ... are all microbenchmarks are included)
- Workloads - We look at workloads to see how multiple resources like CPU+MEMORY+DISK+NETWORK work together.  Often times there are really interesting interactions.  (All the YCSB workloads, Redis, Cassandra, copy, mysql, object_services, hadoop, SPEC CPU2006, ... all included)
- Customer codes - This is an area that is very interesting to have and that is real functional end-to-end applications running.  The problem with getting these into the public domain is they often have very confidential data, that a lot of time to get right, etc.  EPFL has a done a good job of this with Cloud Suite and PKB includes 2 of their workloads and they are working to get the remaining integrated.

You can also check out YouTube talks I've done and get more on cloud in talks like this one - https://www.youtube.com/watch?v=9D1fVFpx57o

Hope this helps!

  Tony

**Comment by voellm** [comment]
Please feel free to reopen if you want to talk more.  Also we have a community meeting this coming week on Feb 11th.  Our 1 year anniversary.  You are welcome to attend and all I need is for you to main me your @gmail.com address to voellm@google.com.  We use Hangouts to do the meetings.

**Comment by Jramirezg** [comment]
I am looking for info about scalability, availability, and performance
benchmarking. I would like to know how you perform a benchmark in your data
center for this metrics. Also I operate a private cloud with IaaS and I
will like to benchmark it.
any info, guidelines and experiences you have with perfkitand, I will
preciate your help.
Send me your advices, and info to jramirezg.1944@gmail.com
thanks for your help



2016-02-01 23:47 GMT-05:00 Anthony Voellm aka Tony the P3rfguy <
notifications@github.com>:

> I can explain some things we do at Google. Will update tomorrow (Tuesday).

**Comment by Jramirezg** [comment]
I was wondering if you offer any online courses about perfkit and your
benchmarking methods. thanks

2016-02-06 12:06 GMT-05:00 Anthony Voellm aka Tony the P3rfguy <
notifications@github.com>:

**Comment by Jramirezg** [comment]
I am speccially interested in Flops/joules metrics for efficiency, if you
use this metric and how you measure it. I can take some time to reply
internet is not very good in Cuba
thanks

2016-02-07 17:59 GMT-05:00 Jose Ramirez <jramirezg.1944@gmail.com>:

> I am looking for info about scalability, availability, and performance
> benchmarking. I would like to know how you perform a benchmark in your data
> center for this metrics. Also I operate a private cloud with IaaS and I
> will like to benchmark it.
> any info, guidelines and experiences you have with perfkitand, I will
> preciate your help.
> Send me your advices, and info to jramirezg.1944@gmail.com
> thanks for your help
>
>
>
> 2016-02-01 23:47 GMT-05:00 Anthony Voellm aka Tony the P3rfguy <
> notifications@github.com>:
>
>> I can explain some things we do at Google. Will update tomorrow (Tuesday).
