### ISSUE TITLE
Object_storage failing with "STDOUT: STDERR: Warning: Permanently added '108.170.222.218' (ECDSA) to the list of known hosts. Usage: pip COMMAND [OPTIONS]  pip: error: No command by the name pip show   (maybe you meant "pip install show")"

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#838]
./pkb.py --image=debian-7 --zones=us-central1-c --machine_type=n1-standard-8 --benchmarks=object_storage_service --storage=GCP --object_storage_scenario=api_data

...
STDOUT: STDERR: Warning: Permanently added '108.170.222.218' (ECDSA) to the list of known hosts. Usage: pip COMMAND [OPTIONS]  pip: error: No command by the name pip show   (maybe you meant "pip install show")"

...

perfkit@pkb-d8f9db39-0:~$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

To fix the issue I upgraded pip...
$ sudo apt-get remove python-pip
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python get-pip.py

It looks like the root issues is Debian-7 images are pulling a really old version of pip.  I suggest we update the package install to wget the latest like above.

**Comment by voellm** [comment]
@noahl FYI... maybe you want to fix this.

**Comment by noahl** [comment]
@voellm I assigned myself. I'll work on a PR today.

**Comment by noahl** [comment]
#842 fixes this for me.

**Comment by stfeng** [comment]
Thank you Noah for fixing this for everyone!

**Comment by noahl** [comment]
I just merged #842, so I'm closing this bug.
