### ISSUE TITLE
Move provider-specific requirements-*.txt files into the providers' directories.

### ISSUE THREAD

**Issue by skschneider** [GoogleCloudPlatform/PerfKitBenchmarker#851]
As discussed in #834, this is to avoid cluttering the root directory and to consolidate provider-specific files.

Right now, #829 has some unmerged changes to a provider requirements file. After that, I'll make a PR to copy the files to the new location, while having the existing files in the old location use `-r` to include the files in the new location. After a while, the old files will be removed.

I'm not sure if there's a good way to guide users who have `pip install` commands in their workflows pointing to the old files. There will be updates to `CHANGES.md` with each release, but these are easy to miss. The `pip install` command will fail, and if the job continues, the subsequent `pkb.py` invocation without a `--ignore_package_requirements` flag may fail at some point in the future, when requirements change.

**Comment by skschneider** [comment]
#961 has moved the requirement files to the provider directories, but the old files still exist with a single `-r` line including the corresponding new file. After the v1.5.0 release, I'll remove the old files.

**Comment by skschneider** [comment]
@noahl created #975 to remove the old files.

**Comment by noahl** [comment]
Since #975 is merged, this issue is fixed. Closing.
