### ISSUE TITLE
failure to clean up azure resources when scratch disk size is invalid

### ISSUE THREAD

**Issue by jdc0589** [GoogleCloudPlatform/PerfKitBenchmarker#863]
**Full disclosure**: I had commented out [these assertions](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/azure/azure_disk.py#L108) to get passed an error with the PLRS assertion when I got this error

pkb command : `pkb --cloud Azure --benchmarks=fio --scratch_disk_type=remote_ssd --scratch_disk_size=1024 --machine_type="Standard_DS13" --image="b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_4-LTS-amd64-server-20160222-en-us-30GB"`

Azure makes you specify 1023GB for a 1TB volume, which I forgot about. If you go above that, the scratch disk creation fails, at which point there are multiple pkb issues.

1. it retries disk creation, possibly endlessly. I only let it go a few times before I interrupted it.
2. the resource cleanup process blows up in to what seems like another endless retry attempt when it gets to some disk cleanup stuff.

Log (personal data scrubbed)
[pkb.log.txt](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/164034/pkb.log.txt)

**Comment by jdc0589** [comment]
I will retest with the correct azure_storage_type and the assertions in place and reopen if it persists.

**Comment by ehankland** [comment]
There is a configurable timeout period for commands that PKB thinks are retryable (like creating/deleting disks) - the default is 1200 seconds or 20 minutes. You can control this with the "default_timeout" flag. From the logs it looks like the cleanup wasn't working because Azure was busy doing something else:
```
error:   Disk not deleted: pkb-5df4a917-0-pkb-5df4a917-0-0-201603082148220306
error:   Windows Azure is currently performing an operation on deployment 'pkb-5df4a917-0' that requires exclusive access. Please try again later for operation on disk or image 'pkb-5df4a917-0-pkb-5df4a917-0-0-201603082148220306' associated with the deployment.
```
Eventually (in the 20 min retry window) Azure probably would have allowed the disk deletion request through and cleanup would have proceeded.

**Comment by voellm** [comment]
If you come up with a better timeout here please post back on work is working well.

**Comment by jdc0589** [comment]
no, leave this closed. it was due to some modification I made while trying to solve another issue.
