### ISSUE TITLE
issue with azure_storage_type

### ISSUE THREAD

**Issue by jdc0589** [GoogleCloudPlatform/PerfKitBenchmarker#864]
Based on some assertion errors I got ([due to this](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/azure/azure_disk.py#L108)), it looks like `azure_storage_type` **must** be set to provision a premium disk. However, I'm not seeing a way to do this from the command line if there is no user config file. 

But, it doesn't look like that flag value is really even used anywhere... am I missing something?

Also, when commenting out those assertions, the disk was created, but it looks like it created the disk as a standard disk rather than premium (p30)

**Comment by jdc0589** [comment]
made some last minute updates...

**Comment by voellm** [comment]
@noahl 
Can you add some examples to the questions.

@jdc0589  - The names are here - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/azure/azure_disk.py#L39

**Comment by noahl** [comment]
So you tried `--azure_storage_type=...` from the command line and had no effect? I would have expected that to set the Azure storage type.

Also, which assertions did you comment out?

**Comment by voellm** [comment]
@noahl - Please give some full examples.  Its not always clear how to use
the flags or the options they take.

On Tue, Mar 8, 2016 at 2:27 PM, noahl <notifications@github.com> wrote:

> So you tried --azure_storage_type=... from the command line and had no
> effect? I would have expected that to set the Azure storage type.
>
> Also, which assertions did you comment out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/864#issuecomment-193997300>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by noahl** [comment]
Oh, I see one possible source of confusion. The `--azure_storage_type` flag sets the replication of your storage, and applies to all storage on Azure, including Blob Store, Queues, etc. The options are LRS, PLRS, ZRS, GRS, and RAGRS. You also have to set the `--disk_type` flag, which sets PKB's notion of a disk type. So if you want to create an Azure premium storage disk, you'll need to use `pkb.py --cloud=Azure --disk_type=premium-storage --azure_storage_type=PLRS ...`

**Comment by noahl** [comment]
@jdc0589 - can you post the command you were using, and the output you expected?

**Comment by jdc0589** [comment]
@noahl `--azure_storage_type` is not accepted as a valid cmd line flag.

original pkb command: `pkb --cloud Azure --benchmarks=fio --scratch_disk_type=remote_ssd --azure_storage_type="plrs" --scratch_disk_size=1023 --machine_type="Standard_DS13" --image="b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_4-LTS-amd64-server-20160222-en-us-30GB"`

rejected by the cli parser: `pkb --cloud Azure --benchmarks=fio --scratch_disk_type=remote_ssd --azure_storage_type="plrs" --scratch_disk_size=1023 --machine_type="Standard_DS13" --image="b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_4-LTS-amd64-server-20160222-en-us-30GB"`

**Comment by noahl** [comment]
The issue that our flags are case-sensitive, so you need to capitalize `PLRS`. Sorry for the confusion. Also, putting quotes around "PLRS" isn't necessary, although I don't think they'll hurt if you want to use them.

**Comment by jdc0589** [comment]
@noahl this is still rejected as invalid: `pkb --cloud Azure --benchmarks=fio --scratch_disk_type=premium-storage --azure_storage_type="PLRS" --scratch_disk_size=1023 --machine_type="Standard_DS13" --image="b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_4-LTS-amd64-server-20160222-en-us-30GB"`

am I missing something simple here?

**Comment by noahl** [comment]
@ehankland points out that I missed which disk flag you were using. Unfortunately, we're in the middle of a refactor of the disk type flags. The new method, which will be the only one in the near future, is to get rid of your `--scratch_disk_type` flag and instead use `--data_disk_type=premium-storage`. The error is because the `--scratch_disk_type` flag takes old-style arguments, which do not include `premium-storage`. I'm testing your command with the change from `--scratch_disk_type` to `--data_disk_type`, and I'm not seeing any problems so far, although it's still running.

**Comment by jdc0589** [comment]
@noahl I'm rerunning currently as well (still using --scratch_disk_type, which looks like it was coerced correctly)

**Comment by noahl** [comment]
My test succeeded. I'm closing this issue for now, but please reopen if you run into more problems.

**Comment by jdc0589** [comment]
@noahl mine did as well. looks like this is on me, I just had something wonky in my command after I started trying to add `--azure_storage_type`. Documentation is.....rough, right now though.

**Comment by voellm** [comment]
Perhaps we should update the README.md with some examples and common naming
for the different platforms.  Likely a simple table like...

                      Local SSD         Remote SSD       Remote HD
GCP             <flag value> ...
AWZ
Azure
OpenStack
Racksapce

@noahl - Is this something you can add?

**Comment by jdc0589** [comment]
@voellm That would be extremely valuable. Even more so if each of those examples was also accompanied by a user config file example that did the exact same thing.

**Comment by noahl** [comment]
@voellm Yes, I can add the examples easily.

I'm not sure if we want to put whole sample config files in the README.md, though - it would make it pretty long. What do you think of a folder of sample configs?

**Comment by jdc0589** [comment]
@noahl agreed. a folder with configs would be great. it's easy enough to link straight to those from the readme.

**Comment by noahl** [comment]
Added README examples in #871 .
