### ISSUE TITLE
tox breaks when the environment variable PYTHONPATH is not set (e.g. virtualenv)

### ISSUE THREAD

**Issue by meteorfox** [GoogleCloudPlatform/PerfKitBenchmarker#900]
The recent `scripttests` command added to tox breaks when `PYTHONPATH`env variable is not set. Usually, by default in virtualenvs `PYTHONPATH` is not set, this causes the `setenv` command to raise an error.

```
tox.ConfigError: ConfigError: substitution env:'PYTHONPATH': unknown environment variable 'PYTHONPATH'  or recursive definition.
```

**Comment by meteorfox** [comment]
Easy fix:

```diff
diff --git a/tox.ini b/tox.ini
index 9c63c5b..e477a0d 100644
--- a/tox.ini
+++ b/tox.ini
@@ -17,7 +17,7 @@ deps =
 [testenv:scripttests]
 commands = nosetests {toxinidir}/script-tests []
 setenv = 
-  PYTHONPATH = {toxinidir}/perfkitbenchmarker/scripts:{env:PYTHONPATH}
+  PYTHONPATH = {toxinidir}/perfkitbenchmarker/scripts:{envdir}
 
 [testenv:flake8]
 skip_install = True
```

**Comment by meteorfox** [comment]
@noahl PTAL, this seems to be affecting @ivonindza as well. I have been running with this change locally otherwise tox wouldn't work for me.

**Comment by noahl** [comment]
Closing this because #941 fixes it for me. Please reopen if you see more problems.
