### ISSUE TITLE
iperf benchmark has race condition in saving process id

### ISSUE THREAD

**Issue by hildrum** [GoogleCloudPlatform/PerfKitBenchmarker#921]
It's possible for iperf to save the wrong server id if two copies of the benchmark are running on the same machine.  Instead of using `pgrep -n`, use `$!` to get the process id.

**Comment by ehankland** [comment]
Another option is to run the server inside of the timeout command (http://linux.die.net/man/1/timeout)

**Comment by hildrum** [comment]
The iperf server is started in the prepare phase, so it seemed better not to use a timeout.
