### ISSUE TITLE
Integrate Travis build into unit tests

### ISSUE THREAD

**Issue by noahl** [GoogleCloudPlatform/PerfKitBenchmarker#924]
The build environment on the Travis CI controller is not exactly the same as the one on my workstation (presumably due to poor isolation somewhere), and that's causing me a hard-to-debug error where the unit tests only fail on Travis.

It is possible to build PKB in exactly the travis environment, using [Travis Build](https://github.com/travis-ci/travis-build). This issue is to provide a way to do that conveniently as a developer. (Maybe as part of `hooks/check`, maybe some other way.)

**Comment by ehankland** [comment]
We figured out that this was just due to pandas taking a long time to install which causes Travis to time out after 10 minutes of waiting
