### ISSUE TITLE
Blocking issues of release v1.4.0

### ISSUE THREAD

**Issue by stfeng** [GoogleCloudPlatform/PerfKitBenchmarker#927]
the package hbase installation has a regression introduced by this commit:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/e1a900f51dc2ea6cde1a3f199be538a23ac51c40

Error message is:

2016-04-04 12:29:46,088 da383f03 Thread-96 hbase_ycsb(1/1) INFO     Ran ssh -A -
p 22 perfkit@104.197.164.0 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyCh
ecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o Passwor
dAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAlive
Interval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/run_da383f03/pe
rfkitbenchmarker_keyfile mkdir /tmp/pkb/hbase && curl -L http://www.us.apache.or
g/dist/hbase/1.1.3/hbase-1.1.3-bin.tar.gz | tar -C /tmp/pkb/hbase --strip-compon
ents=1 -xzf -. Got return code (2).
STDOUT: 
STDERR: Warning: Permanently added '104.197.164.0' (ECDSA) to the list of known 
hosts.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   237  100   237    0     0   2443      0 --:--:-- --:--:-- --:--:--  2468

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by stfeng** [comment]
@cmccoy, can you please take a look? Thanks much!

**Comment by cmccoy** [comment]
It looks like 1.1.4 has been released:
http://www-us.apache.org/dist/hbase/1.1.4/

On Mon, Apr 4, 2016 at 12:39 PM, Stanley Feng <notifications@github.com>
wrote:

> @cmccoy <https://github.com/cmccoy>, can you please take a look? Thanks
> much!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/927#issuecomment-205462564>
>



-- 
Connor McCoy | Software Engineer | connormccoy@google.com | 206-876-1657

**Comment by stfeng** [comment]
Perhaps we should always get the latest version? (especially if apache-hbase has a habit of removing old release immediately after they ship a new one...)

**Comment by stfeng** [comment]
I'm also fine with simply bumping up the version to 1.1.4 for a short term fix. Connor, will you make a fix for this? Thx.

**Comment by skschneider** [comment]
To refresh, what's wrong with this one? http://archive.apache.org/dist/hbase/1.1.3/hbase-1.1.3-bin.tar.gz

On a tangential note, I suggest a feature that allows checking the PKB driver machine's data directory for the file before attempting to download from apache.

**Comment by stfeng** [comment]
I tested a fix that uses version 1.1.4, and it worked.

I've pushed a hot fix to release-1.4.0 branch. https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/5d64dbff1f36d95c354bdd121049f214f16baeca
