### ISSUE TITLE
Do you guys do "published-releases"?

### ISSUE THREAD

**Issue by wonderfly** [GoogleCloudPlatform/PerfKitBenchmarker#929]
A published release look like [this](https://help.github.com/articles/about-releases/). The nice thing is that you can get a link to the latest release and share it with your users. May I ask why you chose not to do this? What's the recommended way to download the latest PKB release?

**Comment by ehankland** [comment]
We do tag versions which automatically creates a new release: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/releases

**Comment by wonderfly** [comment]
Yeah, the problem is auto created releases are only [_draft releases_](https://developer.github.com/v3/repos/releases/), not _published releases_. The GitHub API won't show unpublished releases, i.e., if you do
`curl -s "https://api.github.com/repos/GoogleCloudPlatform/PerfKitBenchmarker/releases"`, it shows an empty list, and
`curl -s "https://api.github.com/repos/GoogleCloudPlatform/PerfKitBenchmarker/releases/latest"` gets a 404, whereas if you run it against a repo that _publishes_ releases (e.g. kubernetes), you get the latest version, which is very convenient for users to keep up to date.

I was wondering if you intended not to _publish_ releases for some reason.

Ref: http://stackoverflow.com/questions/26140372/cannot-get-releases-for-a-repo-with-the-github-api

**Comment by ehankland** [comment]
Ah - thanks for explaining. The only reason we didn't publish them is because I don't think we knew what we were doing was only creating draft releases. We'll publish them in the future

**Comment by wonderfly** [comment]
Great. I am not sure but can you try publishing an existing release, e.g., v1.4.0? That'll make my life easier. :smiley:

**Comment by ehankland** [comment]
Done

**Comment by wonderfly** [comment]
Awesome. Now I can simple refer to this link (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/releases/latest) for the latest release.

Thanks for doing that.
