### ISSUE TITLE
cluster_boot output ordering issue

### ISSUE THREAD

**Issue by cbhall** [GoogleCloudPlatform/PerfKitBenchmarker#972]
I ran cluster_boot requesting 48 VMs, and redirecting the output to a file.  My intention was to use a simple awk command on the console output looking for `Boot Time` to find and calculate the average boot time and standard deviation.  This didn't quite work because the output was somewhat garbled:
```
  Boot Time                            33.642686 seconds                        (machine_instance="37")
  Boot Ti2016-04-23 16:19:16,367 47a1a836 MainThread INFO     Publishing 49 samples to /tmp/perfkitbenchmarker/run_47a1a836/perfkitbenchmarker_results.json
2016-04-23 16:19:16,369 47a1a836 MainThread INFO     Benchmark run statuses:
--------------------------------------
Name          UID            Status
--------------------------------------
cluster_boot  cluster_boot0  SUCCEEDED
--------------------------------------
Success rate: 100.00% (1/1)
2016-04-23 16:19:16,369 47a1a836 MainThread INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/run_47a1a836/pkb.log
me                            42.180596 seconds                        (machine_instance="38")
  Boot Time                            40.339968 seconds                        (machine_instance="39")
```
It would be good if PerfKit Benchmarker could maintain a better ordering of the console output.  Yes, I probably should instead look at the json file output of Benchmarker, but the console output initially looked like the simplest approach.

On a related note, it would be good if Benchmarker itself provided an appropriate summary of the performance of a run, such as reporting the average boot time and standard deviation of a cluster_boot run.

**Comment by hildrum** [comment]
I haven't seen this happen; what was your command line?

**Comment by cbhall** [comment]
Sorry, this was my error.  I had thought all output would come on stdout and only errors would be reported on stderr, but I see now that I cannot mix those streams.  Please close this issue.
